// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;
namespace Loscardos.TikTokPartnerSdk.Generated.CustomerService;

public sealed record CustomerServiceCreateConversationRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("buyer_user_id")] string BuyerUserId);


public sealed record CustomerServiceCreateConversationResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] CustomerServiceCreateConversationResponseData Data);

public sealed record CustomerServiceCreateConversationResponseData(
    [property: JsonPropertyName("conversation_id")] string ConversationId);


public sealed record CustomerServiceGetAgentSettingsRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record CustomerServiceGetAgentSettingsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] CustomerServiceGetAgentSettingsResponseData Data);

public sealed record CustomerServiceGetAgentSettingsResponseData(
    [property: JsonPropertyName("can_accept_chat")] bool CanAcceptChat);


public sealed record CustomerServiceGetConversationMessagesRequest(
    [property: JsonPropertyName("conversation_id")] string ConversationId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("locale")] string Locale,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("need_data")] bool? NeedData,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("need_plaintext")] bool? NeedPlaintext,
    [property: JsonPropertyName("page_size")] long PageSize,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("page_token")] string PageToken,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("sort_field")] string SortField,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("sort_order")] string SortOrder,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("time_zone")] string TimeZone);


public sealed record CustomerServiceGetConversationMessagesResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] CustomerServiceGetConversationMessagesResponseData Data);

public sealed record CustomerServiceGetConversationMessagesResponseData(
    [property: JsonPropertyName("next_page_token")] string NextPageToken,
    [property: JsonPropertyName("unsupported_msg_tips")] string UnsupportedMsgTips,
    [property: JsonPropertyName("messages")] IReadOnlyList<CustomerServiceGetConversationMessagesResponseDataMessages> Messages);

public sealed record CustomerServiceGetConversationMessagesResponseDataMessages(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("content")] string Content,
    [property: JsonPropertyName("create_time")] long CreateTime,
    [property: JsonPropertyName("is_visible")] bool IsVisible,
    [property: JsonPropertyName("sender")] CustomerServiceGetConversationMessagesResponseDataMessagesSender Sender,
    [property: JsonPropertyName("index")] string Index,
    [property: JsonPropertyName("data")] string Data,
    [property: JsonPropertyName("plaintext")] string Plaintext);

public sealed record CustomerServiceGetConversationMessagesResponseDataMessagesSender(
    [property: JsonPropertyName("im_user_id")] string ImUserId,
    [property: JsonPropertyName("role")] string Role,
    [property: JsonPropertyName("nickname")] string Nickname,
    [property: JsonPropertyName("avatar")] string Avatar);


public sealed record CustomerServiceGetConversationsRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("locale")] string Locale,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("need_session_id")] bool? NeedSessionId,
    [property: JsonPropertyName("page_size")] long PageSize,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("page_token")] string PageToken,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record CustomerServiceGetConversationsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] CustomerServiceGetConversationsResponseData Data);

public sealed record CustomerServiceGetConversationsResponseData(
    [property: JsonPropertyName("next_page_token")] string NextPageToken,
    [property: JsonPropertyName("conversations")] IReadOnlyList<CustomerServiceGetConversationsResponseDataConversations> Conversations);

public sealed record CustomerServiceGetConversationsResponseDataConversations(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("participant_count")] long ParticipantCount,
    [property: JsonPropertyName("can_send_message")] bool CanSendMessage,
    [property: JsonPropertyName("unread_count")] long UnreadCount,
    [property: JsonPropertyName("create_time")] long CreateTime,
    [property: JsonPropertyName("participants")] IReadOnlyList<CustomerServiceGetConversationsResponseDataConversationsParticipants> Participants,
    [property: JsonPropertyName("latest_message")] CustomerServiceGetConversationsResponseDataConversationsLatestMessage LatestMessage,
    [property: JsonPropertyName("cur_session_id")] string CurSessionId);

public sealed record CustomerServiceGetConversationsResponseDataConversationsParticipants(
    [property: JsonPropertyName("im_user_id")] string ImUserId,
    [property: JsonPropertyName("avatar")] string Avatar,
    [property: JsonPropertyName("user_id")] string UserId,
    [property: JsonPropertyName("role")] string Role,
    [property: JsonPropertyName("nickname")] string Nickname,
    [property: JsonPropertyName("buyer_platform")] string BuyerPlatform);

public sealed record CustomerServiceGetConversationsResponseDataConversationsLatestMessage(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("content")] string Content,
    [property: JsonPropertyName("create_time")] long CreateTime,
    [property: JsonPropertyName("is_visible")] bool IsVisible,
    [property: JsonPropertyName("sender")] CustomerServiceGetConversationsResponseDataConversationsLatestMessageSender Sender,
    [property: JsonPropertyName("index")] string Index);

public sealed record CustomerServiceGetConversationsResponseDataConversationsLatestMessageSender(
    [property: JsonPropertyName("im_user_id")] string ImUserId,
    [property: JsonPropertyName("avatar")] string Avatar,
    [property: JsonPropertyName("role")] string Role,
    [property: JsonPropertyName("nickname")] string Nickname);


public sealed record CustomerServiceReadMessageRequest(
    [property: JsonPropertyName("conversation_id")] string ConversationId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record CustomerServiceReadMessageResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] object Data);


public sealed record CustomerServiceSendMessageRequest(
    [property: JsonPropertyName("conversation_id")] string ConversationId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("content")] string Content);


public sealed record CustomerServiceSendMessageResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] CustomerServiceSendMessageResponseData Data);

public sealed record CustomerServiceSendMessageResponseData(
    [property: JsonPropertyName("message_id")] string MessageId);


public sealed record CustomerServiceUpdateAgentSettingsRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("can_accept_chat")] bool CanAcceptChat);


public sealed record CustomerServiceUpdateAgentSettingsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] object Data);


public sealed record CustomerServiceUploadBuyerMessagesImageRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("data")] string Data);


public sealed record CustomerServiceUploadBuyerMessagesImageResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] CustomerServiceUploadBuyerMessagesImageResponseData Data);

public sealed record CustomerServiceUploadBuyerMessagesImageResponseData(
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("width")] long Width,
    [property: JsonPropertyName("height")] long Height);


public sealed record CustomerServiceGetCustomerServicePerformanceRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("support_date_ge")] string SupportDateGe,
    [property: JsonPropertyName("support_date_lt")] string SupportDateLt);


public sealed record CustomerServiceGetCustomerServicePerformanceResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] CustomerServiceGetCustomerServicePerformanceResponseData Data);

public sealed record CustomerServiceGetCustomerServicePerformanceResponseData(
    [property: JsonPropertyName("performance")] CustomerServiceGetCustomerServicePerformanceResponseDataPerformance Performance);

public sealed record CustomerServiceGetCustomerServicePerformanceResponseDataPerformance(
    [property: JsonPropertyName("support_session_count")] long SupportSessionCount,
    [property: JsonPropertyName("response_percentage")] string ResponsePercentage,
    [property: JsonPropertyName("satisfaction_percentage")] string SatisfactionPercentage,
    [property: JsonPropertyName("response_time_mins")] string ResponseTimeMins,
    [property: JsonPropertyName("conversion_rate")] string ConversionRate,
    [property: JsonPropertyName("cs_guided_gmv")] string CsGuidedGmv,
    [property: JsonPropertyName("currency")] string Currency);


public sealed record CustomerServiceGetConversationRequest(
    [property: JsonPropertyName("conversation_id")] string ConversationId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("need_session_id")] bool? NeedSessionId,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record CustomerServiceGetConversationResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] CustomerServiceGetConversationResponseData Data);

public sealed record CustomerServiceGetConversationResponseData(
    [property: JsonPropertyName("conversation")] CustomerServiceGetConversationResponseDataConversation Conversation);

public sealed record CustomerServiceGetConversationResponseDataConversation(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("participant_count")] long ParticipantCount,
    [property: JsonPropertyName("participants")] IReadOnlyList<CustomerServiceGetConversationResponseDataConversationParticipants> Participants,
    [property: JsonPropertyName("create_time")] long CreateTime,
    [property: JsonPropertyName("unread_count")] long UnreadCount,
    [property: JsonPropertyName("cur_session_id")] string CurSessionId);

public sealed record CustomerServiceGetConversationResponseDataConversationParticipants(
    [property: JsonPropertyName("im_user_id")] string ImUserId,
    [property: JsonPropertyName("role")] string Role,
    [property: JsonPropertyName("nickname")] string Nickname,
    [property: JsonPropertyName("avatar")] string Avatar,
    [property: JsonPropertyName("user_id")] string UserId,
    [property: JsonPropertyName("platform")] string Platform);


public sealed record CustomerServiceSearchSessionsRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("locale")] string Locale,
    [property: JsonPropertyName("page_size")] long PageSize,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("page_token")] string PageToken,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("begin_time_ge")] long BeginTimeGe,
    [property: JsonPropertyName("begin_time_lt")] long BeginTimeLt,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("buyer_nickname")] string BuyerNickname);


public sealed record CustomerServiceSearchSessionsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] CustomerServiceSearchSessionsResponseData Data);

public sealed record CustomerServiceSearchSessionsResponseData(
    [property: JsonPropertyName("next_page_token")] string NextPageToken,
    [property: JsonPropertyName("sessions")] IReadOnlyList<CustomerServiceSearchSessionsResponseDataSessions> Sessions);

public sealed record CustomerServiceSearchSessionsResponseDataSessions(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("conversation_id")] string ConversationId,
    [property: JsonPropertyName("begin_time")] long BeginTime,
    [property: JsonPropertyName("end_time")] long EndTime,
    [property: JsonPropertyName("buyer_nickname")] string BuyerNickname,
    [property: JsonPropertyName("chat_tags")] IReadOnlyList<string> ChatTags,
    [property: JsonPropertyName("satisfaction_score")] long SatisfactionScore,
    [property: JsonPropertyName("dissatisfaction_reason")] string DissatisfactionReason,
    [property: JsonPropertyName("first_response_late")] bool FirstResponseLate,
    [property: JsonPropertyName("first_response_time")] long FirstResponseTime);
