// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;
namespace Loscardos.TikTokPartnerSdk.Generated.Promotion;

public sealed record PromotionCreateActivityRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonPropertyName("activity_type")] string ActivityType,
    [property: JsonPropertyName("product_level")] string ProductLevel,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("duration_type")] string DurationType,
    [property: JsonPropertyName("begin_time")] long BeginTime,
    [property: JsonPropertyName("end_time")] long EndTime,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("participation_limit")] IReadOnlyList<PromotionCreateActivityRequestParticipationLimit> ParticipationLimit,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("discount")] PromotionCreateActivityRequestDiscount Discount,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("target_user_info")] PromotionCreateActivityRequestTargetUserInfo TargetUserInfo);

public sealed record PromotionCreateActivityRequestParticipationLimit(
    [property: JsonPropertyName("type")] string Type);

public sealed record PromotionCreateActivityRequestDiscount(
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("shipping_discount")] PromotionCreateActivityRequestDiscountShippingDiscount ShippingDiscount,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("bmsm_discount")] PromotionCreateActivityRequestDiscountBmsmDiscount BmsmDiscount,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("gift_discount")] PromotionCreateActivityRequestDiscountGiftDiscount GiftDiscount,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("bxgy_discount")] PromotionCreateActivityRequestDiscountBxgyDiscount BxgyDiscount);

public sealed record PromotionCreateActivityRequestDiscountShippingDiscount(
    [property: JsonPropertyName("threshold_type")] string ThresholdType,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("threshold_value")] string ThresholdValue,
    [property: JsonPropertyName("type")] string Type,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("value")] string Value,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("shipping_method")] string ShippingMethod,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("inventory_type")] string InventoryType,
    [property: JsonPropertyName("area_scope")] PromotionCreateActivityRequestDiscountShippingDiscountAreaScope AreaScope);

public sealed record PromotionCreateActivityRequestDiscountShippingDiscountAreaScope(
    [property: JsonPropertyName("type")] string Type,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("specific_areas")] IReadOnlyList<string> SpecificAreas);

public sealed record PromotionCreateActivityRequestDiscountBmsmDiscount(
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("details")] IReadOnlyList<PromotionCreateActivityRequestDiscountBmsmDiscountDetails> Details);

public sealed record PromotionCreateActivityRequestDiscountBmsmDiscountDetails(
    [property: JsonPropertyName("tier")] long Tier,
    [property: JsonPropertyName("threshold_type")] string ThresholdType,
    [property: JsonPropertyName("threshold_value")] string ThresholdValue,
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("value")] string Value);

public sealed record PromotionCreateActivityRequestDiscountGiftDiscount(
    [property: JsonPropertyName("gift_receiving_type")] string GiftReceivingType,
    [property: JsonPropertyName("gift_infos")] IReadOnlyList<PromotionCreateActivityRequestDiscountGiftDiscountGiftInfos> GiftInfos);

public sealed record PromotionCreateActivityRequestDiscountGiftDiscountGiftInfos(
    [property: JsonPropertyName("tier")] long Tier,
    [property: JsonPropertyName("threshold_type")] string ThresholdType,
    [property: JsonPropertyName("threshold_value")] string ThresholdValue,
    [property: JsonPropertyName("gift_details")] IReadOnlyList<PromotionCreateActivityRequestDiscountGiftDiscountGiftInfosGiftDetails> GiftDetails);

public sealed record PromotionCreateActivityRequestDiscountGiftDiscountGiftInfosGiftDetails(
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("total_claim_limit")] string TotalClaimLimit);

public sealed record PromotionCreateActivityRequestDiscountBxgyDiscount(
    [property: JsonPropertyName("threshold_type")] string ThresholdType,
    [property: JsonPropertyName("threshold_value")] string ThresholdValue,
    [property: JsonPropertyName("discount_type")] string DiscountType,
    [property: JsonPropertyName("discount_value")] string DiscountValue,
    [property: JsonPropertyName("benefit_max_applicable_quantity")] string BenefitMaxApplicableQuantity,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("benefit_max_applicable_times")] string BenefitMaxApplicableTimes);

public sealed record PromotionCreateActivityRequestTargetUserInfo(
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("user_type")] string UserType);


public sealed record PromotionCreateActivityResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] PromotionCreateActivityResponseData Data);

public sealed record PromotionCreateActivityResponseData(
    [property: JsonPropertyName("activity_id")] string ActivityId,
    [property: JsonPropertyName("create_time")] long CreateTime,
    [property: JsonPropertyName("update_time")] long UpdateTime,
    [property: JsonPropertyName("status")] string Status);


public sealed record PromotionDeactivateActivityRequest(
    [property: JsonPropertyName("activity_id")] string ActivityId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record PromotionDeactivateActivityResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] PromotionDeactivateActivityResponseData Data);

public sealed record PromotionDeactivateActivityResponseData(
    [property: JsonPropertyName("activity_id")] string ActivityId,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("update_time")] long UpdateTime);


public sealed record PromotionGetActivityRequest(
    [property: JsonPropertyName("activity_id")] string ActivityId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record PromotionGetActivityResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] PromotionGetActivityResponseData Data);

public sealed record PromotionGetActivityResponseData(
    [property: JsonPropertyName("activity_id")] string ActivityId,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonPropertyName("activity_type")] string ActivityType,
    [property: JsonPropertyName("duration_type")] string DurationType,
    [property: JsonPropertyName("begin_time")] long BeginTime,
    [property: JsonPropertyName("end_time")] long EndTime,
    [property: JsonPropertyName("participation_limit")] IReadOnlyList<PromotionGetActivityResponseDataParticipationLimit> ParticipationLimit,
    [property: JsonPropertyName("products")] IReadOnlyList<PromotionGetActivityResponseDataProducts> Products,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("create_time")] long CreateTime,
    [property: JsonPropertyName("update_time")] long UpdateTime,
    [property: JsonPropertyName("product_level")] string ProductLevel,
    [property: JsonPropertyName("activity_commands")] IReadOnlyList<string> ActivityCommands,
    [property: JsonPropertyName("discount")] PromotionGetActivityResponseDataDiscount Discount,
    [property: JsonPropertyName("target_user_info")] PromotionGetActivityResponseDataTargetUserInfo TargetUserInfo,
    [property: JsonPropertyName("benefit_products")] IReadOnlyList<PromotionGetActivityResponseDataBenefitProducts> BenefitProducts);

public sealed record PromotionGetActivityResponseDataParticipationLimit(
    [property: JsonPropertyName("type")] string Type);

public sealed record PromotionGetActivityResponseDataProducts(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("activity_price")] PromotionGetActivityResponseDataProductsActivityPrice ActivityPrice,
    [property: JsonPropertyName("quantity_limit")] long QuantityLimit,
    [property: JsonPropertyName("quantity_per_user")] long QuantityPerUser,
    [property: JsonPropertyName("discount")] string Discount,
    [property: JsonPropertyName("skus")] IReadOnlyList<PromotionGetActivityResponseDataProductsSkus> Skus);

public sealed record PromotionGetActivityResponseDataProductsActivityPrice(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record PromotionGetActivityResponseDataProductsSkus(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("discount")] string Discount,
    [property: JsonPropertyName("quantity_limit")] long QuantityLimit,
    [property: JsonPropertyName("quantity_per_user")] long QuantityPerUser,
    [property: JsonPropertyName("activity_price")] PromotionGetActivityResponseDataProductsSkusActivityPrice ActivityPrice);

public sealed record PromotionGetActivityResponseDataProductsSkusActivityPrice(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record PromotionGetActivityResponseDataDiscount(
    [property: JsonPropertyName("shipping_discount")] PromotionGetActivityResponseDataDiscountShippingDiscount ShippingDiscount,
    [property: JsonPropertyName("bmsm_discount")] PromotionGetActivityResponseDataDiscountBmsmDiscount BmsmDiscount,
    [property: JsonPropertyName("gift_discount")] PromotionGetActivityResponseDataDiscountGiftDiscount GiftDiscount,
    [property: JsonPropertyName("bxgy_discount")] PromotionGetActivityResponseDataDiscountBxgyDiscount BxgyDiscount);

public sealed record PromotionGetActivityResponseDataDiscountShippingDiscount(
    [property: JsonPropertyName("threshold_type")] string ThresholdType,
    [property: JsonPropertyName("threshold_value")] string ThresholdValue,
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("value")] string Value,
    [property: JsonPropertyName("shipping_method")] string ShippingMethod,
    [property: JsonPropertyName("inventory_type")] string InventoryType,
    [property: JsonPropertyName("area_scope")] PromotionGetActivityResponseDataDiscountShippingDiscountAreaScope AreaScope);

public sealed record PromotionGetActivityResponseDataDiscountShippingDiscountAreaScope(
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("specific_areas")] IReadOnlyList<string> SpecificAreas);

public sealed record PromotionGetActivityResponseDataDiscountBmsmDiscount(
    [property: JsonPropertyName("details")] IReadOnlyList<PromotionGetActivityResponseDataDiscountBmsmDiscountDetails> Details);

public sealed record PromotionGetActivityResponseDataDiscountBmsmDiscountDetails(
    [property: JsonPropertyName("tier")] long Tier,
    [property: JsonPropertyName("threshold_type")] string ThresholdType,
    [property: JsonPropertyName("threshold_value")] string ThresholdValue,
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("value")] string Value);

public sealed record PromotionGetActivityResponseDataDiscountGiftDiscount(
    [property: JsonPropertyName("gift_receiving_type")] string GiftReceivingType,
    [property: JsonPropertyName("gift_infos")] IReadOnlyList<PromotionGetActivityResponseDataDiscountGiftDiscountGiftInfos> GiftInfos);

public sealed record PromotionGetActivityResponseDataDiscountGiftDiscountGiftInfos(
    [property: JsonPropertyName("tier")] long Tier,
    [property: JsonPropertyName("threshold_type")] string ThresholdType,
    [property: JsonPropertyName("threshold_value")] string ThresholdValue,
    [property: JsonPropertyName("gift_details")] IReadOnlyList<PromotionGetActivityResponseDataDiscountGiftDiscountGiftInfosGiftDetails> GiftDetails);

public sealed record PromotionGetActivityResponseDataDiscountGiftDiscountGiftInfosGiftDetails(
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("total_claim_limit")] string TotalClaimLimit);

public sealed record PromotionGetActivityResponseDataDiscountBxgyDiscount(
    [property: JsonPropertyName("threshold_type")] string ThresholdType,
    [property: JsonPropertyName("threshold_value")] string ThresholdValue,
    [property: JsonPropertyName("discount_type")] string DiscountType,
    [property: JsonPropertyName("discount_value")] string DiscountValue,
    [property: JsonPropertyName("benefit_max_applicable_quantity")] string BenefitMaxApplicableQuantity,
    [property: JsonPropertyName("benefit_max_applicable_times")] string BenefitMaxApplicableTimes);

public sealed record PromotionGetActivityResponseDataTargetUserInfo(
    [property: JsonPropertyName("user_type")] string UserType);

public sealed record PromotionGetActivityResponseDataBenefitProducts(
    [property: JsonPropertyName("id")] string Id);


public sealed record PromotionRemoveActivityProductRequest(
    [property: JsonPropertyName("activity_id")] string ActivityId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("product_ids")] IReadOnlyList<string> ProductIds,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("sku_ids")] IReadOnlyList<string> SkuIds,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("benefit_product_ids")] IReadOnlyList<string> BenefitProductIds,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("exclude_product_ids")] IReadOnlyList<string> ExcludeProductIds);


public sealed record PromotionRemoveActivityProductResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] PromotionRemoveActivityProductResponseData Data);

public sealed record PromotionRemoveActivityProductResponseData(
    [property: JsonPropertyName("activity_id")] string ActivityId,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("update_time")] long UpdateTime);


public sealed record PromotionSearchActivitiesRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("status")] string Status,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("activity_title")] string ActivityTitle,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("page_size")] long PageSize,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("page_token")] string PageToken,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("activity_type")] string ActivityType);


public sealed record PromotionSearchActivitiesResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] PromotionSearchActivitiesResponseData Data);

public sealed record PromotionSearchActivitiesResponseData(
    [property: JsonPropertyName("total_count")] long TotalCount,
    [property: JsonPropertyName("next_page_token")] string NextPageToken,
    [property: JsonPropertyName("activities")] IReadOnlyList<PromotionSearchActivitiesResponseDataActivities> Activities);

public sealed record PromotionSearchActivitiesResponseDataActivities(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonPropertyName("activity_type")] string ActivityType,
    [property: JsonPropertyName("duration_type")] string DurationType,
    [property: JsonPropertyName("begin_time")] long BeginTime,
    [property: JsonPropertyName("end_time")] long EndTime,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("create_time")] long CreateTime,
    [property: JsonPropertyName("update_time")] long UpdateTime,
    [property: JsonPropertyName("product_level")] string ProductLevel,
    [property: JsonPropertyName("activity_commands")] IReadOnlyList<string> ActivityCommands,
    [property: JsonPropertyName("participation_limit")] IReadOnlyList<PromotionSearchActivitiesResponseDataActivitiesParticipationLimit> ParticipationLimit,
    [property: JsonPropertyName("discount")] PromotionSearchActivitiesResponseDataActivitiesDiscount Discount);

public sealed record PromotionSearchActivitiesResponseDataActivitiesParticipationLimit(
    [property: JsonPropertyName("type")] string Type);

public sealed record PromotionSearchActivitiesResponseDataActivitiesDiscount(
    [property: JsonPropertyName("shipping_discount")] PromotionSearchActivitiesResponseDataActivitiesDiscountShippingDiscount ShippingDiscount,
    [property: JsonPropertyName("bmsm_discount")] PromotionSearchActivitiesResponseDataActivitiesDiscountBmsmDiscount BmsmDiscount,
    [property: JsonPropertyName("gift_discount")] PromotionSearchActivitiesResponseDataActivitiesDiscountGiftDiscount GiftDiscount,
    [property: JsonPropertyName("bxgy_discount")] PromotionSearchActivitiesResponseDataActivitiesDiscountBxgyDiscount BxgyDiscount);

public sealed record PromotionSearchActivitiesResponseDataActivitiesDiscountShippingDiscount(
    [property: JsonPropertyName("threshold_type")] string ThresholdType,
    [property: JsonPropertyName("threshold_value")] string ThresholdValue,
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("value")] string Value,
    [property: JsonPropertyName("shipping_method")] string ShippingMethod,
    [property: JsonPropertyName("inventory_type")] string InventoryType,
    [property: JsonPropertyName("area_scope")] PromotionSearchActivitiesResponseDataActivitiesDiscountShippingDiscountAreaScope AreaScope);

public sealed record PromotionSearchActivitiesResponseDataActivitiesDiscountShippingDiscountAreaScope(
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("specific_areas")] IReadOnlyList<string> SpecificAreas);

public sealed record PromotionSearchActivitiesResponseDataActivitiesDiscountBmsmDiscount(
    [property: JsonPropertyName("details")] IReadOnlyList<PromotionSearchActivitiesResponseDataActivitiesDiscountBmsmDiscountDetails> Details);

public sealed record PromotionSearchActivitiesResponseDataActivitiesDiscountBmsmDiscountDetails(
    [property: JsonPropertyName("tier")] long Tier,
    [property: JsonPropertyName("threshold_type")] string ThresholdType,
    [property: JsonPropertyName("threshold_value")] string ThresholdValue,
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("value")] string Value);

public sealed record PromotionSearchActivitiesResponseDataActivitiesDiscountGiftDiscount(
    [property: JsonPropertyName("gift_receiving_type")] string GiftReceivingType,
    [property: JsonPropertyName("gift_infos")] IReadOnlyList<PromotionSearchActivitiesResponseDataActivitiesDiscountGiftDiscountGiftInfos> GiftInfos);

public sealed record PromotionSearchActivitiesResponseDataActivitiesDiscountGiftDiscountGiftInfos(
    [property: JsonPropertyName("tier")] long Tier,
    [property: JsonPropertyName("threshold_type")] string ThresholdType,
    [property: JsonPropertyName("threshold_value")] string ThresholdValue,
    [property: JsonPropertyName("gift_details")] IReadOnlyList<PromotionSearchActivitiesResponseDataActivitiesDiscountGiftDiscountGiftInfosGiftDetails> GiftDetails);

public sealed record PromotionSearchActivitiesResponseDataActivitiesDiscountGiftDiscountGiftInfosGiftDetails(
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("total_claim_limit")] string TotalClaimLimit);

public sealed record PromotionSearchActivitiesResponseDataActivitiesDiscountBxgyDiscount(
    [property: JsonPropertyName("threshold_type")] string ThresholdType,
    [property: JsonPropertyName("threshold_value")] string ThresholdValue,
    [property: JsonPropertyName("discount_type")] string DiscountType,
    [property: JsonPropertyName("discount_value")] string DiscountValue,
    [property: JsonPropertyName("benefit_max_applicable_quantity")] string BenefitMaxApplicableQuantity,
    [property: JsonPropertyName("benefit_max_applicable_times")] string BenefitMaxApplicableTimes);


public sealed record PromotionUpdateActivityProductRequest(
    [property: JsonPropertyName("activity_id")] string PathActivityId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("products")] IReadOnlyList<PromotionUpdateActivityProductRequestProducts> Products,
    [property: JsonPropertyName("activity_id")] string BodyActivityId,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("benefit_product_ids")] IReadOnlyList<string> BenefitProductIds,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("exclude_product_ids")] IReadOnlyList<string> ExcludeProductIds);

public sealed record PromotionUpdateActivityProductRequestProducts(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("activity_price_amount")] string ActivityPriceAmount,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("discount")] string Discount,
    [property: JsonPropertyName("quantity_limit")] long QuantityLimit,
    [property: JsonPropertyName("quantity_per_user")] long QuantityPerUser,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("skus")] IReadOnlyList<PromotionUpdateActivityProductRequestProductsSkus> Skus);

public sealed record PromotionUpdateActivityProductRequestProductsSkus(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("activity_price_amount")] string ActivityPriceAmount,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("discount")] string Discount,
    [property: JsonPropertyName("quantity_limit")] long QuantityLimit,
    [property: JsonPropertyName("quantity_per_user")] long QuantityPerUser);


public sealed record PromotionUpdateActivityProductResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] PromotionUpdateActivityProductResponseData Data);

public sealed record PromotionUpdateActivityProductResponseData(
    [property: JsonPropertyName("activity_id")] string ActivityId,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonPropertyName("update_time")] long UpdateTime,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("total_count")] long TotalCount);


public sealed record PromotionUpdateActivityRequest(
    [property: JsonPropertyName("activity_id")] string ActivityId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("duration_type")] string DurationType,
    [property: JsonPropertyName("begin_time")] long BeginTime,
    [property: JsonPropertyName("end_time")] long EndTime,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("product_level")] string ProductLevel,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("participation_limit")] IReadOnlyList<PromotionUpdateActivityRequestParticipationLimit> ParticipationLimit,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("discount")] PromotionUpdateActivityRequestDiscount Discount,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("target_user_info")] PromotionUpdateActivityRequestTargetUserInfo TargetUserInfo);

public sealed record PromotionUpdateActivityRequestParticipationLimit(
    [property: JsonPropertyName("type")] string Type);

public sealed record PromotionUpdateActivityRequestDiscount(
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("shipping_discount")] PromotionUpdateActivityRequestDiscountShippingDiscount ShippingDiscount,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("bmsm_discount")] PromotionUpdateActivityRequestDiscountBmsmDiscount BmsmDiscount,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("gift_discount")] PromotionUpdateActivityRequestDiscountGiftDiscount GiftDiscount,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("bxgy_discount")] PromotionUpdateActivityRequestDiscountBxgyDiscount BxgyDiscount);

public sealed record PromotionUpdateActivityRequestDiscountShippingDiscount(
    [property: JsonPropertyName("threshold_type")] string ThresholdType,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("threshold_value")] string ThresholdValue,
    [property: JsonPropertyName("type")] string Type,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("value")] string Value,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("shipping_method")] string ShippingMethod,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("inventory_type")] string InventoryType,
    [property: JsonPropertyName("area_scope")] PromotionUpdateActivityRequestDiscountShippingDiscountAreaScope AreaScope);

public sealed record PromotionUpdateActivityRequestDiscountShippingDiscountAreaScope(
    [property: JsonPropertyName("type")] string Type,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("specific_areas")] IReadOnlyList<string> SpecificAreas);

public sealed record PromotionUpdateActivityRequestDiscountBmsmDiscount(
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("details")] IReadOnlyList<PromotionUpdateActivityRequestDiscountBmsmDiscountDetails> Details);

public sealed record PromotionUpdateActivityRequestDiscountBmsmDiscountDetails(
    [property: JsonPropertyName("tier")] long Tier,
    [property: JsonPropertyName("threshold_type")] string ThresholdType,
    [property: JsonPropertyName("threshold_value")] string ThresholdValue,
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("value")] string Value);

public sealed record PromotionUpdateActivityRequestDiscountGiftDiscount(
    [property: JsonPropertyName("gift_receiving_type")] string GiftReceivingType,
    [property: JsonPropertyName("gift_infos")] IReadOnlyList<PromotionUpdateActivityRequestDiscountGiftDiscountGiftInfos> GiftInfos);

public sealed record PromotionUpdateActivityRequestDiscountGiftDiscountGiftInfos(
    [property: JsonPropertyName("tier")] long Tier,
    [property: JsonPropertyName("threshold_type")] string ThresholdType,
    [property: JsonPropertyName("threshold_value")] string ThresholdValue,
    [property: JsonPropertyName("gift_details")] IReadOnlyList<PromotionUpdateActivityRequestDiscountGiftDiscountGiftInfosGiftDetails> GiftDetails);

public sealed record PromotionUpdateActivityRequestDiscountGiftDiscountGiftInfosGiftDetails(
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("total_claim_limit")] string TotalClaimLimit);

public sealed record PromotionUpdateActivityRequestDiscountBxgyDiscount(
    [property: JsonPropertyName("threshold_type")] string ThresholdType,
    [property: JsonPropertyName("threshold_value")] string ThresholdValue,
    [property: JsonPropertyName("discount_type")] string DiscountType,
    [property: JsonPropertyName("discount_value")] string DiscountValue,
    [property: JsonPropertyName("benefit_max_applicable_quantity")] string BenefitMaxApplicableQuantity,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("benefit_max_applicable_times")] string BenefitMaxApplicableTimes);

public sealed record PromotionUpdateActivityRequestTargetUserInfo(
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("user_type")] string UserType);


public sealed record PromotionUpdateActivityResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] PromotionUpdateActivityResponseData Data);

public sealed record PromotionUpdateActivityResponseData(
    [property: JsonPropertyName("activity_id")] string ActivityId,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonPropertyName("update_time")] long UpdateTime);


public sealed record PromotionGetCouponRequest(
    [property: JsonPropertyName("coupon_id")] string CouponId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record PromotionGetCouponResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] PromotionGetCouponResponseData Data);

public sealed record PromotionGetCouponResponseData(
    [property: JsonPropertyName("coupon")] PromotionGetCouponResponseDataCoupon Coupon);

public sealed record PromotionGetCouponResponseDataCoupon(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonPropertyName("display_type")] string DisplayType,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("create_time")] long CreateTime,
    [property: JsonPropertyName("update_time")] long UpdateTime,
    [property: JsonPropertyName("claim_duration")] PromotionGetCouponResponseDataCouponClaimDuration ClaimDuration,
    [property: JsonPropertyName("redemption_duration")] PromotionGetCouponResponseDataCouponRedemptionDuration RedemptionDuration,
    [property: JsonPropertyName("display_channels")] IReadOnlyList<string> DisplayChannels,
    [property: JsonPropertyName("promo_code")] string PromoCode,
    [property: JsonPropertyName("target_buyer_segment")] string TargetBuyerSegment,
    [property: JsonPropertyName("usage_limits")] PromotionGetCouponResponseDataCouponUsageLimits UsageLimits,
    [property: JsonPropertyName("usage_stats")] PromotionGetCouponResponseDataCouponUsageStats UsageStats,
    [property: JsonPropertyName("discount")] PromotionGetCouponResponseDataCouponDiscount Discount,
    [property: JsonPropertyName("threshold")] PromotionGetCouponResponseDataCouponThreshold Threshold,
    [property: JsonPropertyName("product_scope")] string ProductScope,
    [property: JsonPropertyName("product_ids")] IReadOnlyList<string> ProductIds,
    [property: JsonPropertyName("seller_tnc")] string SellerTnc,
    [property: JsonPropertyName("creation_source")] string CreationSource,
    [property: JsonPropertyName("live_tasks")] IReadOnlyList<PromotionGetCouponResponseDataCouponLiveTasks> LiveTasks);

public sealed record PromotionGetCouponResponseDataCouponClaimDuration(
    [property: JsonPropertyName("start_time")] long StartTime,
    [property: JsonPropertyName("end_time")] long EndTime);

public sealed record PromotionGetCouponResponseDataCouponRedemptionDuration(
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("start_time")] long StartTime,
    [property: JsonPropertyName("end_time")] long EndTime,
    [property: JsonPropertyName("relative_time")] long RelativeTime);

public sealed record PromotionGetCouponResponseDataCouponUsageLimits(
    [property: JsonPropertyName("single_buyer_claim_limit")] long SingleBuyerClaimLimit,
    [property: JsonPropertyName("total_claim_limit")] long TotalClaimLimit,
    [property: JsonPropertyName("redemption_limit")] long RedemptionLimit);

public sealed record PromotionGetCouponResponseDataCouponUsageStats(
    [property: JsonPropertyName("claimed_count")] long ClaimedCount,
    [property: JsonPropertyName("redeemed_count")] long RedeemedCount);

public sealed record PromotionGetCouponResponseDataCouponDiscount(
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("reduction_amount")] PromotionGetCouponResponseDataCouponDiscountReductionAmount ReductionAmount,
    [property: JsonPropertyName("percentage")] string Percentage,
    [property: JsonPropertyName("max_discount")] PromotionGetCouponResponseDataCouponDiscountMaxDiscount MaxDiscount);

public sealed record PromotionGetCouponResponseDataCouponDiscountReductionAmount(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record PromotionGetCouponResponseDataCouponDiscountMaxDiscount(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record PromotionGetCouponResponseDataCouponThreshold(
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("min_spend")] PromotionGetCouponResponseDataCouponThresholdMinSpend MinSpend);

public sealed record PromotionGetCouponResponseDataCouponThresholdMinSpend(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record PromotionGetCouponResponseDataCouponLiveTasks(
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("min_watch_time")] string MinWatchTime);


public sealed record PromotionSearchCouponsRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("page_size")] long PageSize,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("page_token")] string PageToken,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("status")] IReadOnlyList<string> Status,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("title_keyword")] string TitleKeyword,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("display_type")] IReadOnlyList<string> DisplayType);


public sealed record PromotionSearchCouponsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] PromotionSearchCouponsResponseData Data);

public sealed record PromotionSearchCouponsResponseData(
    [property: JsonPropertyName("total_count")] long TotalCount,
    [property: JsonPropertyName("next_page_token")] string NextPageToken,
    [property: JsonPropertyName("coupons")] IReadOnlyList<PromotionSearchCouponsResponseDataCoupons> Coupons);

public sealed record PromotionSearchCouponsResponseDataCoupons(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonPropertyName("display_type")] string DisplayType,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("create_time")] long CreateTime,
    [property: JsonPropertyName("update_time")] long UpdateTime,
    [property: JsonPropertyName("claim_duration")] PromotionSearchCouponsResponseDataCouponsClaimDuration ClaimDuration,
    [property: JsonPropertyName("redemption_duration")] PromotionSearchCouponsResponseDataCouponsRedemptionDuration RedemptionDuration,
    [property: JsonPropertyName("promo_code")] string PromoCode,
    [property: JsonPropertyName("target_buyer_segment")] string TargetBuyerSegment,
    [property: JsonPropertyName("usage_limits")] PromotionSearchCouponsResponseDataCouponsUsageLimits UsageLimits,
    [property: JsonPropertyName("discount")] PromotionSearchCouponsResponseDataCouponsDiscount Discount,
    [property: JsonPropertyName("threshold")] PromotionSearchCouponsResponseDataCouponsThreshold Threshold,
    [property: JsonPropertyName("product_scope")] string ProductScope,
    [property: JsonPropertyName("creation_source")] string CreationSource);

public sealed record PromotionSearchCouponsResponseDataCouponsClaimDuration(
    [property: JsonPropertyName("start_time")] long StartTime,
    [property: JsonPropertyName("end_time")] long EndTime);

public sealed record PromotionSearchCouponsResponseDataCouponsRedemptionDuration(
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("start_time")] long StartTime,
    [property: JsonPropertyName("end_time")] long EndTime,
    [property: JsonPropertyName("relative_time")] long RelativeTime);

public sealed record PromotionSearchCouponsResponseDataCouponsUsageLimits(
    [property: JsonPropertyName("single_buyer_claim_limit")] long SingleBuyerClaimLimit,
    [property: JsonPropertyName("total_claim_limit")] long TotalClaimLimit,
    [property: JsonPropertyName("redemption_limit")] long RedemptionLimit);

public sealed record PromotionSearchCouponsResponseDataCouponsDiscount(
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("reduction_amount")] PromotionSearchCouponsResponseDataCouponsDiscountReductionAmount ReductionAmount,
    [property: JsonPropertyName("percentage")] string Percentage,
    [property: JsonPropertyName("max_discount")] PromotionSearchCouponsResponseDataCouponsDiscountMaxDiscount MaxDiscount);

public sealed record PromotionSearchCouponsResponseDataCouponsDiscountReductionAmount(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record PromotionSearchCouponsResponseDataCouponsDiscountMaxDiscount(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record PromotionSearchCouponsResponseDataCouponsThreshold(
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("min_spend")] PromotionSearchCouponsResponseDataCouponsThresholdMinSpend MinSpend);

public sealed record PromotionSearchCouponsResponseDataCouponsThresholdMinSpend(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);
