// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;
namespace TikTokPartnerSdk.Generated.Authorization;

public sealed record AuthorizationGetAuthorizedShopsRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign);


public sealed record AuthorizationGetAuthorizedShopsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId);


public sealed record AuthorizationGetAuthorizedCategoryAssetsRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign);


public sealed record AuthorizationGetAuthorizedCategoryAssetsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AuthorizationGetAuthorizedCategoryAssetsResponseData Data);

public sealed record AuthorizationGetAuthorizedCategoryAssetsResponseData(
    [property: JsonPropertyName("category_assets")] IReadOnlyList<AuthorizationGetAuthorizedCategoryAssetsResponseDataCategoryAssets> CategoryAssets);

public sealed record AuthorizationGetAuthorizedCategoryAssetsResponseDataCategoryAssets(
    [property: JsonPropertyName("cipher")] string Cipher,
    [property: JsonPropertyName("target_market")] string TargetMarket,
    [property: JsonPropertyName("category")] AuthorizationGetAuthorizedCategoryAssetsResponseDataCategoryAssetsCategory Category);

public sealed record AuthorizationGetAuthorizedCategoryAssetsResponseDataCategoryAssetsCategory(
    [property: JsonPropertyName("id")] long Id,
    [property: JsonPropertyName("name")] string Name);
