// <auto-generated />
#nullable enable
namespace TikTokPartnerSdk.Generated.Authorization;

public sealed record AuthorizationGetAuthorizedShopsRequest();

public sealed record AuthorizationGetAuthorizedShopsResponse(
    int Code,
    string? Message,
    string? RequestId);
