using System.Text;

namespace TikTokPartnerSdk.Generator;

public sealed class ContractsWriter
{
    public string WriteModule(string moduleName, string moduleKey, IReadOnlyList<SchemaEndpoint> endpoints)
    {
        var builder = new StringBuilder();
        var modulePascal = TikTokName.ToPascalCase(moduleKey);

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System.Text.Json.Serialization;");
        builder.AppendLine($"namespace TikTokPartnerSdk.Generated.{modulePascal};");
        builder.AppendLine();

        foreach (var endpoint in endpoints)
        {
            var requestTypeName = TikTokName.ToRequestTypeName(endpoint);
            var responseTypeName = TikTokName.ToResponseTypeName(endpoint);

            WriteRecord(builder, requestTypeName, endpoint.RequestParameters);
            builder.AppendLine();
            WriteNestedTypes(builder, requestTypeName, endpoint.RequestParameters);
            builder.AppendLine();
            WriteRecord(builder, responseTypeName, endpoint.ResponseParameters);
            builder.AppendLine();
            WriteNestedTypes(builder, responseTypeName, endpoint.ResponseParameters);
            builder.AppendLine();
        }

        return builder.ToString().TrimEnd() + Environment.NewLine;
    }

    private static void WriteRecord(StringBuilder builder, string typeName, IReadOnlyList<SchemaParameter> parameters)
    {
        if (parameters.Count == 0)
        {
            builder.AppendLine($"public sealed record {typeName}();");
            return;
        }

        builder.AppendLine($"public sealed record {typeName}(");

        for (var index = 0; index < parameters.Count; index++)
        {
            var parameter = parameters[index];
            var suffix = index == parameters.Count - 1 ? ");" : ",";
            builder.AppendLine(
                $"    [property: JsonPropertyName(\"{parameter.Name}\")] {TikTokTypeMapper.MapType(parameter, typeName)} {TikTokName.ToPropertyName(parameter.Name)}{suffix}");
        }
    }

    private static void WriteNestedTypes(
        StringBuilder builder,
        string parentTypeName,
        IReadOnlyList<SchemaParameter> parameters)
    {
        foreach (var parameter in parameters.Where(static x => x.Children.Count > 0))
        {
            var childTypeName = TikTokName.ToChildTypeName(parentTypeName, parameter.Name);
            WriteRecord(builder, childTypeName, parameter.Children);
            builder.AppendLine();
            WriteNestedTypes(builder, childTypeName, parameter.Children);
        }
    }
}
