// <auto-generated />
#nullable enable
namespace TikTokPartnerSdk.Generated.Seller;

public sealed record SellerGetAuthorizedShopsRequest();

public sealed record SellerGetAuthorizedShopsResponse(
    int Code,
    string? Message,
    string? RequestId);
