// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;
namespace TikTokPartnerSdk.Generated.SupplyChain;

public sealed record SupplyChainConfirmPackageShipmentRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("warehouse_provider_id")] string WarehouseProviderId,
    [property: JsonPropertyName("packages")] IReadOnlyList<SupplyChainConfirmPackageShipmentRequestPackages> Packages);

public sealed record SupplyChainConfirmPackageShipmentRequestPackages(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("wms_order_id")] string WmsOrderId,
    [property: JsonPropertyName("provider_warehouse_code")] string ProviderWarehouseCode,
    [property: JsonPropertyName("shipping_origin_city")] string ShippingOriginCity,
    [property: JsonPropertyName("time_zone")] string TimeZone,
    [property: JsonPropertyName("ship_time_millis")] long ShipTimeMillis,
    [property: JsonPropertyName("create_time_millis")] long CreateTimeMillis,
    [property: JsonPropertyName("handover_time_millis")] long HandoverTimeMillis,
    [property: JsonPropertyName("shipping_provider_id")] string ShippingProviderId,
    [property: JsonPropertyName("shipping_provider_name")] string ShippingProviderName,
    [property: JsonPropertyName("tracking_number")] string TrackingNumber,
    [property: JsonPropertyName("dimension")] SupplyChainConfirmPackageShipmentRequestPackagesDimension Dimension,
    [property: JsonPropertyName("weight")] SupplyChainConfirmPackageShipmentRequestPackagesWeight Weight,
    [property: JsonPropertyName("skus")] IReadOnlyList<SupplyChainConfirmPackageShipmentRequestPackagesSkus> Skus,
    [property: JsonPropertyName("provider_warehouse_name")] string ProviderWarehouseName,
    [property: JsonPropertyName("tcw_warehouse_type")] string TcwWarehouseType);

public sealed record SupplyChainConfirmPackageShipmentRequestPackagesDimension(
    [property: JsonPropertyName("length")] long Length,
    [property: JsonPropertyName("width")] long Width,
    [property: JsonPropertyName("height")] long Height,
    [property: JsonPropertyName("unit")] string Unit);

public sealed record SupplyChainConfirmPackageShipmentRequestPackagesWeight(
    [property: JsonPropertyName("value")] long Value,
    [property: JsonPropertyName("unit")] string Unit);

public sealed record SupplyChainConfirmPackageShipmentRequestPackagesSkus(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("quantity")] long Quantity);


public sealed record SupplyChainConfirmPackageShipmentResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] SupplyChainConfirmPackageShipmentResponseData Data);

public sealed record SupplyChainConfirmPackageShipmentResponseData(
    [property: JsonPropertyName("success_packages")] IReadOnlyList<string> SuccessPackages,
    [property: JsonPropertyName("errors")] IReadOnlyList<SupplyChainConfirmPackageShipmentResponseDataErrors> Errors);

public sealed record SupplyChainConfirmPackageShipmentResponseDataErrors(
    [property: JsonPropertyName("code")] string Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("detail")] SupplyChainConfirmPackageShipmentResponseDataErrorsDetail Detail);

public sealed record SupplyChainConfirmPackageShipmentResponseDataErrorsDetail(
    [property: JsonPropertyName("package_id")] string PackageId);
