// <auto-generated />
#nullable enable
namespace TikTokPartnerSdk.Generated.Event;

public sealed record EventGetSubscriptionsRequest();

public sealed record EventGetSubscriptionsResponse(
    int Code,
    string? Message,
    string? RequestId);
