// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;
namespace TikTokPartnerSdk.Generated.Tools;

public sealed record ToolsUploadFileInitRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("category_asset_cipher")] string CategoryAssetCipher,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("file_name")] string FileName,
    [property: JsonPropertyName("file_type")] string FileType,
    [property: JsonPropertyName("file_size")] long FileSize,
    [property: JsonPropertyName("total_chunk_count")] long TotalChunkCount,
    [property: JsonPropertyName("target_path")] string TargetPath);


public sealed record ToolsUploadFileInitResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] ToolsUploadFileInitResponseData Data);

public sealed record ToolsUploadFileInitResponseData(
    [property: JsonPropertyName("upload_url")] string UploadUrl,
    [property: JsonPropertyName("upload_token")] string UploadToken);
