// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;
namespace TikTokPartnerSdk.Generated.AffiliatePartner;

public sealed record AffiliatePartnerCreateAffiliatePartnerCampaignRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("category_asset_cipher")] string CategoryAssetCipher,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("description")] string Description,
    [property: JsonPropertyName("campaign_start_time")] long CampaignStartTime,
    [property: JsonPropertyName("campaign_end_time")] long CampaignEndTime,
    [property: JsonPropertyName("registration_start_time")] long RegistrationStartTime,
    [property: JsonPropertyName("registration_end_time")] long RegistrationEndTime,
    [property: JsonPropertyName("commission_rate")] long CommissionRate,
    [property: JsonPropertyName("contact_info")] AffiliatePartnerCreateAffiliatePartnerCampaignRequestContactInfo ContactInfo,
    [property: JsonPropertyName("target_shop_codes")] IReadOnlyList<string> TargetShopCodes,
    [property: JsonPropertyName("target_seller_types")] IReadOnlyList<string> TargetSellerTypes);

public sealed record AffiliatePartnerCreateAffiliatePartnerCampaignRequestContactInfo(
    [property: JsonPropertyName("whatsapp")] string Whatsapp,
    [property: JsonPropertyName("email")] string Email,
    [property: JsonPropertyName("phone")] string Phone,
    [property: JsonPropertyName("zalo")] string Zalo,
    [property: JsonPropertyName("viber")] string Viber,
    [property: JsonPropertyName("line")] string Line);


public sealed record AffiliatePartnerCreateAffiliatePartnerCampaignResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliatePartnerCreateAffiliatePartnerCampaignResponseData Data);

public sealed record AffiliatePartnerCreateAffiliatePartnerCampaignResponseData(
    [property: JsonPropertyName("campaign_id")] string CampaignId);


public sealed record AffiliatePartnerEditAffiliatePartnerCampaignRequest(
    [property: JsonPropertyName("campaign_id")] string CampaignId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("category_asset_cipher")] string CategoryAssetCipher,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("description")] string Description,
    [property: JsonPropertyName("campaign_start_time")] long CampaignStartTime,
    [property: JsonPropertyName("campaign_end_time")] long CampaignEndTime,
    [property: JsonPropertyName("registration_start_time")] long RegistrationStartTime,
    [property: JsonPropertyName("registration_end_time")] long RegistrationEndTime,
    [property: JsonPropertyName("commission_rate")] long CommissionRate,
    [property: JsonPropertyName("contact_info")] AffiliatePartnerEditAffiliatePartnerCampaignRequestContactInfo ContactInfo,
    [property: JsonPropertyName("target_shop_codes")] IReadOnlyList<string> TargetShopCodes,
    [property: JsonPropertyName("target_seller_types")] IReadOnlyList<string> TargetSellerTypes);

public sealed record AffiliatePartnerEditAffiliatePartnerCampaignRequestContactInfo(
    [property: JsonPropertyName("whatsapp")] string Whatsapp,
    [property: JsonPropertyName("email")] string Email,
    [property: JsonPropertyName("phone")] string Phone,
    [property: JsonPropertyName("zalo")] string Zalo,
    [property: JsonPropertyName("viber")] string Viber,
    [property: JsonPropertyName("line")] string Line);


public sealed record AffiliatePartnerEditAffiliatePartnerCampaignResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] object Data);


public sealed record AffiliatePartnerGenerateAffiliatePartnerCampaignProductLinkRequest(
    [property: JsonPropertyName("campaign_id")] string CampaignId,
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("category_asset_cipher")] string CategoryAssetCipher,
    [property: JsonPropertyName("creator_commission_rate")] long CreatorCommissionRate);


public sealed record AffiliatePartnerGenerateAffiliatePartnerCampaignProductLinkResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliatePartnerGenerateAffiliatePartnerCampaignProductLinkResponseData Data);

public sealed record AffiliatePartnerGenerateAffiliatePartnerCampaignProductLinkResponseData(
    [property: JsonPropertyName("product_promotion_link")] string ProductPromotionLink);


public sealed record AffiliatePartnerGetAffiliatePartnerCampaignDetailRequest(
    [property: JsonPropertyName("campaign_id")] string CampaignId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("category_asset_cipher")] string CategoryAssetCipher);


public sealed record AffiliatePartnerGetAffiliatePartnerCampaignDetailResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliatePartnerGetAffiliatePartnerCampaignDetailResponseData Data);

public sealed record AffiliatePartnerGetAffiliatePartnerCampaignDetailResponseData(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("description")] string Description,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("region")] string Region,
    [property: JsonPropertyName("registration_start_time")] long RegistrationStartTime,
    [property: JsonPropertyName("registration_end_time")] long RegistrationEndTime,
    [property: JsonPropertyName("campaign_start_time")] long CampaignStartTime,
    [property: JsonPropertyName("campaign_end_time")] long CampaignEndTime,
    [property: JsonPropertyName("commission_rate")] long CommissionRate,
    [property: JsonPropertyName("contact_info")] AffiliatePartnerGetAffiliatePartnerCampaignDetailResponseDataContactInfo ContactInfo,
    [property: JsonPropertyName("target_shops")] IReadOnlyList<AffiliatePartnerGetAffiliatePartnerCampaignDetailResponseDataTargetShops> TargetShops,
    [property: JsonPropertyName("target_seller_types")] IReadOnlyList<string> TargetSellerTypes);

public sealed record AffiliatePartnerGetAffiliatePartnerCampaignDetailResponseDataContactInfo(
    [property: JsonPropertyName("whatsapp")] string Whatsapp,
    [property: JsonPropertyName("email")] string Email,
    [property: JsonPropertyName("phone")] string Phone,
    [property: JsonPropertyName("zalo")] string Zalo,
    [property: JsonPropertyName("viber")] string Viber,
    [property: JsonPropertyName("line")] string Line);

public sealed record AffiliatePartnerGetAffiliatePartnerCampaignDetailResponseDataTargetShops(
    [property: JsonPropertyName("code")] string Code,
    [property: JsonPropertyName("name")] string Name);


public sealed record AffiliatePartnerGetAffiliatePartnerCampaignListRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("category_asset_cipher")] string CategoryAssetCipher,
    [property: JsonPropertyName("page_size")] long PageSize,
    [property: JsonPropertyName("page_token")] string PageToken,
    [property: JsonPropertyName("query_type_filter")] string QueryTypeFilter,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("type")] string Type);


public sealed record AffiliatePartnerGetAffiliatePartnerCampaignListResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliatePartnerGetAffiliatePartnerCampaignListResponseData Data);

public sealed record AffiliatePartnerGetAffiliatePartnerCampaignListResponseData(
    [property: JsonPropertyName("campaigns")] IReadOnlyList<AffiliatePartnerGetAffiliatePartnerCampaignListResponseDataCampaigns> Campaigns,
    [property: JsonPropertyName("next_page_token")] string NextPageToken,
    [property: JsonPropertyName("total_count")] long TotalCount);

public sealed record AffiliatePartnerGetAffiliatePartnerCampaignListResponseDataCampaigns(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("registration_start_time")] long RegistrationStartTime,
    [property: JsonPropertyName("registration_end_time")] long RegistrationEndTime,
    [property: JsonPropertyName("campaign_start_time")] long CampaignStartTime,
    [property: JsonPropertyName("campaign_end_time")] long CampaignEndTime);


public sealed record AffiliatePartnerGetAffiliatePartnerCampaignProductListRequest(
    [property: JsonPropertyName("campaign_id")] string CampaignId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("category_asset_cipher")] string CategoryAssetCipher,
    [property: JsonPropertyName("category_id")] string CategoryId,
    [property: JsonPropertyName("page_size")] long PageSize,
    [property: JsonPropertyName("page_token")] string PageToken,
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("product_name")] string ProductName,
    [property: JsonPropertyName("review_status")] string ReviewStatus,
    [property: JsonPropertyName("shop_name")] string ShopName);


public sealed record AffiliatePartnerGetAffiliatePartnerCampaignProductListResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliatePartnerGetAffiliatePartnerCampaignProductListResponseData Data);

public sealed record AffiliatePartnerGetAffiliatePartnerCampaignProductListResponseData(
    [property: JsonPropertyName("products")] IReadOnlyList<AffiliatePartnerGetAffiliatePartnerCampaignProductListResponseDataProducts> Products,
    [property: JsonPropertyName("next_page_token")] string NextPageToken,
    [property: JsonPropertyName("total_count")] long TotalCount);

public sealed record AffiliatePartnerGetAffiliatePartnerCampaignProductListResponseDataProducts(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("review_status")] string ReviewStatus,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("main_image_url")] string MainImageUrl,
    [property: JsonPropertyName("lowest_price")] AffiliatePartnerGetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice LowestPrice,
    [property: JsonPropertyName("highest_price")] AffiliatePartnerGetAffiliatePartnerCampaignProductListResponseDataProductsHighestPrice HighestPrice,
    [property: JsonPropertyName("inventory")] long Inventory,
    [property: JsonPropertyName("shop_name")] string ShopName,
    [property: JsonPropertyName("total_commission_rate")] long TotalCommissionRate,
    [property: JsonPropertyName("creator_commission_rate")] long CreatorCommissionRate,
    [property: JsonPropertyName("partner_commission_rate")] long PartnerCommissionRate,
    [property: JsonPropertyName("open_collaboration_commission_rate")] long OpenCollaborationCommissionRate,
    [property: JsonPropertyName("is_available")] bool IsAvailable,
    [property: JsonPropertyName("product_sales")] long ProductSales,
    [property: JsonPropertyName("category")] AffiliatePartnerGetAffiliatePartnerCampaignProductListResponseDataProductsCategory Category,
    [property: JsonPropertyName("sample_quota")] long SampleQuota,
    [property: JsonPropertyName("sku_information_list")] IReadOnlyList<AffiliatePartnerGetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationList> SkuInformationList,
    [property: JsonPropertyName("product_description")] string ProductDescription);

public sealed record AffiliatePartnerGetAffiliatePartnerCampaignProductListResponseDataProductsLowestPrice(
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("amount")] string Amount);

public sealed record AffiliatePartnerGetAffiliatePartnerCampaignProductListResponseDataProductsHighestPrice(
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("amount")] string Amount);

public sealed record AffiliatePartnerGetAffiliatePartnerCampaignProductListResponseDataProductsCategory(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("name")] string Name);

public sealed record AffiliatePartnerGetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationList(
    [property: JsonPropertyName("sku_name")] string SkuName,
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("inventory")] AffiliatePartnerGetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListInventory Inventory,
    [property: JsonPropertyName("base_price")] AffiliatePartnerGetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListBasePrice BasePrice,
    [property: JsonPropertyName("region_prices")] IReadOnlyList<AffiliatePartnerGetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListRegionPrices> RegionPrices,
    [property: JsonPropertyName("properties")] IReadOnlyList<AffiliatePartnerGetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListProperties> Properties);

public sealed record AffiliatePartnerGetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListInventory(
    [property: JsonPropertyName("available_quantity")] string AvailableQuantity);

public sealed record AffiliatePartnerGetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListBasePrice(
    [property: JsonPropertyName("region_code")] string RegionCode,
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("list_price")] string ListPrice,
    [property: JsonPropertyName("sale_price")] string SalePrice,
    [property: JsonPropertyName("localized_dutiable_price")] string LocalizedDutiablePrice);

public sealed record AffiliatePartnerGetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListRegionPrices(
    [property: JsonPropertyName("region_code")] string RegionCode,
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("list_price")] string ListPrice,
    [property: JsonPropertyName("sale_price")] string SalePrice,
    [property: JsonPropertyName("localized_dutiable_price")] string LocalizedDutiablePrice);

public sealed record AffiliatePartnerGetAffiliatePartnerCampaignProductListResponseDataProductsSkuInformationListProperties(
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("value_name")] string ValueName);


public sealed record AffiliatePartnerPublishAffiliatePartnerCampaignRequest(
    [property: JsonPropertyName("campaign_id")] string CampaignId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("category_asset_cipher")] string CategoryAssetCipher);


public sealed record AffiliatePartnerPublishAffiliatePartnerCampaignResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] object Data);


public sealed record AffiliatePartnerReviewAffiliatePartnerCampaignProductRequest(
    [property: JsonPropertyName("campaign_id")] string CampaignId,
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("category_asset_cipher")] string CategoryAssetCipher,
    [property: JsonPropertyName("review_result")] string ReviewResult,
    [property: JsonPropertyName("reject_reasons")] IReadOnlyList<string> RejectReasons);


public sealed record AffiliatePartnerReviewAffiliatePartnerCampaignProductResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] object Data);


public sealed record AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusListRequest(
    [property: JsonPropertyName("campaign_id")] string CampaignId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("page_size")] long PageSize,
    [property: JsonPropertyName("page_token")] string PageToken);


public sealed record AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusListResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusListResponseData Data);

public sealed record AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusListResponseData(
    [property: JsonPropertyName("total_count")] long TotalCount,
    [property: JsonPropertyName("campaign_product_statistics")] IReadOnlyList<AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatistics> CampaignProductStatistics,
    [property: JsonPropertyName("next_page_token")] string NextPageToken);

public sealed record AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatistics(
    [property: JsonPropertyName("data_update_time")] string DataUpdateTime,
    [property: JsonPropertyName("creator_sales_num")] long CreatorSalesNum,
    [property: JsonPropertyName("collaborated_creators_num")] long CollaboratedCreatorsNum,
    [property: JsonPropertyName("promoted_creator_num")] long PromotedCreatorNum,
    [property: JsonPropertyName("sample_requested_creator_num")] long SampleRequestedCreatorNum,
    [property: JsonPropertyName("campaign_product_detail")] AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetail CampaignProductDetail);

public sealed record AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetail(
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("product_status")] string ProductStatus,
    [property: JsonPropertyName("product_name")] string ProductName,
    [property: JsonPropertyName("product_stock_count")] string ProductStockCount,
    [property: JsonPropertyName("total_commission_percent")] string TotalCommissionPercent,
    [property: JsonPropertyName("creator_commission_percent")] string CreatorCommissionPercent,
    [property: JsonPropertyName("partner_commission_percent")] string PartnerCommissionPercent,
    [property: JsonPropertyName("plan_commission_percent")] string PlanCommissionPercent,
    [property: JsonPropertyName("product_price")] AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetailProductPrice ProductPrice,
    [property: JsonPropertyName("product_thumbnail")] AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetailProductThumbnail ProductThumbnail,
    [property: JsonPropertyName("indicator_data")] AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetailIndicatorData IndicatorData);

public sealed record AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetailProductPrice(
    [property: JsonPropertyName("min_price")] string MinPrice,
    [property: JsonPropertyName("max_price")] string MaxPrice,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetailProductThumbnail(
    [property: JsonPropertyName("uri")] string Uri,
    [property: JsonPropertyName("url_list")] IReadOnlyList<string> UrlList);

public sealed record AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusListResponseDataCampaignProductStatisticsCampaignProductDetailIndicatorData(
    [property: JsonPropertyName("paid_order_num")] string PaidOrderNum,
    [property: JsonPropertyName("actual_order_num")] string ActualOrderNum,
    [property: JsonPropertyName("estimated_amount")] string EstimatedAmount,
    [property: JsonPropertyName("actual_amount")] string ActualAmount,
    [property: JsonPropertyName("estimated_partner_commission")] string EstimatedPartnerCommission,
    [property: JsonPropertyName("actual_partner_commission")] string ActualPartnerCommission,
    [property: JsonPropertyName("creator_sales_num")] string CreatorSalesNum,
    [property: JsonPropertyName("collaborated_creators_num")] string CollaboratedCreatorsNum,
    [property: JsonPropertyName("promoted_creator_num")] string PromotedCreatorNum,
    [property: JsonPropertyName("sample_requested_creator_num")] string SampleRequestedCreatorNum);


public sealed record AffiliatePartnerPartnerGenerateMultiAffiliateCampaignProductLinkRequest(
    [property: JsonPropertyName("campaign_id")] string CampaignId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("category_asset_cipher")] string CategoryAssetCipher,
    [property: JsonPropertyName("product_ids")] IReadOnlyList<string> ProductIds);


public sealed record AffiliatePartnerPartnerGenerateMultiAffiliateCampaignProductLinkResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliatePartnerPartnerGenerateMultiAffiliateCampaignProductLinkResponseData Data);

public sealed record AffiliatePartnerPartnerGenerateMultiAffiliateCampaignProductLinkResponseData(
    [property: JsonPropertyName("product_promotion_links")] IReadOnlyList<AffiliatePartnerPartnerGenerateMultiAffiliateCampaignProductLinkResponseDataProductPromotionLinks> ProductPromotionLinks,
    [property: JsonPropertyName("failed_product_ids")] IReadOnlyList<string> FailedProductIds);

public sealed record AffiliatePartnerPartnerGenerateMultiAffiliateCampaignProductLinkResponseDataProductPromotionLinks(
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("link")] string Link);


public sealed record AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusInfoRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("category_asset_cipher")] string CategoryAssetCipher,
    [property: JsonPropertyName("page_size")] long PageSize,
    [property: JsonPropertyName("page_token")] string PageToken);


public sealed record AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusInfoResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData Data);

public sealed record AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusInfoResponseData(
    [property: JsonPropertyName("total_creator_count")] long TotalCreatorCount,
    [property: JsonPropertyName("promotion_creators")] IReadOnlyList<AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreators> PromotionCreators,
    [property: JsonPropertyName("next_page_token")] string NextPageToken);

public sealed record AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreators(
    [property: JsonPropertyName("paid_amount")] AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsPaidAmount PaidAmount,
    [property: JsonPropertyName("room_count")] long RoomCount,
    [property: JsonPropertyName("video_count")] long VideoCount,
    [property: JsonPropertyName("free_sample_status")] string FreeSampleStatus,
    [property: JsonPropertyName("commission")] string Commission,
    [property: JsonPropertyName("effective_end_time")] string EffectiveEndTime,
    [property: JsonPropertyName("effective_start_time")] string EffectiveStartTime,
    [property: JsonPropertyName("creator")] AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator Creator,
    [property: JsonPropertyName("affiliate_product_id")] string AffiliateProductId);

public sealed record AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsPaidAmount(
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("amount")] string Amount);

public sealed record AffiliatePartnerGetAffiliateCampaignCreatorFulfillmentStatusInfoResponseDataPromotionCreatorsCreator(
    [property: JsonPropertyName("nick_name")] string NickName,
    [property: JsonPropertyName("avatar_url")] string AvatarUrl,
    [property: JsonPropertyName("follower_num")] long FollowerNum,
    [property: JsonPropertyName("user_name")] string UserName,
    [property: JsonPropertyName("creator_open_id")] string CreatorOpenId);


public sealed record AffiliatePartnerGetAffiliateCampaignCreatorProductContentStatisticsRequest(
    [property: JsonPropertyName("campaign_id")] string CampaignId,
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("creator_temp_id")] string CreatorTempId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("affiliate_product_id")] string AffiliateProductId,
    [property: JsonPropertyName("category_asset_cipher")] string CategoryAssetCipher,
    [property: JsonPropertyName("content_type")] string ContentType);


public sealed record AffiliatePartnerGetAffiliateCampaignCreatorProductContentStatisticsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliatePartnerGetAffiliateCampaignCreatorProductContentStatisticsResponseData Data);

public sealed record AffiliatePartnerGetAffiliateCampaignCreatorProductContentStatisticsResponseData(
    [property: JsonPropertyName("creator_content_statistics")] IReadOnlyList<AffiliatePartnerGetAffiliateCampaignCreatorProductContentStatisticsResponseDataCreatorContentStatistics> CreatorContentStatistics);

public sealed record AffiliatePartnerGetAffiliateCampaignCreatorProductContentStatisticsResponseDataCreatorContentStatistics(
    [property: JsonPropertyName("content_type")] string ContentType,
    [property: JsonPropertyName("cover_img_url")] string CoverImgUrl,
    [property: JsonPropertyName("source_url")] string SourceUrl,
    [property: JsonPropertyName("view_count")] string ViewCount,
    [property: JsonPropertyName("like_count")] string LikeCount,
    [property: JsonPropertyName("comment_num")] string CommentNum,
    [property: JsonPropertyName("paid_order_num")] string PaidOrderNum,
    [property: JsonPropertyName("paid_amount")] string PaidAmount,
    [property: JsonPropertyName("linked_tiktok_video")] string LinkedTiktokVideo,
    [property: JsonPropertyName("published_date")] string PublishedDate,
    [property: JsonPropertyName("content_end_date")] string ContentEndDate);


public sealed record AffiliatePartnerGetAffiliateCampaignCreatorProductSampleStatusRequest(
    [property: JsonPropertyName("campaign_id")] string CampaignId,
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("creator_temp_id")] string CreatorTempId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("category_asset_cipher")] string CategoryAssetCipher);


public sealed record AffiliatePartnerGetAffiliateCampaignCreatorProductSampleStatusResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliatePartnerGetAffiliateCampaignCreatorProductSampleStatusResponseData Data);

public sealed record AffiliatePartnerGetAffiliateCampaignCreatorProductSampleStatusResponseData(
    [property: JsonPropertyName("sample_status")] AffiliatePartnerGetAffiliateCampaignCreatorProductSampleStatusResponseDataSampleStatus SampleStatus);

public sealed record AffiliatePartnerGetAffiliateCampaignCreatorProductSampleStatusResponseDataSampleStatus(
    [property: JsonPropertyName("shipping_provider_name")] string ShippingProviderName,
    [property: JsonPropertyName("delivery_option")] string DeliveryOption,
    [property: JsonPropertyName("estimated_earliest_delivery_date")] string EstimatedEarliestDeliveryDate,
    [property: JsonPropertyName("estimated_latest_delivery_date")] string EstimatedLatestDeliveryDate,
    [property: JsonPropertyName("quantity")] long Quantity,
    [property: JsonPropertyName("tracking_results")] IReadOnlyList<AffiliatePartnerGetAffiliateCampaignCreatorProductSampleStatusResponseDataSampleStatusTrackingResults> TrackingResults);

public sealed record AffiliatePartnerGetAffiliateCampaignCreatorProductSampleStatusResponseDataSampleStatusTrackingResults(
    [property: JsonPropertyName("tracking_event_update_date")] string TrackingEventUpdateDate,
    [property: JsonPropertyName("tracking_event_description")] string TrackingEventDescription,
    [property: JsonPropertyName("tracking_event_description_extended")] string TrackingEventDescriptionExtended);


public sealed record AffiliatePartnerSearchCapAffiliateOrdersRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("category_asset_cipher")] string CategoryAssetCipher,
    [property: JsonPropertyName("page_size")] long PageSize,
    [property: JsonPropertyName("page_token")] string PageToken,
    [property: JsonPropertyName("order_id")] string OrderId,
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("settle_status")] long SettleStatus,
    [property: JsonPropertyName("create_time_ge")] long CreateTimeGe,
    [property: JsonPropertyName("create_time_lt")] long CreateTimeLt);


public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliatePartnerSearchCapAffiliateOrdersResponseData Data);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseData(
    [property: JsonPropertyName("sku_orders")] IReadOnlyList<AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrders> SkuOrders,
    [property: JsonPropertyName("next_page_token")] string NextPageToken,
    [property: JsonPropertyName("total_count")] long TotalCount);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrders(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("tags")] string Tags,
    [property: JsonPropertyName("create_time")] long CreateTime,
    [property: JsonPropertyName("delivery_time")] long DeliveryTime,
    [property: JsonPropertyName("settle_status")] string SettleStatus,
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("open_collaboration_id")] string OpenCollaborationId,
    [property: JsonPropertyName("target_collaboration_id")] string TargetCollaborationId,
    [property: JsonPropertyName("creator_username")] string CreatorUsername,
    [property: JsonPropertyName("product_name")] string ProductName,
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("price")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersPrice Price,
    [property: JsonPropertyName("quantity")] long Quantity,
    [property: JsonPropertyName("shop_name")] string ShopName,
    [property: JsonPropertyName("content_type")] string ContentType,
    [property: JsonPropertyName("content_id")] string ContentId,
    [property: JsonPropertyName("attribution_type")] string AttributionType,
    [property: JsonPropertyName("commission_model")] string CommissionModel,
    [property: JsonPropertyName("commission_tier_setting")] string CommissionTierSetting,
    [property: JsonPropertyName("standard_commission_rate")] long StandardCommissionRate,
    [property: JsonPropertyName("commission_bonus_rate")] long CommissionBonusRate,
    [property: JsonPropertyName("shop_ads_commission_rate")] long ShopAdsCommissionRate,
    [property: JsonPropertyName("tap_bonus_commission_rate")] long TapBonusCommissionRate,
    [property: JsonPropertyName("revenue_sharing_portion_rate")] long RevenueSharingPortionRate,
    [property: JsonPropertyName("estimated_commission_base")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedCommissionBase EstimatedCommissionBase,
    [property: JsonPropertyName("estimated_standard_commission")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedStandardCommission EstimatedStandardCommission,
    [property: JsonPropertyName("estimated_bonus_commission")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedBonusCommission EstimatedBonusCommission,
    [property: JsonPropertyName("estimated_shop_ads_commission")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedShopAdsCommission EstimatedShopAdsCommission,
    [property: JsonPropertyName("estimated_tap_bonus_commission")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedTapBonusCommission EstimatedTapBonusCommission,
    [property: JsonPropertyName("estimated_creator_tax_isr")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorTaxIsr EstimatedCreatorTaxIsr,
    [property: JsonPropertyName("estimated_creator_tax_iva")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorTaxIva EstimatedCreatorTaxIva,
    [property: JsonPropertyName("estimated_creator_tax_pit")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorTaxPit EstimatedCreatorTaxPit,
    [property: JsonPropertyName("estimated_creator_total_earnings_after_tax")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorTotalEarningsAfterTax EstimatedCreatorTotalEarningsAfterTax,
    [property: JsonPropertyName("estimated_total_agency_earnings")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedTotalAgencyEarnings EstimatedTotalAgencyEarnings,
    [property: JsonPropertyName("estimated_agency_isr")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedAgencyIsr EstimatedAgencyIsr,
    [property: JsonPropertyName("estimated_agency_iva")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedAgencyIva EstimatedAgencyIva,
    [property: JsonPropertyName("actual_commission_base")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualCommissionBase ActualCommissionBase,
    [property: JsonPropertyName("actual_standard_commission")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualStandardCommission ActualStandardCommission,
    [property: JsonPropertyName("actual_bonus_commission")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualBonusCommission ActualBonusCommission,
    [property: JsonPropertyName("actual_shop_ads_commission")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualShopAdsCommission ActualShopAdsCommission,
    [property: JsonPropertyName("actual_tap_bonus_commission")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualTapBonusCommission ActualTapBonusCommission,
    [property: JsonPropertyName("actual_creator_tax_isr")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualCreatorTaxIsr ActualCreatorTaxIsr,
    [property: JsonPropertyName("actual_creator_tax_iva")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualCreatorTaxIva ActualCreatorTaxIva,
    [property: JsonPropertyName("actual_creator_tax_pit")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualCreatorTaxPit ActualCreatorTaxPit,
    [property: JsonPropertyName("actual_creator_total_earnings_after_tax")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualCreatorTotalEarningsAfterTax ActualCreatorTotalEarningsAfterTax,
    [property: JsonPropertyName("actual_total_agency_commission")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualTotalAgencyCommission ActualTotalAgencyCommission,
    [property: JsonPropertyName("actual_agency_isr")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualAgencyIsr ActualAgencyIsr,
    [property: JsonPropertyName("actual_agency_iva")] AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualAgencyIva ActualAgencyIva,
    [property: JsonPropertyName("fully_return")] string FullyReturn,
    [property: JsonPropertyName("settlement_time")] long SettlementTime,
    [property: JsonPropertyName("last_update_time")] long LastUpdateTime);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersPrice(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedCommissionBase(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedStandardCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedBonusCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedShopAdsCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedTapBonusCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorTaxIsr(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorTaxIva(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorTaxPit(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorTotalEarningsAfterTax(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedTotalAgencyEarnings(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedAgencyIsr(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersEstimatedAgencyIva(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualCommissionBase(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualStandardCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualBonusCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualShopAdsCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualTapBonusCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualCreatorTaxIsr(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualCreatorTaxIva(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualCreatorTaxPit(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualCreatorTotalEarningsAfterTax(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualTotalAgencyCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualAgencyIsr(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchCapAffiliateOrdersResponseDataSkuOrdersActualAgencyIva(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);


public sealed record AffiliatePartnerSearchTapAffiliateOrdersRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("category_asset_cipher")] string CategoryAssetCipher,
    [property: JsonPropertyName("page_size")] long PageSize,
    [property: JsonPropertyName("page_token")] string PageToken,
    [property: JsonPropertyName("create_time_ge")] long CreateTimeGe,
    [property: JsonPropertyName("create_time_lt")] long CreateTimeLt,
    [property: JsonPropertyName("campaign_id")] string CampaignId);


public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliatePartnerSearchTapAffiliateOrdersResponseData Data);

public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponseData(
    [property: JsonPropertyName("sku_orders")] IReadOnlyList<AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrders> SkuOrders,
    [property: JsonPropertyName("next_page_token")] string NextPageToken,
    [property: JsonPropertyName("total_count")] long TotalCount);

public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrders(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("create_time")] long CreateTime,
    [property: JsonPropertyName("delivery_time")] long DeliveryTime,
    [property: JsonPropertyName("settle_status")] string SettleStatus,
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("campaign_id")] string CampaignId,
    [property: JsonPropertyName("creator_username")] string CreatorUsername,
    [property: JsonPropertyName("product_name")] string ProductName,
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("price")] AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersPrice Price,
    [property: JsonPropertyName("quantity")] long Quantity,
    [property: JsonPropertyName("content_type")] string ContentType,
    [property: JsonPropertyName("content_id")] string ContentId,
    [property: JsonPropertyName("creator_standard_commission_rate")] long CreatorStandardCommissionRate,
    [property: JsonPropertyName("partner_standard_commission_rate")] long PartnerStandardCommissionRate,
    [property: JsonPropertyName("creator_shop_ads_commission_rate")] long CreatorShopAdsCommissionRate,
    [property: JsonPropertyName("partner_shop_ads_commission_rate")] long PartnerShopAdsCommissionRate,
    [property: JsonPropertyName("partner_tap_bonus_commission_rate")] long PartnerTapBonusCommissionRate,
    [property: JsonPropertyName("creator_tap_bonus_commission_rate")] long CreatorTapBonusCommissionRate,
    [property: JsonPropertyName("estimated_commission_base")] AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCommissionBase EstimatedCommissionBase,
    [property: JsonPropertyName("estimated_creator_standard_commission")] AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorStandardCommission EstimatedCreatorStandardCommission,
    [property: JsonPropertyName("estimated_partner_standard_commission")] AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerStandardCommission EstimatedPartnerStandardCommission,
    [property: JsonPropertyName("estimated_creator_shop_ads_commission")] AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorShopAdsCommission EstimatedCreatorShopAdsCommission,
    [property: JsonPropertyName("estimated_partner_shop_ads_commission")] AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerShopAdsCommission EstimatedPartnerShopAdsCommission,
    [property: JsonPropertyName("estimated_partner_tap_bonus_commission")] AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerTapBonusCommission EstimatedPartnerTapBonusCommission,
    [property: JsonPropertyName("estimated_creator_tap_bonus_commission")] AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorTapBonusCommission EstimatedCreatorTapBonusCommission,
    [property: JsonPropertyName("estimated_partner_isr")] AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerIsr EstimatedPartnerIsr,
    [property: JsonPropertyName("estimated_partner_iva")] AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerIva EstimatedPartnerIva,
    [property: JsonPropertyName("actual_commission_base")] AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersActualCommissionBase ActualCommissionBase,
    [property: JsonPropertyName("actual_creator_standard_commission")] AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersActualCreatorStandardCommission ActualCreatorStandardCommission,
    [property: JsonPropertyName("actual_partner_standard_commission")] AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerStandardCommission ActualPartnerStandardCommission,
    [property: JsonPropertyName("actual_creator_shop_ads_commission")] AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersActualCreatorShopAdsCommission ActualCreatorShopAdsCommission,
    [property: JsonPropertyName("actual_partner_shop_ads_commission")] AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerShopAdsCommission ActualPartnerShopAdsCommission,
    [property: JsonPropertyName("actual_partner_isr")] AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerIsr ActualPartnerIsr,
    [property: JsonPropertyName("actual_partner_iva")] AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerIva ActualPartnerIva,
    [property: JsonPropertyName("actual_partner_tap_bonus_commission")] AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerTapBonusCommission ActualPartnerTapBonusCommission,
    [property: JsonPropertyName("actual_creator_tap_bonus_commission")] AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersActualCreatorTapBonusCommission ActualCreatorTapBonusCommission,
    [property: JsonPropertyName("fully_return")] string FullyReturn,
    [property: JsonPropertyName("settlement_time")] long SettlementTime,
    [property: JsonPropertyName("last_update_time")] long LastUpdateTime);

public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersPrice(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCommissionBase(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorStandardCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerStandardCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorShopAdsCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerShopAdsCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerTapBonusCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedCreatorTapBonusCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerIsr(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersEstimatedPartnerIva(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersActualCommissionBase(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersActualCreatorStandardCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerStandardCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersActualCreatorShopAdsCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerShopAdsCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerIsr(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerIva(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersActualPartnerTapBonusCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliatePartnerSearchTapAffiliateOrdersResponseDataSkuOrdersActualCreatorTapBonusCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);
