// <auto-generated />
#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace TikTokPartnerSdk.Generated.Webhooks;

public sealed record TikTokOrderStatusChangeWebhookData(
    [property: JsonPropertyName(@"order_id")] string? OrderId,
    [property: JsonPropertyName(@"order_status")] string? OrderStatus,
    [property: JsonPropertyName(@"is_on_hold_order")] bool? IsOnHoldOrder,
    [property: JsonPropertyName(@"update_time")] long? UpdateTime);

public sealed record TikTokRecipientAddressUpdateWebhookData(
    [property: JsonPropertyName(@"order_id")] string? OrderId,
    [property: JsonPropertyName(@"update_time")] long? UpdateTime);

public sealed record TikTokPackageUpdateWebhookData(
    [property: JsonPropertyName(@"sc_type")] string? ScType,
    [property: JsonPropertyName(@"role_type")] string? RoleType,
    [property: JsonPropertyName(@"package_list")] IReadOnlyList<TikTokPackageUpdateWebhookDataPackageList>? PackageList,
    [property: JsonPropertyName(@"update_time")] long? UpdateTime);

public sealed record TikTokPackageUpdateWebhookDataPackageList(
    [property: JsonPropertyName(@"package_id")] string? PackageId,
    [property: JsonPropertyName(@"order_id_list")] IReadOnlyList<string>? OrderIdList);

public sealed record TikTokProductStatusChangeWebhookData(
    [property: JsonPropertyName(@"product_id")] long? ProductId,
    [property: JsonPropertyName(@"status")] string? Status,
    [property: JsonPropertyName(@"suspended_reason")] string? SuspendedReason,
    [property: JsonPropertyName(@"update_time")] long? UpdateTime);

public sealed record TikTokSellerDeauthorizationWebhookData(
    [property: JsonPropertyName(@"message")] string? Message);

public sealed record TikTokUpcomingAuthorizationExpirationWebhookData(
    [property: JsonPropertyName(@"message")] string? Message,
    [property: JsonPropertyName(@"expiration_time")] string? ExpirationTime);

public sealed record TikTokCancellationStatusChangeWebhookData(
    [property: JsonPropertyName(@"order_id")] string? OrderId,
    [property: JsonPropertyName(@"cancellations_role")] string? CancellationsRole,
    [property: JsonPropertyName(@"cancel_status")] string? CancelStatus,
    [property: JsonPropertyName(@"cancel_id")] string? CancelId,
    [property: JsonPropertyName(@"create_time")] long? CreateTime);

public sealed record TikTokReturnStatusChangeWebhookData(
    [property: JsonPropertyName(@"order_id")] string? OrderId,
    [property: JsonPropertyName(@"return_role")] string? ReturnRole,
    [property: JsonPropertyName(@"return_type")] string? ReturnType,
    [property: JsonPropertyName(@"return_status")] string? ReturnStatus,
    [property: JsonPropertyName(@"return_id")] string? ReturnId,
    [property: JsonPropertyName(@"create_time")] string? CreateTime,
    [property: JsonPropertyName(@"update_time")] string? UpdateTime);

public sealed record TikTokNewConversationWebhookData(
    [property: JsonPropertyName(@"conversation_id")] string? ConversationId,
    [property: JsonPropertyName(@"create_time")] long? CreateTime);

public sealed record TikTokNewMessageWebhookData(
    [property: JsonPropertyName(@"content")] string? Content,
    [property: JsonPropertyName(@"conversation_id")] string? ConversationId,
    [property: JsonPropertyName(@"create_time")] long? CreateTime,
    [property: JsonPropertyName(@"is_visible")] bool? IsVisible,
    [property: JsonPropertyName(@"message_id")] string? MessageId,
    [property: JsonPropertyName(@"index")] string? Index,
    [property: JsonPropertyName(@"type")] string? Type,
    [property: JsonPropertyName(@"sender")] TikTokNewMessageWebhookDataSender? Sender);

public sealed record TikTokNewMessageWebhookDataSender(
    [property: JsonPropertyName(@"im_user_id")] string? ImUserId,
    [property: JsonPropertyName(@"role")] string? Role);

public sealed record TikTokProductInformationChangeWebhookData(
    [property: JsonPropertyName(@"product_id")] string? ProductId,
    [property: JsonPropertyName(@"change_source")] string? ChangeSource,
    [property: JsonPropertyName(@"changed_fields")] IReadOnlyList<string>? ChangedFields,
    [property: JsonPropertyName(@"update_time")] long? UpdateTime);

public sealed record TikTokProductCreationWebhookData(
    [property: JsonPropertyName(@"product_id")] long? ProductId,
    [property: JsonPropertyName(@"product_types")] IReadOnlyList<string>? ProductTypes,
    [property: JsonPropertyName(@"update_time")] long? UpdateTime);

public sealed record TikTokShoppableContentPostingWebhookData(
    [property: JsonPropertyName(@"product_id")] string? ProductId,
    [property: JsonPropertyName(@"event")] TikTokShoppableContentPostingWebhookDataEvent? Event);

public sealed record TikTokShoppableContentPostingWebhookDataEvent(
    [property: JsonPropertyName(@"type")] string? Type,
    [property: JsonPropertyName(@"scene")] string? Scene,
    [property: JsonPropertyName(@"content_id")] string? ContentId);

public sealed record TikTokProductCategoryChangeWebhookData(
    [property: JsonPropertyName(@"product_id")] string? ProductId,
    [property: JsonPropertyName(@"previous_category_id")] string? PreviousCategoryId,
    [property: JsonPropertyName(@"current_category_id")] string? CurrentCategoryId,
    [property: JsonPropertyName(@"update_time")] long? UpdateTime);

public sealed record TikTokSizeChartChangeWebhookData(
    [property: JsonPropertyName(@"size_chart_template_id")] string? SizeChartTemplateId,
    [property: JsonPropertyName(@"size_chart_template_name")] string? SizeChartTemplateName,
    [property: JsonPropertyName(@"event_type")] string? EventType,
    [property: JsonPropertyName(@"update_time")] long? UpdateTime);

public sealed record TikTokCreatorDeauthorizationWebhookData(
    [property: JsonPropertyName(@"cancel_time")] long? CancelTime);

public sealed record TikTokInboundFBTOrderStatusChangeWebhookData(
    [property: JsonPropertyName(@"inbound_order_id")] string? InboundOrderId,
    [property: JsonPropertyName(@"order_status")] string? OrderStatus,
    [property: JsonPropertyName(@"update_time")] long? UpdateTime);

public sealed record TikTokFBTMerchantOnboardingWebhookData(
    [property: JsonPropertyName(@"onboarded_regions")] IReadOnlyList<TikTokFBTMerchantOnboardingWebhookDataOnboardedRegions>? OnboardedRegions,
    [property: JsonPropertyName(@"update_time")] long? UpdateTime);

public sealed record TikTokFBTMerchantOnboardingWebhookDataOnboardedRegions(
    [property: JsonPropertyName(@"region_code")] string? RegionCode);

public sealed record TikTokGoodsMatchWebhookData(
    [property: JsonPropertyName(@"match_type")] string? MatchType,
    [property: JsonPropertyName(@"product_type")] string? ProductType,
    [property: JsonPropertyName(@"goods_id")] string? GoodsId,
    [property: JsonPropertyName(@"product_id")] string? ProductId,
    [property: JsonPropertyName(@"sku_id")] string? SkuId,
    [property: JsonPropertyName(@"update_time")] long? UpdateTime);

public sealed record TikTokFBTInventoryUpdateWebhookData(
    [property: JsonPropertyName(@"goods_id")] string? GoodsId,
    [property: JsonPropertyName(@"sku_id")] string? SkuId,
    [property: JsonPropertyName(@"fbt_warehouse_inventory")] IReadOnlyList<TikTokFBTInventoryUpdateWebhookDataFbtWarehouseInventory>? FbtWarehouseInventory,
    [property: JsonPropertyName(@"update_time")] long? UpdateTime);

public sealed record TikTokFBTInventoryUpdateWebhookDataFbtWarehouseInventory(
    [property: JsonPropertyName(@"fbt_warehouse_id")] string? FbtWarehouseId,
    [property: JsonPropertyName(@"on_hand_detail")] TikTokFBTInventoryUpdateWebhookDataFbtWarehouseInventoryOnHandDetail? OnHandDetail);

public sealed record TikTokFBTInventoryUpdateWebhookDataFbtWarehouseInventoryOnHandDetail(
    [property: JsonPropertyName(@"total_quantity")] long? TotalQuantity,
    [property: JsonPropertyName(@"reserved_quantity")] long? ReservedQuantity,
    [property: JsonPropertyName(@"available_quantity")] long? AvailableQuantity);

public sealed record TikTokOpportunityMatchingStatusChangeWebhookData(
    [property: JsonPropertyName(@"external_product_id")] string? ExternalProductId,
    [property: JsonPropertyName(@"opportunity_matching_status")] string? OpportunityMatchingStatus,
    [property: JsonPropertyName(@"opportunity_ids")] IReadOnlyList<string>? OpportunityIds,
    [property: JsonPropertyName(@"opportunity_matching_end_time")] long? OpportunityMatchingEndTime,
    [property: JsonPropertyName(@"update_time")] long? UpdateTime);

public sealed record TikTokInventoryStatusChangeWebhookData(
    [property: JsonPropertyName(@"product_id")] string? ProductId,
    [property: JsonPropertyName(@"sku_id")] string? SkuId,
    [property: JsonPropertyName(@"trigger_reason")] string? TriggerReason,
    [property: JsonPropertyName(@"current_inventory_status")] string? CurrentInventoryStatus,
    [property: JsonPropertyName(@"inventory_distribution")] string? InventoryDistribution,
    [property: JsonPropertyName(@"update_time")] string? UpdateTime);

public sealed record TikTokNewMessageListenerWebhookData(
    [property: JsonPropertyName(@"index")] string? Index,
    [property: JsonPropertyName(@"message_id")] string? MessageId,
    [property: JsonPropertyName(@"conversation_id")] string? ConversationId,
    [property: JsonPropertyName(@"msg_type")] string? MsgType,
    [property: JsonPropertyName(@"content")] string? Content,
    [property: JsonPropertyName(@"create_time")] string? CreateTime,
    [property: JsonPropertyName(@"sender")] TikTokNewMessageListenerWebhookDataSender? Sender);

public sealed record TikTokNewMessageListenerWebhookDataSender(
    [property: JsonPropertyName(@"sender_im_user_id")] string? SenderImUserId);

public sealed record TikTokTokopediaMirrorStatusChangeWebhookData(
    [property: JsonPropertyName(@"tts_shop_id")] string? TtsShopId,
    [property: JsonPropertyName(@"mirror_status")] string? MirrorStatus,
    [property: JsonPropertyName(@"update_time")] long? UpdateTime);

public sealed record TikTokInvoiceStatusChangeWebhookData(
    [property: JsonPropertyName(@"package_id")] string? PackageId,
    [property: JsonPropertyName(@"order_ids")] IReadOnlyList<string>? OrderIds,
    [property: JsonPropertyName(@"invoice_status")] string? InvoiceStatus,
    [property: JsonPropertyName(@"invalid_reason")] string? InvalidReason);

public sealed record TikTokProductAuditStatusChangeWebhookData(
    [property: JsonPropertyName(@"product_id")] long? ProductId,
    [property: JsonPropertyName(@"audit")] TikTokProductAuditStatusChangeWebhookDataAudit? Audit,
    [property: JsonPropertyName(@"integrated_platform_statuses")] TikTokProductAuditStatusChangeWebhookDataIntegratedPlatformStatuses? IntegratedPlatformStatuses,
    [property: JsonPropertyName(@"update_time")] long? UpdateTime);

public sealed record TikTokProductAuditStatusChangeWebhookDataAudit(
    [property: JsonPropertyName(@"status")] string? Status,
    [property: JsonPropertyName(@"pre_approved_reason")] string? PreApprovedReason);

public sealed record TikTokProductAuditStatusChangeWebhookDataIntegratedPlatformStatuses(
    [property: JsonPropertyName(@"platform")] string? Platform,
    [property: JsonPropertyName(@"status")] string? Status);

public sealed record TikTokStrikethroughPriceExpiredWebhookData(
    [property: JsonPropertyName(@"product_id")] string? ProductId,
    [property: JsonPropertyName(@"sku_id")] string? SkuId);

public sealed record TikTokActivityStatusChangeWebhookData(
    [property: JsonPropertyName(@"activity_id")] string? ActivityId,
    [property: JsonPropertyName(@"update_time")] long? UpdateTime,
    [property: JsonPropertyName(@"activity_type")] string? ActivityType,
    [property: JsonPropertyName(@"product_level")] string? ProductLevel,
    [property: JsonPropertyName(@"status")] string? Status);

public sealed record TikTokCombinedListingChangeWebhookData(
    [property: JsonPropertyName(@"combined_listing_id")] string? CombinedListingId,
    [property: JsonPropertyName(@"products")] IReadOnlyList<TikTokCombinedListingChangeWebhookDataProducts>? Products,
    [property: JsonPropertyName(@"status")] string? Status,
    [property: JsonPropertyName(@"change_type")] string? ChangeType,
    [property: JsonPropertyName(@"added_product_ids")] IReadOnlyList<string>? AddedProductIds,
    [property: JsonPropertyName(@"removed_product_ids")] IReadOnlyList<string>? RemovedProductIds);

public sealed record TikTokCombinedListingChangeWebhookDataProducts(
    [property: JsonPropertyName(@"id")] string? Id);

public sealed record TikTokImageTranslationCompletedWebhookData(
    [property: JsonPropertyName(@"translation_task")] TikTokImageTranslationCompletedWebhookDataTranslationTask? TranslationTask);

public sealed record TikTokImageTranslationCompletedWebhookDataTranslationTask(
    [property: JsonPropertyName(@"id")] string? Id,
    [property: JsonPropertyName(@"status")] string? Status,
    [property: JsonPropertyName(@"fail_reason")] string? FailReason,
    [property: JsonPropertyName(@"target_lang")] string? TargetLang,
    [property: JsonPropertyName(@"original_image")] TikTokImageTranslationCompletedWebhookDataTranslationTaskOriginalImage? OriginalImage,
    [property: JsonPropertyName(@"translated_image")] TikTokImageTranslationCompletedWebhookDataTranslationTaskTranslatedImage? TranslatedImage);

public sealed record TikTokImageTranslationCompletedWebhookDataTranslationTaskOriginalImage(
    [property: JsonPropertyName(@"uri")] string? Uri,
    [property: JsonPropertyName(@"url")] string? Url);

public sealed record TikTokImageTranslationCompletedWebhookDataTranslationTaskTranslatedImage(
    [property: JsonPropertyName(@"uri")] string? Uri,
    [property: JsonPropertyName(@"url")] string? Url);

public sealed record TikTokGlobalReplicationStatusChangeWebhookData(
    [property: JsonPropertyName(@"source_product_id")] string? SourceProductId,
    [property: JsonPropertyName(@"replicated_product")] string? ReplicatedProduct);

public sealed record TikTokGlobalListingMethodChangeWebhookData(
    [property: JsonPropertyName(@"global_product_id")] string? GlobalProductId,
    [property: JsonPropertyName(@"local_product_id")] string? LocalProductId,
    [property: JsonPropertyName(@"listing_method")] string? ListingMethod);

public sealed record TikTokVideoPrecheckResultWebhookData(
    [property: JsonPropertyName(@"precheck_task_id")] string? PrecheckTaskId,
    [property: JsonPropertyName(@"result")] string? Result,
    [property: JsonPropertyName(@"issues")] IReadOnlyList<TikTokVideoPrecheckResultWebhookDataIssues>? Issues);

public sealed record TikTokVideoPrecheckResultWebhookDataIssues(
    [property: JsonPropertyName(@"risk")] string? Risk,
    [property: JsonPropertyName(@"suggestion")] string? Suggestion);

public sealed record TikTokSampleApplicationStatusChangeWebhookData(
    [property: JsonPropertyName(@"application_id")] string? ApplicationId,
    [property: JsonPropertyName(@"new_status")] string? NewStatus,
    [property: JsonPropertyName(@"creator")] TikTokSampleApplicationStatusChangeWebhookDataCreator? Creator,
    [property: JsonPropertyName(@"product")] TikTokSampleApplicationStatusChangeWebhookDataProduct? Product);

public sealed record TikTokSampleApplicationStatusChangeWebhookDataCreator(
    [property: JsonPropertyName(@"creator_open_id")] string? CreatorOpenId);

public sealed record TikTokSampleApplicationStatusChangeWebhookDataProduct(
    [property: JsonPropertyName(@"id")] string? Id,
    [property: JsonPropertyName(@"sku_id")] string? SkuId);

public sealed record TikTokGetFBTMCFOrderStatusWebhookData(
    [property: JsonPropertyName(@"mcf_order")] TikTokGetFBTMCFOrderStatusWebhookDataMcfOrder? McfOrder);

public sealed record TikTokGetFBTMCFOrderStatusWebhookDataMcfOrder(
    [property: JsonPropertyName(@"external_order_id")] string? ExternalOrderId,
    [property: JsonPropertyName(@"mcf_order_id")] string? McfOrderId,
    [property: JsonPropertyName(@"consign_orders")] TikTokGetFBTMCFOrderStatusWebhookDataMcfOrderConsignOrders? ConsignOrders,
    [property: JsonPropertyName(@"create_time")] long? CreateTime);

public sealed record TikTokGetFBTMCFOrderStatusWebhookDataMcfOrderConsignOrders(
    [property: JsonPropertyName(@"id")] string? Id,
    [property: JsonPropertyName(@"tracking_number")] string? TrackingNumber,
    [property: JsonPropertyName(@"carrier")] string? Carrier,
    [property: JsonPropertyName(@"status")] string? Status,
    [property: JsonPropertyName(@"goods")] TikTokGetFBTMCFOrderStatusWebhookDataMcfOrderConsignOrdersGoods? Goods);

public sealed record TikTokGetFBTMCFOrderStatusWebhookDataMcfOrderConsignOrdersGoods(
    [property: JsonPropertyName(@"id")] string? Id,
    [property: JsonPropertyName(@"quantity")] long? Quantity);

public sealed record TikTokShoppableVideoPrecheckTasksResultWebhookData(
    [property: JsonPropertyName(@"task_id")] string? TaskId,
    [property: JsonPropertyName(@"violation_check_result")] TikTokShoppableVideoPrecheckTasksResultWebhookDataViolationCheckResult? ViolationCheckResult,
    [property: JsonPropertyName(@"good_quality_check_result")] TikTokShoppableVideoPrecheckTasksResultWebhookDataGoodQualityCheckResult? GoodQualityCheckResult);

public sealed record TikTokShoppableVideoPrecheckTasksResultWebhookDataViolationCheckResult(
    [property: JsonPropertyName(@"status")] string? Status,
    [property: JsonPropertyName(@"issues")] IReadOnlyList<TikTokShoppableVideoPrecheckTasksResultWebhookDataViolationCheckResultIssues>? Issues);

public sealed record TikTokShoppableVideoPrecheckTasksResultWebhookDataViolationCheckResultIssues(
    [property: JsonPropertyName(@"risk")] string? Risk,
    [property: JsonPropertyName(@"suggestions")] string? Suggestions);

public sealed record TikTokShoppableVideoPrecheckTasksResultWebhookDataGoodQualityCheckResult(
    [property: JsonPropertyName(@"status")] string? Status,
    [property: JsonPropertyName(@"issues")] IReadOnlyList<TikTokShoppableVideoPrecheckTasksResultWebhookDataGoodQualityCheckResultIssues>? Issues);

public sealed record TikTokShoppableVideoPrecheckTasksResultWebhookDataGoodQualityCheckResultIssues(
    [property: JsonPropertyName(@"code")] string? Code,
    [property: JsonPropertyName(@"suggestions")] string? Suggestions);

public sealed record TikTokProductPackageRecommendedWebhookData(
    [property: JsonPropertyName(@"abnormality_types")] IReadOnlyList<string>? AbnormalityTypes,
    [property: JsonPropertyName(@"dimension_recommendation")] TikTokProductPackageRecommendedWebhookDataDimensionRecommendation? DimensionRecommendation,
    [property: JsonPropertyName(@"product_id")] string? ProductId,
    [property: JsonPropertyName(@"weight_recommendation")] TikTokProductPackageRecommendedWebhookDataWeightRecommendation? WeightRecommendation);

public sealed record TikTokProductPackageRecommendedWebhookDataDimensionRecommendation(
    [property: JsonPropertyName(@"height")] TikTokProductPackageRecommendedWebhookDataDimensionRecommendationHeight? Height,
    [property: JsonPropertyName(@"length")] TikTokProductPackageRecommendedWebhookDataDimensionRecommendationLength? Length,
    [property: JsonPropertyName(@"unit")] string? Unit,
    [property: JsonPropertyName(@"width")] TikTokProductPackageRecommendedWebhookDataDimensionRecommendationWidth? Width);

public sealed record TikTokProductPackageRecommendedWebhookDataDimensionRecommendationHeight(
    [property: JsonPropertyName(@"max_value")] string? MaxValue,
    [property: JsonPropertyName(@"min_value")] string? MinValue);

public sealed record TikTokProductPackageRecommendedWebhookDataDimensionRecommendationLength(
    [property: JsonPropertyName(@"max_value")] string? MaxValue,
    [property: JsonPropertyName(@"min_value")] string? MinValue);

public sealed record TikTokProductPackageRecommendedWebhookDataDimensionRecommendationWidth(
    [property: JsonPropertyName(@"max_value")] string? MaxValue,
    [property: JsonPropertyName(@"min_value")] string? MinValue);

public sealed record TikTokProductPackageRecommendedWebhookDataWeightRecommendation(
    [property: JsonPropertyName(@"unit")] string? Unit,
    [property: JsonPropertyName(@"weight")] TikTokProductPackageRecommendedWebhookDataWeightRecommendationWeight? Weight);

public sealed record TikTokProductPackageRecommendedWebhookDataWeightRecommendationWeight(
    [property: JsonPropertyName(@"max_value")] string? MaxValue,
    [property: JsonPropertyName(@"min_value")] string? MinValue);

public sealed record TikTokActivityChangeWebhookData(
    [property: JsonPropertyName(@"activity_id")] string? ActivityId,
    [property: JsonPropertyName(@"update_time")] long? UpdateTime,
    [property: JsonPropertyName(@"change_type")] string? ChangeType,
    [property: JsonPropertyName(@"product_update_list")] TikTokActivityChangeWebhookDataProductUpdateList? ProductUpdateList,
    [property: JsonPropertyName(@"product_remove_list")] TikTokActivityChangeWebhookDataProductRemoveList? ProductRemoveList);

public sealed record TikTokActivityChangeWebhookDataProductUpdateList(
    [property: JsonPropertyName(@"product_ids")] IReadOnlyList<string>? ProductIds,
    [property: JsonPropertyName(@"exclude_product_ids")] IReadOnlyList<string>? ExcludeProductIds,
    [property: JsonPropertyName(@"benefit_product_ids")] IReadOnlyList<string>? BenefitProductIds);

public sealed record TikTokActivityChangeWebhookDataProductRemoveList(
    [property: JsonPropertyName(@"product_ids")] IReadOnlyList<string>? ProductIds,
    [property: JsonPropertyName(@"sku_ids")] IReadOnlyList<string>? SkuIds,
    [property: JsonPropertyName(@"benefit_product_ids")] IReadOnlyList<JsonElement>? BenefitProductIds,
    [property: JsonPropertyName(@"exclude_product_ids")] IReadOnlyList<JsonElement>? ExcludeProductIds);

public sealed record TikTokInventoryChangedWebhookData(
    [property: JsonPropertyName(@"event_id")] string? EventId,
    [property: JsonPropertyName(@"occurred_at")] string? OccurredAt,
    [property: JsonPropertyName(@"seller_id")] string? SellerId,
    [property: JsonPropertyName(@"product_id")] string? ProductId,
    [property: JsonPropertyName(@"sku_id")] string? SkuId,
    [property: JsonPropertyName(@"quantity_snapshot_after_change")] TikTokInventoryChangedWebhookDataQuantitySnapshotAfterChange? QuantitySnapshotAfterChange,
    [property: JsonPropertyName(@"change_detail")] IReadOnlyList<TikTokInventoryChangedWebhookDataChangeDetail>? ChangeDetail);

public sealed record TikTokInventoryChangedWebhookDataQuantitySnapshotAfterChange(
    [property: JsonPropertyName(@"total_quantity")] long? TotalQuantity,
    [property: JsonPropertyName(@"total_available_quantity")] long? TotalAvailableQuantity,
    [property: JsonPropertyName(@"total_committed_quantity")] long? TotalCommittedQuantity,
    [property: JsonPropertyName(@"in_shop_quantity")] long? InShopQuantity,
    [property: JsonPropertyName(@"campaign_locked_quantity")] long? CampaignLockedQuantity,
    [property: JsonPropertyName(@"creator_locked_quantity")] long? CreatorLockedQuantity);

public sealed record TikTokInventoryChangedWebhookDataChangeDetail(
    [property: JsonPropertyName(@"idempotency_key")] string? IdempotencyKey,
    [property: JsonPropertyName(@"trigger_source")] string? TriggerSource,
    [property: JsonPropertyName(@"occurred_at")] string? OccurredAt,
    [property: JsonPropertyName(@"total_quantity_delta")] long? TotalQuantityDelta,
    [property: JsonPropertyName(@"available_quantity_delta")] long? AvailableQuantityDelta,
    [property: JsonPropertyName(@"committed_quantity_delta")] long? CommittedQuantityDelta,
    [property: JsonPropertyName(@"in_shop_quantity_delta")] long? InShopQuantityDelta,
    [property: JsonPropertyName(@"campaign_locked_quantity_delta")] long? CampaignLockedQuantityDelta,
    [property: JsonPropertyName(@"creator_locked_quantity_delta")] long? CreatorLockedQuantityDelta);
