// <auto-generated />
#nullable enable

namespace TikTokPartnerSdk.Generated.Webhooks;

public static class TikTokWebhookType
{
    public const long OrderStatusChange = 1;
    public const long RecipientAddressUpdate = 3;
    public const long PackageUpdate = 4;
    public const long ProductStatusChange = 5;
    public const long SellerDeauthorization = 6;
    public const long UpcomingAuthorizationExpiration = 7;
    public const long CancellationStatusChange = 11;
    public const long ReturnStatusChange = 12;
    public const long NewConversation = 13;
    public const long NewMessage = 14;
    public const long ProductInformationChange = 15;
    public const long ProductCreation = 16;
    public const long ShoppableContentPosting = 17;
    public const long ProductCategoryChange = 18;
    public const long SizeChartChange = 19;
    public const long CreatorDeauthorization = 20;
    public const long InboundFBTOrderStatusChange = 21;
    public const long FBTMerchantOnboarding = 22;
    public const long GoodsMatch = 23;
    public const long FBTInventoryUpdate = 24;
    public const long OpportunityMatchingStatusChange = 25;
    public const long InventoryStatusChange = 27;
    public const long NewMessageListener = 33;
    public const long TokopediaMirrorStatusChange = 35;
    public const long InvoiceStatusChange = 36;
    public const long ProductAuditStatusChange = 37;
    public const long StrikethroughPriceExpired = 38;
    public const long ActivityStatusChange = 39;
    public const long CombinedListingChange = 42;
    public const long ImageTranslationCompleted = 46;
    public const long GlobalReplicationStatusChange = 51;
    public const long GlobalListingMethodChange = 52;
    public const long VideoPrecheckResult = 55;
    public const long SampleApplicationStatusChange = 56;
    public const long GetFBTMCFOrderStatus = 58;
    public const long ShoppableVideoPrecheckTasksResult = 59;
    public const long ProductPackageRecommended = 62;
    public const long ActivityChange = 63;
    public const long InventoryChanged = 68;
}
