// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;
namespace TikTokPartnerSdk.Generated.ReturnAndRefund;

public sealed record ReturnAndRefundApproveCancellationRequest(
    [property: JsonPropertyName("cancel_id")] string CancelId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("idempotency_key")] string IdempotencyKey,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record ReturnAndRefundApproveCancellationResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] object Data);


public sealed record ReturnAndRefundApproveReturnRequest(
    [property: JsonPropertyName("return_id")] string ReturnId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("idempotency_key")] string IdempotencyKey,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("decision")] string Decision,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("buyer_keep_item")] bool BuyerKeepItem,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("partial_refund")] ReturnAndRefundApproveReturnRequestPartialRefund PartialRefund);

public sealed record ReturnAndRefundApproveReturnRequestPartialRefund(
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("amount")] string Amount);


public sealed record ReturnAndRefundApproveReturnResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] object Data);


public sealed record ReturnAndRefundGetRejectReasonsRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("locale")] string Locale,
    [property: JsonPropertyName("return_or_cancel_id")] string ReturnOrCancelId,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record ReturnAndRefundGetRejectReasonsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] ReturnAndRefundGetRejectReasonsResponseData Data);

public sealed record ReturnAndRefundGetRejectReasonsResponseData(
    [property: JsonPropertyName("reasons")] IReadOnlyList<ReturnAndRefundGetRejectReasonsResponseDataReasons> Reasons);

public sealed record ReturnAndRefundGetRejectReasonsResponseDataReasons(
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("text")] string Text);


public sealed record ReturnAndRefundGetReturnRecordsRequest(
    [property: JsonPropertyName("return_id")] string ReturnId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("locale")] string Locale,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record ReturnAndRefundGetReturnRecordsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] ReturnAndRefundGetReturnRecordsResponseData Data);

public sealed record ReturnAndRefundGetReturnRecordsResponseData(
    [property: JsonPropertyName("records")] IReadOnlyList<ReturnAndRefundGetReturnRecordsResponseDataRecords> Records);

public sealed record ReturnAndRefundGetReturnRecordsResponseDataRecords(
    [property: JsonPropertyName("event")] string Event,
    [property: JsonPropertyName("role")] string Role,
    [property: JsonPropertyName("description")] string Description,
    [property: JsonPropertyName("reason_text")] string ReasonText,
    [property: JsonPropertyName("note")] string Note,
    [property: JsonPropertyName("images")] IReadOnlyList<ReturnAndRefundGetReturnRecordsResponseDataRecordsImages> Images,
    [property: JsonPropertyName("videos")] IReadOnlyList<ReturnAndRefundGetReturnRecordsResponseDataRecordsVideos> Videos,
    [property: JsonPropertyName("create_time")] long CreateTime);

public sealed record ReturnAndRefundGetReturnRecordsResponseDataRecordsImages(
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("width")] long Width,
    [property: JsonPropertyName("height")] long Height);

public sealed record ReturnAndRefundGetReturnRecordsResponseDataRecordsVideos(
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("cover")] string Cover,
    [property: JsonPropertyName("width")] long Width,
    [property: JsonPropertyName("height")] long Height,
    [property: JsonPropertyName("duration_millis")] long DurationMillis);


public sealed record ReturnAndRefundRejectCancellationRequest(
    [property: JsonPropertyName("cancel_id")] string CancelId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("idempotency_key")] string IdempotencyKey,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("reject_reason")] string RejectReason,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("comment")] string Comment,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("images")] IReadOnlyList<ReturnAndRefundRejectCancellationRequestImages> Images);

public sealed record ReturnAndRefundRejectCancellationRequestImages(
    [property: JsonPropertyName("image_id")] string ImageId,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("mime_type")] string MimeType,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("height")] long Height,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("width")] long Width);


public sealed record ReturnAndRefundRejectCancellationResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] object Data);


public sealed record ReturnAndRefundRejectReturnRequest(
    [property: JsonPropertyName("return_id")] string ReturnId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("idempotency_key")] string IdempotencyKey,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("decision")] string Decision,
    [property: JsonPropertyName("reject_reason")] string RejectReason,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("comment")] string Comment,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("images")] IReadOnlyList<ReturnAndRefundRejectReturnRequestImages> Images);

public sealed record ReturnAndRefundRejectReturnRequestImages(
    [property: JsonPropertyName("image_id")] string ImageId,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("mime_type")] string MimeType,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("height")] long Height,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("width")] long Width);


public sealed record ReturnAndRefundRejectReturnResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] object Data);


public sealed record ReturnAndRefundGetDecisionEligibilityRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("check_decisions")] IReadOnlyList<string> CheckDecisions,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("locale")] string Locale,
    [property: JsonPropertyName("return_or_cancel_id")] string ReturnOrCancelId,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record ReturnAndRefundGetDecisionEligibilityResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] ReturnAndRefundGetDecisionEligibilityResponseData Data);

public sealed record ReturnAndRefundGetDecisionEligibilityResponseData(
    [property: JsonPropertyName("decisions")] IReadOnlyList<ReturnAndRefundGetDecisionEligibilityResponseDataDecisions> Decisions);

public sealed record ReturnAndRefundGetDecisionEligibilityResponseDataDecisions(
    [property: JsonPropertyName("decision")] string Decision,
    [property: JsonPropertyName("eligible")] bool Eligible,
    [property: JsonPropertyName("ineligible_code")] long IneligibleCode,
    [property: JsonPropertyName("ineligible_reason")] string IneligibleReason,
    [property: JsonPropertyName("available_reject_reasons")] IReadOnlyList<ReturnAndRefundGetDecisionEligibilityResponseDataDecisionsAvailableRejectReasons> AvailableRejectReasons);

public sealed record ReturnAndRefundGetDecisionEligibilityResponseDataDecisionsAvailableRejectReasons(
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("text")] string Text);


public sealed record ReturnAndRefundCalculateRefundRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("order_id")] string OrderId,
    [property: JsonPropertyName("request_type")] string RequestType,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("shipment_type")] string ShipmentType,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("handover_method")] string HandoverMethod,
    [property: JsonPropertyName("reason_name")] string ReasonName,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("order_line_item_ids")] IReadOnlyList<string> OrderLineItemIds,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("skus")] IReadOnlyList<ReturnAndRefundCalculateRefundRequestSkus> Skus,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("order_line_list")] IReadOnlyList<ReturnAndRefundCalculateRefundRequestOrderLineList> OrderLineList);

public sealed record ReturnAndRefundCalculateRefundRequestSkus(
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("quantity")] long Quantity);

public sealed record ReturnAndRefundCalculateRefundRequestOrderLineList(
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("order_line_item_id")] string OrderLineItemId,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("sub_order_line_item_id")] string SubOrderLineItemId);


public sealed record ReturnAndRefundCalculateRefundResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] ReturnAndRefundCalculateRefundResponseData Data);

public sealed record ReturnAndRefundCalculateRefundResponseData(
    [property: JsonPropertyName("order_refund_amount")] ReturnAndRefundCalculateRefundResponseDataOrderRefundAmount OrderRefundAmount);

public sealed record ReturnAndRefundCalculateRefundResponseDataOrderRefundAmount(
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("refund_total")] string RefundTotal,
    [property: JsonPropertyName("refund_subtotal")] string RefundSubtotal,
    [property: JsonPropertyName("refund_shipping_fee")] string RefundShippingFee,
    [property: JsonPropertyName("refund_tax")] string RefundTax,
    [property: JsonPropertyName("retail_delivery_fee")] string RetailDeliveryFee);


public sealed record ReturnAndRefundCancelOrderRequest(
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("order_id")] string OrderId,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("skus")] IReadOnlyList<ReturnAndRefundCancelOrderRequestSkus> Skus,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("order_line_item_ids")] IReadOnlyList<string> OrderLineItemIds,
    [property: JsonPropertyName("cancel_reason")] string CancelReason,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("order_line_list")] IReadOnlyList<ReturnAndRefundCancelOrderRequestOrderLineList> OrderLineList);

public sealed record ReturnAndRefundCancelOrderRequestSkus(
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("quantity")] long Quantity);

public sealed record ReturnAndRefundCancelOrderRequestOrderLineList(
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("order_line_item_id")] string OrderLineItemId,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("sub_order_line_item_id")] string SubOrderLineItemId);


public sealed record ReturnAndRefundCancelOrderResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] ReturnAndRefundCancelOrderResponseData Data);

public sealed record ReturnAndRefundCancelOrderResponseData(
    [property: JsonPropertyName("cancel_id")] string CancelId,
    [property: JsonPropertyName("cancel_status")] string CancelStatus);


public sealed record ReturnAndRefundCreateReturnRequest(
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("idempotency_key")] string IdempotencyKey,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("order_id")] string OrderId,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("skus")] IReadOnlyList<ReturnAndRefundCreateReturnRequestSkus> Skus,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("order_line_item_ids")] IReadOnlyList<string> OrderLineItemIds,
    [property: JsonPropertyName("return_reason")] string ReturnReason,
    [property: JsonPropertyName("return_type")] string ReturnType,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("refund_total")] string RefundTotal,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("shipment_type")] string ShipmentType,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("handover_method")] string HandoverMethod,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("order_line_list")] IReadOnlyList<ReturnAndRefundCreateReturnRequestOrderLineList> OrderLineList);

public sealed record ReturnAndRefundCreateReturnRequestSkus(
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("quantity")] long Quantity);

public sealed record ReturnAndRefundCreateReturnRequestOrderLineList(
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("order_line_item_id")] string OrderLineItemId,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("sub_order_line_item_id")] string SubOrderLineItemId);


public sealed record ReturnAndRefundCreateReturnResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] ReturnAndRefundCreateReturnResponseData Data);

public sealed record ReturnAndRefundCreateReturnResponseData(
    [property: JsonPropertyName("return_id")] string ReturnId,
    [property: JsonPropertyName("return_status")] string ReturnStatus);


public sealed record ReturnAndRefundGetAftersaleEligibilityRequest(
    [property: JsonPropertyName("order_id")] string OrderId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("initiate_aftersale_user")] string InitiateAftersaleUser,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("request_types")] IReadOnlyList<string> RequestTypes,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record ReturnAndRefundGetAftersaleEligibilityResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] ReturnAndRefundGetAftersaleEligibilityResponseData Data);

public sealed record ReturnAndRefundGetAftersaleEligibilityResponseData(
    [property: JsonPropertyName("sku_eligibility")] IReadOnlyList<ReturnAndRefundGetAftersaleEligibilityResponseDataSkuEligibility> SkuEligibility);

public sealed record ReturnAndRefundGetAftersaleEligibilityResponseDataSkuEligibility(
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("line_item_eligibility")] IReadOnlyList<ReturnAndRefundGetAftersaleEligibilityResponseDataSkuEligibilityLineItemEligibility> LineItemEligibility);

public sealed record ReturnAndRefundGetAftersaleEligibilityResponseDataSkuEligibilityLineItemEligibility(
    [property: JsonPropertyName("request_type")] string RequestType,
    [property: JsonPropertyName("order_line_items_ids")] IReadOnlyList<string> OrderLineItemsIds,
    [property: JsonPropertyName("eligible")] bool Eligible,
    [property: JsonPropertyName("ineligible_code")] long IneligibleCode,
    [property: JsonPropertyName("ineligible_reason")] string IneligibleReason,
    [property: JsonPropertyName("available_reason_names")] IReadOnlyList<string> AvailableReasonNames,
    [property: JsonPropertyName("order_line_list")] IReadOnlyList<ReturnAndRefundGetAftersaleEligibilityResponseDataSkuEligibilityLineItemEligibilityOrderLineList> OrderLineList);

public sealed record ReturnAndRefundGetAftersaleEligibilityResponseDataSkuEligibilityLineItemEligibilityOrderLineList(
    [property: JsonPropertyName("order_line_item_id")] string OrderLineItemId,
    [property: JsonPropertyName("sub_order_line_item_id")] string SubOrderLineItemId);


public sealed record ReturnAndRefundSearchCancellationsRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("page_size")] string PageSize,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("page_token")] string PageToken,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("sort_field")] string SortField,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("sort_order")] string SortOrder,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("cancel_ids")] IReadOnlyList<string> CancelIds,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("order_ids")] IReadOnlyList<string> OrderIds,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("buyer_user_ids")] IReadOnlyList<string> BuyerUserIds,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("cancel_types")] IReadOnlyList<string> CancelTypes,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("cancel_status")] IReadOnlyList<string> CancelStatus,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("create_time_ge")] long CreateTimeGe,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("create_time_lt")] long CreateTimeLt,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("update_time_ge")] long UpdateTimeGe,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("update_time_lt")] long UpdateTimeLt,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("locale")] string Locale);


public sealed record ReturnAndRefundSearchCancellationsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] ReturnAndRefundSearchCancellationsResponseData Data);

public sealed record ReturnAndRefundSearchCancellationsResponseData(
    [property: JsonPropertyName("cancellations")] IReadOnlyList<ReturnAndRefundSearchCancellationsResponseDataCancellations> Cancellations,
    [property: JsonPropertyName("total_count")] long TotalCount,
    [property: JsonPropertyName("next_page_token")] string NextPageToken);

public sealed record ReturnAndRefundSearchCancellationsResponseDataCancellations(
    [property: JsonPropertyName("order_id")] string OrderId,
    [property: JsonPropertyName("cancel_type")] string CancelType,
    [property: JsonPropertyName("cancel_status")] string CancelStatus,
    [property: JsonPropertyName("role")] string Role,
    [property: JsonPropertyName("cancel_reason")] string CancelReason,
    [property: JsonPropertyName("cancel_reason_text")] string CancelReasonText,
    [property: JsonPropertyName("create_time")] long CreateTime,
    [property: JsonPropertyName("update_time")] long UpdateTime,
    [property: JsonPropertyName("seller_next_action_response")] IReadOnlyList<ReturnAndRefundSearchCancellationsResponseDataCancellationsSellerNextActionResponse> SellerNextActionResponse,
    [property: JsonPropertyName("refund_amount")] ReturnAndRefundSearchCancellationsResponseDataCancellationsRefundAmount RefundAmount,
    [property: JsonPropertyName("cancel_line_items")] IReadOnlyList<ReturnAndRefundSearchCancellationsResponseDataCancellationsCancelLineItems> CancelLineItems,
    [property: JsonPropertyName("cancel_id")] string CancelId,
    [property: JsonPropertyName("should_replenish_stock")] bool ShouldReplenishStock);

public sealed record ReturnAndRefundSearchCancellationsResponseDataCancellationsSellerNextActionResponse(
    [property: JsonPropertyName("action")] string Action,
    [property: JsonPropertyName("deadline")] long Deadline);

public sealed record ReturnAndRefundSearchCancellationsResponseDataCancellationsRefundAmount(
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("refund_total")] string RefundTotal,
    [property: JsonPropertyName("refund_subtotal")] string RefundSubtotal,
    [property: JsonPropertyName("refund_shipping_fee")] string RefundShippingFee,
    [property: JsonPropertyName("refund_tax")] string RefundTax,
    [property: JsonPropertyName("retail_delivery_fee")] string RetailDeliveryFee,
    [property: JsonPropertyName("buyer_service_fee")] string BuyerServiceFee);

public sealed record ReturnAndRefundSearchCancellationsResponseDataCancellationsCancelLineItems(
    [property: JsonPropertyName("cancel_line_item_id")] string CancelLineItemId,
    [property: JsonPropertyName("order_line_item_id")] string OrderLineItemId,
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("sku_name")] string SkuName,
    [property: JsonPropertyName("product_image")] ReturnAndRefundSearchCancellationsResponseDataCancellationsCancelLineItemsProductImage ProductImage,
    [property: JsonPropertyName("product_name")] string ProductName,
    [property: JsonPropertyName("seller_sku")] string SellerSku,
    [property: JsonPropertyName("refund_amount")] ReturnAndRefundSearchCancellationsResponseDataCancellationsCancelLineItemsRefundAmount RefundAmount,
    [property: JsonPropertyName("cancel_sub_line_items")] IReadOnlyList<ReturnAndRefundSearchCancellationsResponseDataCancellationsCancelLineItemsCancelSubLineItems> CancelSubLineItems);

public sealed record ReturnAndRefundSearchCancellationsResponseDataCancellationsCancelLineItemsProductImage(
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("width")] long Width,
    [property: JsonPropertyName("height")] long Height);

public sealed record ReturnAndRefundSearchCancellationsResponseDataCancellationsCancelLineItemsRefundAmount(
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("refund_total")] string RefundTotal,
    [property: JsonPropertyName("refund_subtotal")] string RefundSubtotal,
    [property: JsonPropertyName("refund_shipping_fee")] string RefundShippingFee,
    [property: JsonPropertyName("refund_tax")] string RefundTax,
    [property: JsonPropertyName("retail_delivery_fee")] string RetailDeliveryFee,
    [property: JsonPropertyName("buyer_service_fee")] string BuyerServiceFee);

public sealed record ReturnAndRefundSearchCancellationsResponseDataCancellationsCancelLineItemsCancelSubLineItems(
    [property: JsonPropertyName("cancel_sub_line_item_id")] string CancelSubLineItemId,
    [property: JsonPropertyName("cancel_line_item_id")] string CancelLineItemId,
    [property: JsonPropertyName("sub_order_line_item_id")] string SubOrderLineItemId,
    [property: JsonPropertyName("order_line_item_id")] string OrderLineItemId,
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("sku_name")] string SkuName,
    [property: JsonPropertyName("product_image")] ReturnAndRefundSearchCancellationsResponseDataCancellationsCancelLineItemsCancelSubLineItemsProductImage ProductImage,
    [property: JsonPropertyName("product_name")] string ProductName,
    [property: JsonPropertyName("seller_sku")] string SellerSku,
    [property: JsonPropertyName("refund_amount")] ReturnAndRefundSearchCancellationsResponseDataCancellationsCancelLineItemsCancelSubLineItemsRefundAmount RefundAmount);

public sealed record ReturnAndRefundSearchCancellationsResponseDataCancellationsCancelLineItemsCancelSubLineItemsProductImage(
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("width")] long Width,
    [property: JsonPropertyName("height")] long Height);

public sealed record ReturnAndRefundSearchCancellationsResponseDataCancellationsCancelLineItemsCancelSubLineItemsRefundAmount(
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("refund_total")] string RefundTotal,
    [property: JsonPropertyName("refund_subtotal")] string RefundSubtotal,
    [property: JsonPropertyName("refund_shipping_fee")] string RefundShippingFee,
    [property: JsonPropertyName("refund_tax")] string RefundTax,
    [property: JsonPropertyName("retail_delivery_fee")] string RetailDeliveryFee,
    [property: JsonPropertyName("buyer_service_fee")] string BuyerServiceFee);


public sealed record ReturnAndRefundSearchReturnsRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("page_size")] string PageSize,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("page_token")] string PageToken,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("sort_field")] string SortField,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("sort_order")] string SortOrder,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("return_ids")] IReadOnlyList<string> ReturnIds,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("order_ids")] IReadOnlyList<string> OrderIds,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("buyer_user_ids")] IReadOnlyList<string> BuyerUserIds,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("return_types")] IReadOnlyList<string> ReturnTypes,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("return_status")] IReadOnlyList<string> ReturnStatus,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("seller_proposed_return_type")] IReadOnlyList<string> SellerProposedReturnType,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("create_time_ge")] long CreateTimeGe,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("arbitration_status")] IReadOnlyList<string> ArbitrationStatus,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("update_time_ge")] long UpdateTimeGe,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("update_time_lt")] long UpdateTimeLt,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("locale")] string Locale,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("create_time_lt")] long CreateTimeLt);


public sealed record ReturnAndRefundSearchReturnsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] ReturnAndRefundSearchReturnsResponseData Data);

public sealed record ReturnAndRefundSearchReturnsResponseData(
    [property: JsonPropertyName("return_orders")] IReadOnlyList<ReturnAndRefundSearchReturnsResponseDataReturnOrders> ReturnOrders,
    [property: JsonPropertyName("total_count")] long TotalCount,
    [property: JsonPropertyName("next_page_token")] string NextPageToken);

public sealed record ReturnAndRefundSearchReturnsResponseDataReturnOrders(
    [property: JsonPropertyName("order_id")] string OrderId,
    [property: JsonPropertyName("return_id")] string ReturnId,
    [property: JsonPropertyName("return_type")] string ReturnType,
    [property: JsonPropertyName("return_status")] string ReturnStatus,
    [property: JsonPropertyName("arbitration_status")] string ArbitrationStatus,
    [property: JsonPropertyName("role")] string Role,
    [property: JsonPropertyName("return_reason")] string ReturnReason,
    [property: JsonPropertyName("return_reason_text")] string ReturnReasonText,
    [property: JsonPropertyName("shipment_type")] string ShipmentType,
    [property: JsonPropertyName("handover_method")] string HandoverMethod,
    [property: JsonPropertyName("return_tracking_number")] string ReturnTrackingNumber,
    [property: JsonPropertyName("return_provider_name")] string ReturnProviderName,
    [property: JsonPropertyName("return_provider_id")] string ReturnProviderId,
    [property: JsonPropertyName("pre_return_id")] string PreReturnId,
    [property: JsonPropertyName("next_return_id")] string NextReturnId,
    [property: JsonPropertyName("can_buyer_keep_item")] bool CanBuyerKeepItem,
    [property: JsonPropertyName("update_time")] long UpdateTime,
    [property: JsonPropertyName("seller_next_action_response")] IReadOnlyList<ReturnAndRefundSearchReturnsResponseDataReturnOrdersSellerNextActionResponse> SellerNextActionResponse,
    [property: JsonPropertyName("create_time")] long CreateTime,
    [property: JsonPropertyName("return_line_items")] IReadOnlyList<ReturnAndRefundSearchReturnsResponseDataReturnOrdersReturnLineItems> ReturnLineItems,
    [property: JsonPropertyName("discount_amount")] IReadOnlyList<ReturnAndRefundSearchReturnsResponseDataReturnOrdersDiscountAmount> DiscountAmount,
    [property: JsonPropertyName("shipping_fee_amount")] IReadOnlyList<ReturnAndRefundSearchReturnsResponseDataReturnOrdersShippingFeeAmount> ShippingFeeAmount,
    [property: JsonPropertyName("refund_amount")] ReturnAndRefundSearchReturnsResponseDataReturnOrdersRefundAmount RefundAmount,
    [property: JsonPropertyName("return_shipping_document_type")] string ReturnShippingDocumentType,
    [property: JsonPropertyName("return_method")] string ReturnMethod,
    [property: JsonPropertyName("is_combined_return")] bool IsCombinedReturn,
    [property: JsonPropertyName("combined_return_id")] string CombinedReturnId,
    [property: JsonPropertyName("seller_proposed_return_type")] string SellerProposedReturnType,
    [property: JsonPropertyName("partial_refund")] ReturnAndRefundSearchReturnsResponseDataReturnOrdersPartialRefund PartialRefund,
    [property: JsonPropertyName("buyer_rejected_partial_refund")] bool BuyerRejectedPartialRefund,
    [property: JsonPropertyName("return_warehouse_address")] ReturnAndRefundSearchReturnsResponseDataReturnOrdersReturnWarehouseAddress ReturnWarehouseAddress,
    [property: JsonPropertyName("is_quick_refund")] bool IsQuickRefund);

public sealed record ReturnAndRefundSearchReturnsResponseDataReturnOrdersSellerNextActionResponse(
    [property: JsonPropertyName("action")] string Action,
    [property: JsonPropertyName("deadline")] long Deadline);

public sealed record ReturnAndRefundSearchReturnsResponseDataReturnOrdersReturnLineItems(
    [property: JsonPropertyName("return_line_item_id")] string ReturnLineItemId,
    [property: JsonPropertyName("order_line_item_id")] string OrderLineItemId,
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("sku_name")] string SkuName,
    [property: JsonPropertyName("product_name")] string ProductName,
    [property: JsonPropertyName("seller_sku")] string SellerSku,
    [property: JsonPropertyName("product_image")] ReturnAndRefundSearchReturnsResponseDataReturnOrdersReturnLineItemsProductImage ProductImage,
    [property: JsonPropertyName("refund_amount")] ReturnAndRefundSearchReturnsResponseDataReturnOrdersReturnLineItemsRefundAmount RefundAmount,
    [property: JsonPropertyName("return_sub_line_items")] IReadOnlyList<ReturnAndRefundSearchReturnsResponseDataReturnOrdersReturnLineItemsReturnSubLineItems> ReturnSubLineItems);

public sealed record ReturnAndRefundSearchReturnsResponseDataReturnOrdersReturnLineItemsProductImage(
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("width")] long Width,
    [property: JsonPropertyName("height")] long Height);

public sealed record ReturnAndRefundSearchReturnsResponseDataReturnOrdersReturnLineItemsRefundAmount(
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("refund_total")] string RefundTotal,
    [property: JsonPropertyName("refund_subtotal")] string RefundSubtotal,
    [property: JsonPropertyName("refund_shipping_fee")] string RefundShippingFee,
    [property: JsonPropertyName("refund_tax")] string RefundTax,
    [property: JsonPropertyName("retail_delivery_fee")] string RetailDeliveryFee,
    [property: JsonPropertyName("buyer_service_fee")] string BuyerServiceFee);

public sealed record ReturnAndRefundSearchReturnsResponseDataReturnOrdersReturnLineItemsReturnSubLineItems(
    [property: JsonPropertyName("return_sub_line_item_id")] string ReturnSubLineItemId,
    [property: JsonPropertyName("return_line_item_id")] string ReturnLineItemId,
    [property: JsonPropertyName("sub_order_line_item_id")] string SubOrderLineItemId,
    [property: JsonPropertyName("order_line_item_id")] string OrderLineItemId,
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("sku_name")] string SkuName,
    [property: JsonPropertyName("product_image")] ReturnAndRefundSearchReturnsResponseDataReturnOrdersReturnLineItemsReturnSubLineItemsProductImage ProductImage,
    [property: JsonPropertyName("product_name")] string ProductName,
    [property: JsonPropertyName("seller_sku")] string SellerSku,
    [property: JsonPropertyName("refund_amount")] ReturnAndRefundSearchReturnsResponseDataReturnOrdersReturnLineItemsReturnSubLineItemsRefundAmount RefundAmount);

public sealed record ReturnAndRefundSearchReturnsResponseDataReturnOrdersReturnLineItemsReturnSubLineItemsProductImage(
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("width")] long Width,
    [property: JsonPropertyName("height")] long Height);

public sealed record ReturnAndRefundSearchReturnsResponseDataReturnOrdersReturnLineItemsReturnSubLineItemsRefundAmount(
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("refund_total")] string RefundTotal,
    [property: JsonPropertyName("refund_subtotal")] string RefundSubtotal,
    [property: JsonPropertyName("refund_shipping_fee")] string RefundShippingFee,
    [property: JsonPropertyName("refund_tax")] string RefundTax,
    [property: JsonPropertyName("retail_delivery_fee")] string RetailDeliveryFee,
    [property: JsonPropertyName("buyer_service_fee")] string BuyerServiceFee);

public sealed record ReturnAndRefundSearchReturnsResponseDataReturnOrdersDiscountAmount(
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("product_seller_discount")] string ProductSellerDiscount,
    [property: JsonPropertyName("shipping_fee_platform_discount")] string ShippingFeePlatformDiscount,
    [property: JsonPropertyName("shipping_fee_seller_discount")] string ShippingFeeSellerDiscount,
    [property: JsonPropertyName("product_platform_discount")] string ProductPlatformDiscount);

public sealed record ReturnAndRefundSearchReturnsResponseDataReturnOrdersShippingFeeAmount(
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("seller_paid_return_shipping_fee")] string SellerPaidReturnShippingFee,
    [property: JsonPropertyName("platform_paid_return_shipping_fee")] string PlatformPaidReturnShippingFee,
    [property: JsonPropertyName("buyer_paid_return_shipping_fee")] string BuyerPaidReturnShippingFee);

public sealed record ReturnAndRefundSearchReturnsResponseDataReturnOrdersRefundAmount(
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("refund_total")] string RefundTotal,
    [property: JsonPropertyName("refund_subtotal")] string RefundSubtotal,
    [property: JsonPropertyName("refund_shipping_fee")] string RefundShippingFee,
    [property: JsonPropertyName("refund_tax")] string RefundTax,
    [property: JsonPropertyName("retail_delivery_fee")] string RetailDeliveryFee,
    [property: JsonPropertyName("buyer_service_fee")] string BuyerServiceFee);

public sealed record ReturnAndRefundSearchReturnsResponseDataReturnOrdersPartialRefund(
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("amount")] string Amount);

public sealed record ReturnAndRefundSearchReturnsResponseDataReturnOrdersReturnWarehouseAddress(
    [property: JsonPropertyName("full_address")] string FullAddress);
