<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TikTokPartnerSdk.Storage.EntityFramework</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TikTokPartnerSdk.Abstractions\TikTokPartnerSdk.Abstractions.csproj" />
  </ItemGroup>
</Project>
