// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;
namespace TikTokPartnerSdk.Generated.AffiliateCreator;

public sealed record AffiliateCreatorAddShowcaseProductsRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("add_type")] string AddType,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("product_ids")] IReadOnlyList<string> ProductIds,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("product_link")] string ProductLink);


public sealed record AffiliateCreatorAddShowcaseProductsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorAddShowcaseProductsResponseData Data);

public sealed record AffiliateCreatorAddShowcaseProductsResponseData(
    [property: JsonPropertyName("errors")] IReadOnlyList<AffiliateCreatorAddShowcaseProductsResponseDataErrors> Errors);

public sealed record AffiliateCreatorAddShowcaseProductsResponseDataErrors(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("detail")] AffiliateCreatorAddShowcaseProductsResponseDataErrorsDetail Detail);

public sealed record AffiliateCreatorAddShowcaseProductsResponseDataErrorsDetail(
    [property: JsonPropertyName("product_id")] string ProductId);


public sealed record AffiliateCreatorCreatorSearchOpenCollaborationProductRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("page_size")] long PageSize,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("page_token")] string PageToken,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("sort_field")] string SortField,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("sort_order")] string SortOrder,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("title_keywords")] IReadOnlyList<string> TitleKeywords,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("sales_price_range")] AffiliateCreatorCreatorSearchOpenCollaborationProductRequestSalesPriceRange SalesPriceRange,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("category")] AffiliateCreatorCreatorSearchOpenCollaborationProductRequestCategory Category,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("commission_rate_range")] AffiliateCreatorCreatorSearchOpenCollaborationProductRequestCommissionRateRange CommissionRateRange);

public sealed record AffiliateCreatorCreatorSearchOpenCollaborationProductRequestSalesPriceRange(
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("amount_ge")] string AmountGe,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("amount_lt")] string AmountLt);

public sealed record AffiliateCreatorCreatorSearchOpenCollaborationProductRequestCategory(
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("id")] string Id);

public sealed record AffiliateCreatorCreatorSearchOpenCollaborationProductRequestCommissionRateRange(
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("rate_ge")] long RateGe,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("rate_lt")] long RateLt);


public sealed record AffiliateCreatorCreatorSearchOpenCollaborationProductResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorCreatorSearchOpenCollaborationProductResponseData Data);

public sealed record AffiliateCreatorCreatorSearchOpenCollaborationProductResponseData(
    [property: JsonPropertyName("products")] IReadOnlyList<AffiliateCreatorCreatorSearchOpenCollaborationProductResponseDataProducts> Products,
    [property: JsonPropertyName("next_page_token")] string NextPageToken,
    [property: JsonPropertyName("total_count")] long TotalCount);

public sealed record AffiliateCreatorCreatorSearchOpenCollaborationProductResponseDataProducts(
    [property: JsonPropertyName("shop")] AffiliateCreatorCreatorSearchOpenCollaborationProductResponseDataProductsShop Shop,
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("has_inventory")] bool HasInventory,
    [property: JsonPropertyName("units_sold")] long UnitsSold,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonPropertyName("sale_region")] string SaleRegion,
    [property: JsonPropertyName("main_image_url")] string MainImageUrl,
    [property: JsonPropertyName("detail_link")] string DetailLink,
    [property: JsonPropertyName("original_price")] AffiliateCreatorCreatorSearchOpenCollaborationProductResponseDataProductsOriginalPrice OriginalPrice,
    [property: JsonPropertyName("category_chains")] IReadOnlyList<AffiliateCreatorCreatorSearchOpenCollaborationProductResponseDataProductsCategoryChains> CategoryChains,
    [property: JsonPropertyName("commission")] AffiliateCreatorCreatorSearchOpenCollaborationProductResponseDataProductsCommission Commission,
    [property: JsonPropertyName("sales_price")] AffiliateCreatorCreatorSearchOpenCollaborationProductResponseDataProductsSalesPrice SalesPrice);

public sealed record AffiliateCreatorCreatorSearchOpenCollaborationProductResponseDataProductsShop(
    [property: JsonPropertyName("name")] string Name);

public sealed record AffiliateCreatorCreatorSearchOpenCollaborationProductResponseDataProductsOriginalPrice(
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("minimum_amount")] string MinimumAmount,
    [property: JsonPropertyName("maximum_amount")] string MaximumAmount);

public sealed record AffiliateCreatorCreatorSearchOpenCollaborationProductResponseDataProductsCategoryChains(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("local_name")] string LocalName,
    [property: JsonPropertyName("is_leaf")] bool IsLeaf,
    [property: JsonPropertyName("parent_id")] string ParentId);

public sealed record AffiliateCreatorCreatorSearchOpenCollaborationProductResponseDataProductsCommission(
    [property: JsonPropertyName("rate")] long Rate,
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("amount")] string Amount);

public sealed record AffiliateCreatorCreatorSearchOpenCollaborationProductResponseDataProductsSalesPrice(
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("minimum_amount")] string MinimumAmount,
    [property: JsonPropertyName("maximum_amount")] string MaximumAmount);


public sealed record AffiliateCreatorGetShowcaseProductsRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("origin")] string Origin,
    [property: JsonPropertyName("page_size")] long PageSize,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("page_token")] string PageToken);


public sealed record AffiliateCreatorGetShowcaseProductsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorGetShowcaseProductsResponseData Data);

public sealed record AffiliateCreatorGetShowcaseProductsResponseData(
    [property: JsonPropertyName("products")] IReadOnlyList<AffiliateCreatorGetShowcaseProductsResponseDataProducts> Products,
    [property: JsonPropertyName("next_page_token")] string NextPageToken,
    [property: JsonPropertyName("total_count")] long TotalCount);

public sealed record AffiliateCreatorGetShowcaseProductsResponseDataProducts(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("shop")] AffiliateCreatorGetShowcaseProductsResponseDataProductsShop Shop,
    [property: JsonPropertyName("addition")] AffiliateCreatorGetShowcaseProductsResponseDataProductsAddition Addition,
    [property: JsonPropertyName("price")] AffiliateCreatorGetShowcaseProductsResponseDataProductsPrice Price,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonPropertyName("main_images")] IReadOnlyList<AffiliateCreatorGetShowcaseProductsResponseDataProductsMainImages> MainImages,
    [property: JsonPropertyName("status")] AffiliateCreatorGetShowcaseProductsResponseDataProductsStatus Status,
    [property: JsonPropertyName("source")] string Source,
    [property: JsonPropertyName("detail_link")] string DetailLink,
    [property: JsonPropertyName("third_party_link")] string ThirdPartyLink,
    [property: JsonPropertyName("sale_regions")] IReadOnlyList<string> SaleRegions,
    [property: JsonPropertyName("commission")] AffiliateCreatorGetShowcaseProductsResponseDataProductsCommission Commission,
    [property: JsonPropertyName("collaboration")] AffiliateCreatorGetShowcaseProductsResponseDataProductsCollaboration Collaboration);

public sealed record AffiliateCreatorGetShowcaseProductsResponseDataProductsShop(
    [property: JsonPropertyName("name")] string Name);

public sealed record AffiliateCreatorGetShowcaseProductsResponseDataProductsAddition(
    [property: JsonPropertyName("customized_main_images")] IReadOnlyList<AffiliateCreatorGetShowcaseProductsResponseDataProductsAdditionCustomizedMainImages> CustomizedMainImages);

public sealed record AffiliateCreatorGetShowcaseProductsResponseDataProductsAdditionCustomizedMainImages(
    [property: JsonPropertyName("width")] long Width,
    [property: JsonPropertyName("heigth")] long Heigth,
    [property: JsonPropertyName("url")] string Url);

public sealed record AffiliateCreatorGetShowcaseProductsResponseDataProductsPrice(
    [property: JsonPropertyName("original_price")] AffiliateCreatorGetShowcaseProductsResponseDataProductsPriceOriginalPrice OriginalPrice,
    [property: JsonPropertyName("seller_discount_price")] AffiliateCreatorGetShowcaseProductsResponseDataProductsPriceSellerDiscountPrice SellerDiscountPrice,
    [property: JsonPropertyName("platform_discount_price")] AffiliateCreatorGetShowcaseProductsResponseDataProductsPricePlatformDiscountPrice PlatformDiscountPrice);

public sealed record AffiliateCreatorGetShowcaseProductsResponseDataProductsPriceOriginalPrice(
    [property: JsonPropertyName("minimum_amount")] string MinimumAmount,
    [property: JsonPropertyName("maximum_amount")] string MaximumAmount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorGetShowcaseProductsResponseDataProductsPriceSellerDiscountPrice(
    [property: JsonPropertyName("minimum_amount")] string MinimumAmount,
    [property: JsonPropertyName("maximum_amount")] string MaximumAmount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorGetShowcaseProductsResponseDataProductsPricePlatformDiscountPrice(
    [property: JsonPropertyName("minimum_amount")] string MinimumAmount,
    [property: JsonPropertyName("maximum_amount")] string MaximumAmount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorGetShowcaseProductsResponseDataProductsMainImages(
    [property: JsonPropertyName("width")] long Width,
    [property: JsonPropertyName("heigth")] long Heigth,
    [property: JsonPropertyName("url")] string Url);

public sealed record AffiliateCreatorGetShowcaseProductsResponseDataProductsStatus(
    [property: JsonPropertyName("inventory_status")] string InventoryStatus,
    [property: JsonPropertyName("review_status")] string ReviewStatus,
    [property: JsonPropertyName("is_hidden")] bool IsHidden,
    [property: JsonPropertyName("added_status")] string AddedStatus);

public sealed record AffiliateCreatorGetShowcaseProductsResponseDataProductsCommission(
    [property: JsonPropertyName("rate")] long Rate,
    [property: JsonPropertyName("reward_rate")] long RewardRate);

public sealed record AffiliateCreatorGetShowcaseProductsResponseDataProductsCollaboration(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("partner")] AffiliateCreatorGetShowcaseProductsResponseDataProductsCollaborationPartner Partner);

public sealed record AffiliateCreatorGetShowcaseProductsResponseDataProductsCollaborationPartner(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("name")] string Name);


public sealed record AffiliateCreatorSearchCreatorTargetCollaborationsRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("page_size")] long PageSize,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("page_token")] string PageToken,
    [property: JsonPropertyName("shop_id")] string ShopId,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("keyword_type")] string KeywordType,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("keyword")] string Keyword);


public sealed record AffiliateCreatorSearchCreatorTargetCollaborationsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorSearchCreatorTargetCollaborationsResponseData Data);

public sealed record AffiliateCreatorSearchCreatorTargetCollaborationsResponseData(
    [property: JsonPropertyName("total_count")] long TotalCount,
    [property: JsonPropertyName("next_page_token")] string NextPageToken,
    [property: JsonPropertyName("target_collaborations")] IReadOnlyList<AffiliateCreatorSearchCreatorTargetCollaborationsResponseDataTargetCollaborations> TargetCollaborations);

public sealed record AffiliateCreatorSearchCreatorTargetCollaborationsResponseDataTargetCollaborations(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("products")] IReadOnlyList<AffiliateCreatorSearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProducts> Products);

public sealed record AffiliateCreatorSearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProducts(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonPropertyName("main_image_url")] string MainImageUrl,
    [property: JsonPropertyName("commission")] AffiliateCreatorSearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProductsCommission Commission);

public sealed record AffiliateCreatorSearchCreatorTargetCollaborationsResponseDataTargetCollaborationsProductsCommission(
    [property: JsonPropertyName("rate")] long Rate,
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);


public sealed record AffiliateCreatorCreatorSearchSampleApplicationFulfillmentsRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("sort_field")] string SortField,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("sort_order")] string SortOrder,
    [property: JsonPropertyName("fulfillment_statuses")] IReadOnlyList<string> FulfillmentStatuses);


public sealed record AffiliateCreatorCreatorSearchSampleApplicationFulfillmentsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorCreatorSearchSampleApplicationFulfillmentsResponseData Data);

public sealed record AffiliateCreatorCreatorSearchSampleApplicationFulfillmentsResponseData(
    [property: JsonPropertyName("fulfillments")] IReadOnlyList<AffiliateCreatorCreatorSearchSampleApplicationFulfillmentsResponseDataFulfillments> Fulfillments);

public sealed record AffiliateCreatorCreatorSearchSampleApplicationFulfillmentsResponseDataFulfillments(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("shop_id")] string ShopId,
    [property: JsonPropertyName("application_id")] string ApplicationId,
    [property: JsonPropertyName("sample_application_type")] string SampleApplicationType,
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("expiration_time")] long ExpirationTime,
    [property: JsonPropertyName("total_suspend_duration")] long TotalSuspendDuration,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("bound_product_status")] string BoundProductStatus);


public sealed record AffiliateCreatorRemoveShowcaseProductsRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("product_ids")] IReadOnlyList<string> ProductIds);


public sealed record AffiliateCreatorRemoveShowcaseProductsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorRemoveShowcaseProductsResponseData Data);

public sealed record AffiliateCreatorRemoveShowcaseProductsResponseData(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId);


public sealed record AffiliateCreatorTopShowcaseProductsRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("product_ids")] IReadOnlyList<string> ProductIds);


public sealed record AffiliateCreatorTopShowcaseProductsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorTopShowcaseProductsResponseData Data);

public sealed record AffiliateCreatorTopShowcaseProductsResponseData(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId);


public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("page_size")] long PageSize,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("page_token")] string PageToken,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("create_time_ge")] long CreateTimeGe,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("create_time_lt")] long CreateTimeLt);


public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorSearchCreatorAffiliateOrdersResponseData Data);

public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponseData(
    [property: JsonPropertyName("orders")] IReadOnlyList<AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrders> Orders,
    [property: JsonPropertyName("next_page_token")] string NextPageToken,
    [property: JsonPropertyName("total_count")] long TotalCount);

public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrders(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("create_time")] long CreateTime,
    [property: JsonPropertyName("delivery_time")] long DeliveryTime,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("skus")] IReadOnlyList<AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkus> Skus);

public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkus(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("campaign_id")] string CampaignId,
    [property: JsonPropertyName("open_collaboration_id")] string OpenCollaborationId,
    [property: JsonPropertyName("target_collaboration_id")] string TargetCollaborationId,
    [property: JsonPropertyName("product_name")] string ProductName,
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("price")] AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusPrice Price,
    [property: JsonPropertyName("shop_name")] string ShopName,
    [property: JsonPropertyName("content_type")] string ContentType,
    [property: JsonPropertyName("content_id")] string ContentId,
    [property: JsonPropertyName("quantity")] long Quantity,
    [property: JsonPropertyName("commission_rate")] long CommissionRate,
    [property: JsonPropertyName("commission_tier_setting")] string CommissionTierSetting,
    [property: JsonPropertyName("commission_model")] string CommissionModel,
    [property: JsonPropertyName("commission_bonus_rate")] long CommissionBonusRate,
    [property: JsonPropertyName("estimated_commission_base")] AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusEstimatedCommissionBase EstimatedCommissionBase,
    [property: JsonPropertyName("standard_commission_rate")] long StandardCommissionRate,
    [property: JsonPropertyName("shop_ads_commission_rate")] long ShopAdsCommissionRate,
    [property: JsonPropertyName("estimated_bonus_commission")] AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusEstimatedBonusCommission EstimatedBonusCommission,
    [property: JsonPropertyName("estimated_standard_commission")] AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusEstimatedStandardCommission EstimatedStandardCommission,
    [property: JsonPropertyName("estimated_shop_ads_commission")] AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusEstimatedShopAdsCommission EstimatedShopAdsCommission,
    [property: JsonPropertyName("estimated_commission")] AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusEstimatedCommission EstimatedCommission,
    [property: JsonPropertyName("actual_commission")] AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusActualCommission ActualCommission,
    [property: JsonPropertyName("actual_bonus_commission")] AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusActualBonusCommission ActualBonusCommission,
    [property: JsonPropertyName("actual_commission_base")] AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusActualCommissionBase ActualCommissionBase,
    [property: JsonPropertyName("actual_standard_commission")] AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusActualStandardCommission ActualStandardCommission,
    [property: JsonPropertyName("actual_shop_ads_commission")] AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusActualShopAdsCommission ActualShopAdsCommission,
    [property: JsonPropertyName("returned_quantity")] long ReturnedQuantity,
    [property: JsonPropertyName("refunded_quantity")] long RefundedQuantity,
    [property: JsonPropertyName("tag")] string Tag,
    [property: JsonPropertyName("creator_commission_reward_rate")] long CreatorCommissionRewardRate,
    [property: JsonPropertyName("estimated_creator_commission_reward_fee")] AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommissionRewardFee EstimatedCreatorCommissionRewardFee,
    [property: JsonPropertyName("actual_creator_commission_reward_fee")] AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusActualCreatorCommissionRewardFee ActualCreatorCommissionRewardFee,
    [property: JsonPropertyName("isr")] AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusIsr Isr,
    [property: JsonPropertyName("iva")] AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusIva Iva,
    [property: JsonPropertyName("pit")] AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusPit Pit,
    [property: JsonPropertyName("shared_with_partner")] AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusSharedWithPartner SharedWithPartner,
    [property: JsonPropertyName("trace_info")] AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusTraceInfo TraceInfo,
    [property: JsonPropertyName("last_update_time")] long LastUpdateTime);

public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusPrice(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusEstimatedCommissionBase(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusEstimatedBonusCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusEstimatedStandardCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusEstimatedShopAdsCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusEstimatedCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusActualCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusActualBonusCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusActualCommissionBase(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusActualStandardCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusActualShopAdsCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusEstimatedCreatorCommissionRewardFee(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusActualCreatorCommissionRewardFee(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusIsr(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusIva(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusPit(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusSharedWithPartner(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorSearchCreatorAffiliateOrdersResponseDataOrdersSkusTraceInfo(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("type")] string Type);


public sealed record AffiliateCreatorGetCreatorApplicableSampleLabelRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("product_id")] string ProductId);


public sealed record AffiliateCreatorGetCreatorApplicableSampleLabelResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorGetCreatorApplicableSampleLabelResponseData Data);

public sealed record AffiliateCreatorGetCreatorApplicableSampleLabelResponseData(
    [property: JsonPropertyName("label")] AffiliateCreatorGetCreatorApplicableSampleLabelResponseDataLabel Label);

public sealed record AffiliateCreatorGetCreatorApplicableSampleLabelResponseDataLabel(
    [property: JsonPropertyName("can_apply")] bool CanApply,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("application_id")] string ApplicationId,
    [property: JsonPropertyName("reach_limit")] bool ReachLimit,
    [property: JsonPropertyName("sample_product")] AffiliateCreatorGetCreatorApplicableSampleLabelResponseDataLabelSampleProduct SampleProduct);

public sealed record AffiliateCreatorGetCreatorApplicableSampleLabelResponseDataLabelSampleProduct(
    [property: JsonPropertyName("sample_sku_list")] IReadOnlyList<AffiliateCreatorGetCreatorApplicableSampleLabelResponseDataLabelSampleProductSampleSkuList> SampleSkuList);

public sealed record AffiliateCreatorGetCreatorApplicableSampleLabelResponseDataLabelSampleProductSampleSkuList(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("sale_property_value_ids")] string SalePropertyValueIds,
    [property: JsonPropertyName("price")] AffiliateCreatorGetCreatorApplicableSampleLabelResponseDataLabelSampleProductSampleSkuListPrice Price,
    [property: JsonPropertyName("sale_properties")] IReadOnlyList<AffiliateCreatorGetCreatorApplicableSampleLabelResponseDataLabelSampleProductSampleSkuListSaleProperties> SaleProperties,
    [property: JsonPropertyName("is_available")] bool IsAvailable,
    [property: JsonPropertyName("unavailable_reason")] string UnavailableReason);

public sealed record AffiliateCreatorGetCreatorApplicableSampleLabelResponseDataLabelSampleProductSampleSkuListPrice(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorGetCreatorApplicableSampleLabelResponseDataLabelSampleProductSampleSkuListSaleProperties(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("value_id")] string ValueId,
    [property: JsonPropertyName("value_name")] string ValueName);


public sealed record AffiliateCreatorGetCreatorSampleApplicationDetailRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("application_id")] string ApplicationId,
    [property: JsonPropertyName("application_type")] string ApplicationType,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("main_order_id")] string MainOrderId);


public sealed record AffiliateCreatorGetCreatorSampleApplicationDetailResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorGetCreatorSampleApplicationDetailResponseData Data);

public sealed record AffiliateCreatorGetCreatorSampleApplicationDetailResponseData(
    [property: JsonPropertyName("sample_application")] AffiliateCreatorGetCreatorSampleApplicationDetailResponseDataSampleApplication SampleApplication);

public sealed record AffiliateCreatorGetCreatorSampleApplicationDetailResponseDataSampleApplication(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("create_time")] long CreateTime,
    [property: JsonPropertyName("sample_product")] AffiliateCreatorGetCreatorSampleApplicationDetailResponseDataSampleApplicationSampleProduct SampleProduct,
    [property: JsonPropertyName("main_order_id")] string MainOrderId,
    [property: JsonPropertyName("activity_id")] string ActivityId,
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("creator_fulfillment")] AffiliateCreatorGetCreatorSampleApplicationDetailResponseDataSampleApplicationCreatorFulfillment CreatorFulfillment);

public sealed record AffiliateCreatorGetCreatorSampleApplicationDetailResponseDataSampleApplicationSampleProduct(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("sku_sale_property_value_names")] IReadOnlyList<string> SkuSalePropertyValueNames);

public sealed record AffiliateCreatorGetCreatorSampleApplicationDetailResponseDataSampleApplicationCreatorFulfillment(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("expiration_time")] long ExpirationTime,
    [property: JsonPropertyName("total_suspend_duration")] long TotalSuspendDuration,
    [property: JsonPropertyName("status")] string Status);


public sealed record AffiliateCreatorSearchCreatorSampleApplicationsRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("page_size")] long PageSize,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("page_token")] string PageToken,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("application_statuses")] IReadOnlyList<string> ApplicationStatuses);


public sealed record AffiliateCreatorSearchCreatorSampleApplicationsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorSearchCreatorSampleApplicationsResponseData Data);

public sealed record AffiliateCreatorSearchCreatorSampleApplicationsResponseData(
    [property: JsonPropertyName("next_page_token")] string NextPageToken,
    [property: JsonPropertyName("sample_applications")] IReadOnlyList<AffiliateCreatorSearchCreatorSampleApplicationsResponseDataSampleApplications> SampleApplications);

public sealed record AffiliateCreatorSearchCreatorSampleApplicationsResponseDataSampleApplications(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("sample_product")] AffiliateCreatorSearchCreatorSampleApplicationsResponseDataSampleApplicationsSampleProduct SampleProduct,
    [property: JsonPropertyName("main_order_id")] string MainOrderId,
    [property: JsonPropertyName("activity_id")] string ActivityId,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("creator_fulfillment")] AffiliateCreatorSearchCreatorSampleApplicationsResponseDataSampleApplicationsCreatorFulfillment CreatorFulfillment);

public sealed record AffiliateCreatorSearchCreatorSampleApplicationsResponseDataSampleApplicationsSampleProduct(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("sku_sale_property_value_names")] IReadOnlyList<string> SkuSalePropertyValueNames);

public sealed record AffiliateCreatorSearchCreatorSampleApplicationsResponseDataSampleApplicationsCreatorFulfillment(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("expiration_time")] long ExpirationTime,
    [property: JsonPropertyName("total_suspend_duration")] long TotalSuspendDuration,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("bound_product_status")] string BoundProductStatus);


public sealed record AffiliateCreatorCreatorGeneratePublisherLinkRequest(
    [property: JsonPropertyName("publisher_id")] string PublisherId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("material")] AffiliateCreatorCreatorGeneratePublisherLinkRequestMaterial Material,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("campaign_id")] string CampaignId,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("link_type")] string LinkType);

public sealed record AffiliateCreatorCreatorGeneratePublisherLinkRequestMaterial(
    [property: JsonPropertyName("ids")] IReadOnlyList<string> Ids,
    [property: JsonPropertyName("type")] string Type);


public sealed record AffiliateCreatorCreatorGeneratePublisherLinkResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorCreatorGeneratePublisherLinkResponseData Data);

public sealed record AffiliateCreatorCreatorGeneratePublisherLinkResponseData(
    [property: JsonPropertyName("sharing_links")] IReadOnlyList<AffiliateCreatorCreatorGeneratePublisherLinkResponseDataSharingLinks> SharingLinks,
    [property: JsonPropertyName("failed_materials")] IReadOnlyList<AffiliateCreatorCreatorGeneratePublisherLinkResponseDataFailedMaterials> FailedMaterials);

public sealed record AffiliateCreatorCreatorGeneratePublisherLinkResponseDataSharingLinks(
    [property: JsonPropertyName("material_id")] long MaterialId,
    [property: JsonPropertyName("sharing_link")] string SharingLink,
    [property: JsonPropertyName("deep_link")] string DeepLink,
    [property: JsonPropertyName("one_link")] string OneLink);

public sealed record AffiliateCreatorCreatorGeneratePublisherLinkResponseDataFailedMaterials(
    [property: JsonPropertyName("material_id")] string MaterialId,
    [property: JsonPropertyName("fail_reason")] string FailReason);


public sealed record AffiliateCreatorCreatorGenerateGeneralLinkRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("material")] AffiliateCreatorCreatorGenerateGeneralLinkRequestMaterial Material,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("campaign_id")] string CampaignId,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("link_type")] string LinkType);

public sealed record AffiliateCreatorCreatorGenerateGeneralLinkRequestMaterial(
    [property: JsonPropertyName("ids")] IReadOnlyList<string> Ids,
    [property: JsonPropertyName("type")] string Type);


public sealed record AffiliateCreatorCreatorGenerateGeneralLinkResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorCreatorGenerateGeneralLinkResponseData Data);

public sealed record AffiliateCreatorCreatorGenerateGeneralLinkResponseData(
    [property: JsonPropertyName("sharing_links")] IReadOnlyList<AffiliateCreatorCreatorGenerateGeneralLinkResponseDataSharingLinks> SharingLinks,
    [property: JsonPropertyName("failed_materials")] IReadOnlyList<AffiliateCreatorCreatorGenerateGeneralLinkResponseDataFailedMaterials> FailedMaterials);

public sealed record AffiliateCreatorCreatorGenerateGeneralLinkResponseDataSharingLinks(
    [property: JsonPropertyName("material_id")] string MaterialId,
    [property: JsonPropertyName("sharing_link")] string SharingLink,
    [property: JsonPropertyName("deep_link")] string DeepLink,
    [property: JsonPropertyName("one_link")] string OneLink);

public sealed record AffiliateCreatorCreatorGenerateGeneralLinkResponseDataFailedMaterials(
    [property: JsonPropertyName("material_id")] string MaterialId,
    [property: JsonPropertyName("fail_reason")] string FailReason);


public sealed record AffiliateCreatorCreatorSearchAffiliateTraceOrdersRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("page_size")] long PageSize,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("page_token")] string PageToken,
    [property: JsonPropertyName("time_ge")] long TimeGe,
    [property: JsonPropertyName("time_lt")] long TimeLt,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("time_type")] string TimeType);


public sealed record AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseData Data);

public sealed record AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseData(
    [property: JsonPropertyName("orders")] IReadOnlyList<AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrders> Orders,
    [property: JsonPropertyName("next_page_token")] string NextPageToken,
    [property: JsonPropertyName("total_count")] long TotalCount);

public sealed record AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrders(
    [property: JsonPropertyName("id")] long Id,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("skus")] IReadOnlyList<AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkus> Skus,
    [property: JsonPropertyName("create_time")] long CreateTime,
    [property: JsonPropertyName("delivery_time")] long DeliveryTime);

public sealed record AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkus(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("price")] AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice Price,
    [property: JsonPropertyName("quantity")] long Quantity,
    [property: JsonPropertyName("commission_rate")] long CommissionRate,
    [property: JsonPropertyName("estimated_commission_base")] AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusEstimatedCommissionBase EstimatedCommissionBase,
    [property: JsonPropertyName("actual_commission")] AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusActualCommission ActualCommission,
    [property: JsonPropertyName("shop_ads_commission_rate")] long ShopAdsCommissionRate,
    [property: JsonPropertyName("commission_bonus_rate")] long CommissionBonusRate,
    [property: JsonPropertyName("product_name")] string ProductName,
    [property: JsonPropertyName("shop_name")] string ShopName,
    [property: JsonPropertyName("returned_quantity")] long ReturnedQuantity,
    [property: JsonPropertyName("refunded_quantity")] long RefundedQuantity,
    [property: JsonPropertyName("campaign_id")] string CampaignId,
    [property: JsonPropertyName("actual_commission_base")] AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusActualCommissionBase ActualCommissionBase,
    [property: JsonPropertyName("actual_shop_ads_commission")] AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusActualShopAdsCommission ActualShopAdsCommission,
    [property: JsonPropertyName("estimated_shop_ads_commission")] AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusEstimatedShopAdsCommission EstimatedShopAdsCommission,
    [property: JsonPropertyName("estimated_bonus_commission")] AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusEstimatedBonusCommission EstimatedBonusCommission,
    [property: JsonPropertyName("delivery_time")] long DeliveryTime,
    [property: JsonPropertyName("creator_commission_reward_rate")] long CreatorCommissionRewardRate,
    [property: JsonPropertyName("estimated_creator_commission_reward_fee")] AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusEstimatedCreatorCommissionRewardFee EstimatedCreatorCommissionRewardFee,
    [property: JsonPropertyName("actual_creator_commission_reward_fee")] AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusActualCreatorCommissionRewardFee ActualCreatorCommissionRewardFee,
    [property: JsonPropertyName("content_type")] string ContentType,
    [property: JsonPropertyName("content_id")] string ContentId,
    [property: JsonPropertyName("trace")] AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusTrace Trace,
    [property: JsonPropertyName("estimated_commission")] AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusEstimatedCommission EstimatedCommission,
    [property: JsonPropertyName("actual_bonus_commission")] AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusActualBonusCommission ActualBonusCommission);

public sealed record AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusPrice(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusEstimatedCommissionBase(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusActualCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusActualCommissionBase(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusActualShopAdsCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusEstimatedShopAdsCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusEstimatedBonusCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusEstimatedCreatorCommissionRewardFee(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusActualCreatorCommissionRewardFee(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusTrace(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("type")] string Type);

public sealed record AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusEstimatedCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorCreatorSearchAffiliateTraceOrdersResponseDataOrdersSkusActualBonusCommission(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);


public sealed record AffiliateCreatorUploadShoppableVideoFileRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("data")] string Data);


public sealed record AffiliateCreatorUploadShoppableVideoFileResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorUploadShoppableVideoFileResponseData Data);

public sealed record AffiliateCreatorUploadShoppableVideoFileResponseData(
    [property: JsonPropertyName("video_file")] AffiliateCreatorUploadShoppableVideoFileResponseDataVideoFile VideoFile);

public sealed record AffiliateCreatorUploadShoppableVideoFileResponseDataVideoFile(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("md5")] string Md5);


public sealed record AffiliateCreatorGetCreatorProfileRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign);


public sealed record AffiliateCreatorGetCreatorProfileResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorGetCreatorProfileResponseData Data);

public sealed record AffiliateCreatorGetCreatorProfileResponseData(
    [property: JsonPropertyName("avatar")] AffiliateCreatorGetCreatorProfileResponseDataAvatar Avatar,
    [property: JsonPropertyName("username")] string Username,
    [property: JsonPropertyName("selection_region")] string SelectionRegion,
    [property: JsonPropertyName("register_region")] string RegisterRegion,
    [property: JsonPropertyName("seller_type")] string SellerType,
    [property: JsonPropertyName("permissions")] IReadOnlyList<string> Permissions,
    [property: JsonPropertyName("user_type")] string UserType,
    [property: JsonPropertyName("creator_user_open_id")] string CreatorUserOpenId);

public sealed record AffiliateCreatorGetCreatorProfileResponseDataAvatar(
    [property: JsonPropertyName("width")] long Width,
    [property: JsonPropertyName("height")] long Height,
    [property: JsonPropertyName("url")] string Url);


public sealed record AffiliateCreatorGetOpenCollaborationProductListByProductIdsRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("product_ids")] IReadOnlyList<string> ProductIds);


public sealed record AffiliateCreatorGetOpenCollaborationProductListByProductIdsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorGetOpenCollaborationProductListByProductIdsResponseData Data);

public sealed record AffiliateCreatorGetOpenCollaborationProductListByProductIdsResponseData(
    [property: JsonPropertyName("products")] IReadOnlyList<AffiliateCreatorGetOpenCollaborationProductListByProductIdsResponseDataProducts> Products);

public sealed record AffiliateCreatorGetOpenCollaborationProductListByProductIdsResponseDataProducts(
    [property: JsonPropertyName("shop")] AffiliateCreatorGetOpenCollaborationProductListByProductIdsResponseDataProductsShop Shop,
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("has_inventory")] bool HasInventory,
    [property: JsonPropertyName("units_sold")] long UnitsSold,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonPropertyName("sale_region")] string SaleRegion,
    [property: JsonPropertyName("main_image_url")] string MainImageUrl,
    [property: JsonPropertyName("detail_link")] string DetailLink,
    [property: JsonPropertyName("original_price")] AffiliateCreatorGetOpenCollaborationProductListByProductIdsResponseDataProductsOriginalPrice OriginalPrice,
    [property: JsonPropertyName("category_chains")] IReadOnlyList<AffiliateCreatorGetOpenCollaborationProductListByProductIdsResponseDataProductsCategoryChains> CategoryChains,
    [property: JsonPropertyName("commission")] AffiliateCreatorGetOpenCollaborationProductListByProductIdsResponseDataProductsCommission Commission,
    [property: JsonPropertyName("sales_price")] AffiliateCreatorGetOpenCollaborationProductListByProductIdsResponseDataProductsSalesPrice SalesPrice,
    [property: JsonPropertyName("shop_ads_commission")] AffiliateCreatorGetOpenCollaborationProductListByProductIdsResponseDataProductsShopAdsCommission ShopAdsCommission);

public sealed record AffiliateCreatorGetOpenCollaborationProductListByProductIdsResponseDataProductsShop(
    [property: JsonPropertyName("name")] string Name);

public sealed record AffiliateCreatorGetOpenCollaborationProductListByProductIdsResponseDataProductsOriginalPrice(
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("minimum_amount")] string MinimumAmount,
    [property: JsonPropertyName("maximum_amount")] string MaximumAmount);

public sealed record AffiliateCreatorGetOpenCollaborationProductListByProductIdsResponseDataProductsCategoryChains(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("local_name")] string LocalName,
    [property: JsonPropertyName("is_leaf")] bool IsLeaf,
    [property: JsonPropertyName("parent_id")] string ParentId);

public sealed record AffiliateCreatorGetOpenCollaborationProductListByProductIdsResponseDataProductsCommission(
    [property: JsonPropertyName("rate")] long Rate,
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("amount")] string Amount);

public sealed record AffiliateCreatorGetOpenCollaborationProductListByProductIdsResponseDataProductsSalesPrice(
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("minimum_amount")] string MinimumAmount,
    [property: JsonPropertyName("maximum_amount")] string MaximumAmount);

public sealed record AffiliateCreatorGetOpenCollaborationProductListByProductIdsResponseDataProductsShopAdsCommission(
    [property: JsonPropertyName("rate")] long Rate);


public sealed record AffiliateCreatorGetShopProductsRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("page_size")] long PageSize,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("page_token")] string PageToken,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("sort_field")] string SortField,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("sort_order")] string SortOrder,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("title_keyword")] string TitleKeyword);


public sealed record AffiliateCreatorGetShopProductsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorGetShopProductsResponseData Data);

public sealed record AffiliateCreatorGetShopProductsResponseData(
    [property: JsonPropertyName("products")] IReadOnlyList<AffiliateCreatorGetShopProductsResponseDataProducts> Products,
    [property: JsonPropertyName("total_count")] long TotalCount,
    [property: JsonPropertyName("next_page_token")] string NextPageToken);

public sealed record AffiliateCreatorGetShopProductsResponseDataProducts(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonPropertyName("price")] AffiliateCreatorGetShopProductsResponseDataProductsPrice Price,
    [property: JsonPropertyName("added_status")] string AddedStatus,
    [property: JsonPropertyName("brand_name")] string BrandName,
    [property: JsonPropertyName("images")] IReadOnlyList<AffiliateCreatorGetShopProductsResponseDataProductsImages> Images,
    [property: JsonPropertyName("sales_count")] long SalesCount);

public sealed record AffiliateCreatorGetShopProductsResponseDataProductsPrice(
    [property: JsonPropertyName("amount")] string Amount,
    [property: JsonPropertyName("currency")] string Currency);

public sealed record AffiliateCreatorGetShopProductsResponseDataProductsImages(
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("width")] long Width,
    [property: JsonPropertyName("height")] long Height);


public sealed record AffiliateCreatorGetShoppableVideoStatusRequest(
    [property: JsonPropertyName("video_id")] string VideoId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign);


public sealed record AffiliateCreatorGetShoppableVideoStatusResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorGetShoppableVideoStatusResponseData Data);

public sealed record AffiliateCreatorGetShoppableVideoStatusResponseData(
    [property: JsonPropertyName("video")] AffiliateCreatorGetShoppableVideoStatusResponseDataVideo Video);

public sealed record AffiliateCreatorGetShoppableVideoStatusResponseDataVideo(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("post_status")] string PostStatus,
    [property: JsonPropertyName("post_time")] long PostTime);


public sealed record AffiliateCreatorPrecheckVideoContentRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("video_info")] AffiliateCreatorPrecheckVideoContentRequestVideoInfo VideoInfo,
    [property: JsonPropertyName("product_link_info")] AffiliateCreatorPrecheckVideoContentRequestProductLinkInfo ProductLinkInfo);

public sealed record AffiliateCreatorPrecheckVideoContentRequestVideoInfo(
    [property: JsonPropertyName("file_id")] string FileId);

public sealed record AffiliateCreatorPrecheckVideoContentRequestProductLinkInfo(
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("title")] string Title);


public sealed record AffiliateCreatorPrecheckVideoContentResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorPrecheckVideoContentResponseData Data);

public sealed record AffiliateCreatorPrecheckVideoContentResponseData(
    [property: JsonPropertyName("precheck")] AffiliateCreatorPrecheckVideoContentResponseDataPrecheck Precheck);

public sealed record AffiliateCreatorPrecheckVideoContentResponseDataPrecheck(
    [property: JsonPropertyName("task_id")] string TaskId);


public sealed record AffiliateCreatorGetShoppableVideoPrecheckResultRequest(
    [property: JsonPropertyName("task_id")] string TaskId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign);


public sealed record AffiliateCreatorGetShoppableVideoPrecheckResultResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorGetShoppableVideoPrecheckResultResponseData Data);

public sealed record AffiliateCreatorGetShoppableVideoPrecheckResultResponseData(
    [property: JsonPropertyName("precheck_task")] AffiliateCreatorGetShoppableVideoPrecheckResultResponseDataPrecheckTask PrecheckTask);

public sealed record AffiliateCreatorGetShoppableVideoPrecheckResultResponseDataPrecheckTask(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("violation_check_result")] AffiliateCreatorGetShoppableVideoPrecheckResultResponseDataPrecheckTaskViolationCheckResult ViolationCheckResult,
    [property: JsonPropertyName("good_quality_check_result")] AffiliateCreatorGetShoppableVideoPrecheckResultResponseDataPrecheckTaskGoodQualityCheckResult GoodQualityCheckResult);

public sealed record AffiliateCreatorGetShoppableVideoPrecheckResultResponseDataPrecheckTaskViolationCheckResult(
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("issues")] IReadOnlyList<AffiliateCreatorGetShoppableVideoPrecheckResultResponseDataPrecheckTaskViolationCheckResultIssues> Issues);

public sealed record AffiliateCreatorGetShoppableVideoPrecheckResultResponseDataPrecheckTaskViolationCheckResultIssues(
    [property: JsonPropertyName("risk")] string Risk,
    [property: JsonPropertyName("suggestions")] string Suggestions);

public sealed record AffiliateCreatorGetShoppableVideoPrecheckResultResponseDataPrecheckTaskGoodQualityCheckResult(
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("issues")] IReadOnlyList<AffiliateCreatorGetShoppableVideoPrecheckResultResponseDataPrecheckTaskGoodQualityCheckResultIssues> Issues);

public sealed record AffiliateCreatorGetShoppableVideoPrecheckResultResponseDataPrecheckTaskGoodQualityCheckResultIssues(
    [property: JsonPropertyName("code")] string Code,
    [property: JsonPropertyName("suggestions")] string Suggestions);


public sealed record AffiliateCreatorPostShoppableVideoRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("video_info")] AffiliateCreatorPostShoppableVideoRequestVideoInfo VideoInfo,
    [property: JsonPropertyName("product_link_info")] AffiliateCreatorPostShoppableVideoRequestProductLinkInfo ProductLinkInfo);

public sealed record AffiliateCreatorPostShoppableVideoRequestVideoInfo(
    [property: JsonPropertyName("file_id")] string FileId,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("cover_uri")] string CoverUri,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("cover_timestamp_ms")] long CoverTimestampMs,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("music_id")] string MusicId);

public sealed record AffiliateCreatorPostShoppableVideoRequestProductLinkInfo(
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("title")] string Title);


public sealed record AffiliateCreatorPostShoppableVideoResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] AffiliateCreatorPostShoppableVideoResponseData Data);

public sealed record AffiliateCreatorPostShoppableVideoResponseData(
    [property: JsonPropertyName("video")] AffiliateCreatorPostShoppableVideoResponseDataVideo Video);

public sealed record AffiliateCreatorPostShoppableVideoResponseDataVideo(
    [property: JsonPropertyName("id")] string Id);
