// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;
namespace Loscardos.TikTokPartnerSdk.Generated.Order;

public sealed record OrderGetOrderListRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("page_size")] long PageSize,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("page_token")] string PageToken,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("sort_field")] string SortField,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("sort_order")] string SortOrder,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("order_status")] string OrderStatus,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("create_time_ge")] long? CreateTimeGe,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("create_time_lt")] long? CreateTimeLt,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("update_time_ge")] long? UpdateTimeGe,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("update_time_lt")] long? UpdateTimeLt,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("shipping_type")] string ShippingType,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("buyer_user_id")] string BuyerUserId,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("is_buyer_request_cancel")] bool? IsBuyerRequestCancel,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("warehouse_ids")] IReadOnlyList<string> WarehouseIds);


public sealed record OrderGetOrderListResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] OrderGetOrderListResponseData Data);

public sealed record OrderGetOrderListResponseData(
    [property: JsonPropertyName("next_page_token")] string NextPageToken,
    [property: JsonPropertyName("total_count")] long TotalCount,
    [property: JsonPropertyName("orders")] IReadOnlyList<OrderGetOrderListResponseDataOrders> Orders);

public sealed record OrderGetOrderListResponseDataOrders(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("buyer_message")] string BuyerMessage,
    [property: JsonPropertyName("cancellation_initiator")] string CancellationInitiator,
    [property: JsonPropertyName("shipping_provider_id")] string ShippingProviderId,
    [property: JsonPropertyName("create_time")] long CreateTime,
    [property: JsonPropertyName("shipping_provider")] string ShippingProvider,
    [property: JsonPropertyName("packages")] IReadOnlyList<OrderGetOrderListResponseDataOrdersPackages> Packages,
    [property: JsonPropertyName("payment")] OrderGetOrderListResponseDataOrdersPayment Payment,
    [property: JsonPropertyName("recipient_address")] OrderGetOrderListResponseDataOrdersRecipientAddress RecipientAddress,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("fulfillment_type")] string FulfillmentType,
    [property: JsonPropertyName("delivery_type")] string DeliveryType,
    [property: JsonPropertyName("paid_time")] long PaidTime,
    [property: JsonPropertyName("rts_sla_time")] long RtsSlaTime,
    [property: JsonPropertyName("tts_sla_time")] long TtsSlaTime,
    [property: JsonPropertyName("cancel_reason")] string CancelReason,
    [property: JsonPropertyName("update_time")] long UpdateTime,
    [property: JsonPropertyName("payment_method_name")] string PaymentMethodName,
    [property: JsonPropertyName("rts_time")] long RtsTime,
    [property: JsonPropertyName("tracking_number")] string TrackingNumber,
    [property: JsonPropertyName("split_or_combine_tag")] string SplitOrCombineTag,
    [property: JsonPropertyName("has_updated_recipient_address")] bool HasUpdatedRecipientAddress,
    [property: JsonPropertyName("cancel_order_sla_time")] long CancelOrderSlaTime,
    [property: JsonPropertyName("warehouse_id")] string WarehouseId,
    [property: JsonPropertyName("request_cancel_time")] long RequestCancelTime,
    [property: JsonPropertyName("shipping_type")] string ShippingType,
    [property: JsonPropertyName("user_id")] string UserId,
    [property: JsonPropertyName("seller_note")] string SellerNote,
    [property: JsonPropertyName("delivery_sla_time")] long DeliverySlaTime,
    [property: JsonPropertyName("is_cod")] bool IsCod,
    [property: JsonPropertyName("delivery_option_id")] string DeliveryOptionId,
    [property: JsonPropertyName("cancel_time")] long CancelTime,
    [property: JsonPropertyName("need_upload_invoice")] string NeedUploadInvoice,
    [property: JsonPropertyName("delivery_option_name")] string DeliveryOptionName,
    [property: JsonPropertyName("cpf")] string Cpf,
    [property: JsonPropertyName("line_items")] IReadOnlyList<OrderGetOrderListResponseDataOrdersLineItems> LineItems,
    [property: JsonPropertyName("buyer_email")] string BuyerEmail,
    [property: JsonPropertyName("delivery_due_time")] long DeliveryDueTime,
    [property: JsonPropertyName("is_sample_order")] bool IsSampleOrder,
    [property: JsonPropertyName("shipping_due_time")] long ShippingDueTime,
    [property: JsonPropertyName("collection_due_time")] long CollectionDueTime,
    [property: JsonPropertyName("delivery_option_required_delivery_time")] long DeliveryOptionRequiredDeliveryTime,
    [property: JsonPropertyName("is_on_hold_order")] bool IsOnHoldOrder,
    [property: JsonPropertyName("delivery_time")] long DeliveryTime,
    [property: JsonPropertyName("is_replacement_order")] bool IsReplacementOrder,
    [property: JsonPropertyName("is_subscription_order")] bool IsSubscriptionOrder,
    [property: JsonPropertyName("collection_time")] long CollectionTime,
    [property: JsonPropertyName("replaced_order_id")] string ReplacedOrderId,
    [property: JsonPropertyName("is_buyer_request_cancel")] bool IsBuyerRequestCancel,
    [property: JsonPropertyName("pick_up_cut_off_time")] long PickUpCutOffTime,
    [property: JsonPropertyName("fast_dispatch_sla_time")] long FastDispatchSlaTime,
    [property: JsonPropertyName("commerce_platform")] string CommercePlatform,
    [property: JsonPropertyName("order_type")] string OrderType,
    [property: JsonPropertyName("release_date")] long ReleaseDate,
    [property: JsonPropertyName("handling_duration")] OrderGetOrderListResponseDataOrdersHandlingDuration HandlingDuration,
    [property: JsonPropertyName("auto_combine_group_id")] string AutoCombineGroupId,
    [property: JsonPropertyName("cpf_name")] string CpfName,
    [property: JsonPropertyName("is_exchange_order")] bool IsExchangeOrder,
    [property: JsonPropertyName("exchange_source_order_id")] string ExchangeSourceOrderId,
    [property: JsonPropertyName("consultation_id")] string ConsultationId,
    [property: JsonPropertyName("fast_delivery_program")] string FastDeliveryProgram,
    [property: JsonPropertyName("fulfillment_priority_level")] long FulfillmentPriorityLevel,
    [property: JsonPropertyName("recommended_shipping_time")] long RecommendedShippingTime,
    [property: JsonPropertyName("buyer_nickname")] string BuyerNickname,
    [property: JsonPropertyName("buyer_avatar")] string BuyerAvatar,
    [property: JsonPropertyName("order_rights")] IReadOnlyList<long> OrderRights);

public sealed record OrderGetOrderListResponseDataOrdersPackages(
    [property: JsonPropertyName("id")] string Id);

public sealed record OrderGetOrderListResponseDataOrdersPayment(
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("sub_total")] string SubTotal,
    [property: JsonPropertyName("shipping_fee")] string ShippingFee,
    [property: JsonPropertyName("seller_discount")] string SellerDiscount,
    [property: JsonPropertyName("platform_discount")] string PlatformDiscount,
    [property: JsonPropertyName("payment_platform_discount")] string PaymentPlatformDiscount,
    [property: JsonPropertyName("payment_discount_service_fee")] string PaymentDiscountServiceFee,
    [property: JsonPropertyName("total_amount")] string TotalAmount,
    [property: JsonPropertyName("original_total_product_price")] string OriginalTotalProductPrice,
    [property: JsonPropertyName("original_shipping_fee")] string OriginalShippingFee,
    [property: JsonPropertyName("shipping_fee_seller_discount")] string ShippingFeeSellerDiscount,
    [property: JsonPropertyName("shipping_fee_platform_discount")] string ShippingFeePlatformDiscount,
    [property: JsonPropertyName("shipping_fee_cofunded_discount")] string ShippingFeeCofundedDiscount,
    [property: JsonPropertyName("tax")] string Tax,
    [property: JsonPropertyName("small_order_fee")] string SmallOrderFee,
    [property: JsonPropertyName("shipping_fee_tax")] string ShippingFeeTax,
    [property: JsonPropertyName("product_tax")] string ProductTax,
    [property: JsonPropertyName("retail_delivery_fee")] string RetailDeliveryFee,
    [property: JsonPropertyName("buyer_service_fee")] string BuyerServiceFee,
    [property: JsonPropertyName("handling_fee")] string HandlingFee,
    [property: JsonPropertyName("shipping_insurance_fee")] string ShippingInsuranceFee,
    [property: JsonPropertyName("item_insurance_fee")] string ItemInsuranceFee,
    [property: JsonPropertyName("item_insurance_tax")] string ItemInsuranceTax,
    [property: JsonPropertyName("distance_shipping_fee")] string DistanceShippingFee,
    [property: JsonPropertyName("distance_fee")] string DistanceFee);

public sealed record OrderGetOrderListResponseDataOrdersRecipientAddress(
    [property: JsonPropertyName("full_address")] string FullAddress,
    [property: JsonPropertyName("phone_number")] string PhoneNumber,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("first_name")] string FirstName,
    [property: JsonPropertyName("last_name")] string LastName,
    [property: JsonPropertyName("first_name_local_script")] string FirstNameLocalScript,
    [property: JsonPropertyName("last_name_local_script")] string LastNameLocalScript,
    [property: JsonPropertyName("address_detail")] string AddressDetail,
    [property: JsonPropertyName("address_line1")] string AddressLine1,
    [property: JsonPropertyName("address_line2")] string AddressLine2,
    [property: JsonPropertyName("address_line3")] string AddressLine3,
    [property: JsonPropertyName("address_line4")] string AddressLine4,
    [property: JsonPropertyName("district_info")] IReadOnlyList<OrderGetOrderListResponseDataOrdersRecipientAddressDistrictInfo> DistrictInfo,
    [property: JsonPropertyName("delivery_preferences")] OrderGetOrderListResponseDataOrdersRecipientAddressDeliveryPreferences DeliveryPreferences,
    [property: JsonPropertyName("postal_code")] string PostalCode,
    [property: JsonPropertyName("region_code")] string RegionCode,
    [property: JsonPropertyName("post_town")] string PostTown);

public sealed record OrderGetOrderListResponseDataOrdersRecipientAddressDistrictInfo(
    [property: JsonPropertyName("address_level_name")] string AddressLevelName,
    [property: JsonPropertyName("address_name")] string AddressName,
    [property: JsonPropertyName("address_level")] string AddressLevel,
    [property: JsonPropertyName("iso_code")] string IsoCode);

public sealed record OrderGetOrderListResponseDataOrdersRecipientAddressDeliveryPreferences(
    [property: JsonPropertyName("drop_off_location")] string DropOffLocation);

public sealed record OrderGetOrderListResponseDataOrdersLineItems(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("combined_listing_skus")] IReadOnlyList<OrderGetOrderListResponseDataOrdersLineItemsCombinedListingSkus> CombinedListingSkus,
    [property: JsonPropertyName("display_status")] string DisplayStatus,
    [property: JsonPropertyName("product_name")] string ProductName,
    [property: JsonPropertyName("seller_sku")] string SellerSku,
    [property: JsonPropertyName("sku_image")] string SkuImage,
    [property: JsonPropertyName("sku_name")] string SkuName,
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("sale_price")] string SalePrice,
    [property: JsonPropertyName("pfand_fee")] string PfandFee,
    [property: JsonPropertyName("platform_discount")] string PlatformDiscount,
    [property: JsonPropertyName("seller_discount")] string SellerDiscount,
    [property: JsonPropertyName("sku_type")] string SkuType,
    [property: JsonPropertyName("cancel_reason")] string CancelReason,
    [property: JsonPropertyName("original_price")] string OriginalPrice,
    [property: JsonPropertyName("rts_time")] long RtsTime,
    [property: JsonPropertyName("package_status")] string PackageStatus,
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("shipping_provider_name")] string ShippingProviderName,
    [property: JsonPropertyName("cancel_user")] string CancelUser,
    [property: JsonPropertyName("shipping_provider_id")] string ShippingProviderId,
    [property: JsonPropertyName("is_gift")] bool IsGift,
    [property: JsonPropertyName("item_tax")] IReadOnlyList<OrderGetOrderListResponseDataOrdersLineItemsItemTax> ItemTax,
    [property: JsonPropertyName("tracking_number")] string TrackingNumber,
    [property: JsonPropertyName("package_id")] string PackageId,
    [property: JsonPropertyName("retail_delivery_fee")] string RetailDeliveryFee,
    [property: JsonPropertyName("buyer_service_fee")] string BuyerServiceFee,
    [property: JsonPropertyName("small_order_fee")] string SmallOrderFee,
    [property: JsonPropertyName("handling_duration_days")] string HandlingDurationDays,
    [property: JsonPropertyName("is_dangerous_good")] bool IsDangerousGood,
    [property: JsonPropertyName("needs_prescription")] bool NeedsPrescription,
    [property: JsonPropertyName("gift_retail_price")] string GiftRetailPrice,
    [property: JsonPropertyName("is_unboxing_item")] bool IsUnboxingItem,
    [property: JsonPropertyName("unboxing_sku_code")] string UnboxingSkuCode,
    [property: JsonPropertyName("sub_item_info")] IReadOnlyList<OrderGetOrderListResponseDataOrdersLineItemsSubItemInfo> SubItemInfo,
    [property: JsonPropertyName("distance_shipping_fee")] string DistanceShippingFee,
    [property: JsonPropertyName("distance_fee")] string DistanceFee);

public sealed record OrderGetOrderListResponseDataOrdersLineItemsCombinedListingSkus(
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("sku_count")] long SkuCount,
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("seller_sku")] string SellerSku);

public sealed record OrderGetOrderListResponseDataOrdersLineItemsItemTax(
    [property: JsonPropertyName("tax_type")] string TaxType,
    [property: JsonPropertyName("tax_amount")] string TaxAmount,
    [property: JsonPropertyName("tax_rate")] string TaxRate);

public sealed record OrderGetOrderListResponseDataOrdersLineItemsSubItemInfo(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("display_status")] string DisplayStatus,
    [property: JsonPropertyName("product_name")] string ProductName,
    [property: JsonPropertyName("seller_sku")] string SellerSku,
    [property: JsonPropertyName("sku_image")] string SkuImage,
    [property: JsonPropertyName("sku_name")] string SkuName,
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("sale_price")] string SalePrice,
    [property: JsonPropertyName("platform_discount")] string PlatformDiscount,
    [property: JsonPropertyName("seller_discount")] string SellerDiscount,
    [property: JsonPropertyName("cancel_reason")] string CancelReason,
    [property: JsonPropertyName("original_price")] string OriginalPrice,
    [property: JsonPropertyName("rts_time")] long RtsTime,
    [property: JsonPropertyName("package_status")] string PackageStatus,
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("shipping_provider_name")] string ShippingProviderName,
    [property: JsonPropertyName("cancel_user")] string CancelUser,
    [property: JsonPropertyName("shipping_provider_id")] string ShippingProviderId,
    [property: JsonPropertyName("item_tax")] IReadOnlyList<OrderGetOrderListResponseDataOrdersLineItemsSubItemInfoItemTax> ItemTax,
    [property: JsonPropertyName("tracking_number")] string TrackingNumber,
    [property: JsonPropertyName("package_id")] string PackageId,
    [property: JsonPropertyName("retail_delivery_fee")] string RetailDeliveryFee,
    [property: JsonPropertyName("is_dangerous_good")] bool IsDangerousGood,
    [property: JsonPropertyName("warehouse_id")] string WarehouseId);

public sealed record OrderGetOrderListResponseDataOrdersLineItemsSubItemInfoItemTax(
    [property: JsonPropertyName("tax_type")] string TaxType,
    [property: JsonPropertyName("tax_amount")] string TaxAmount,
    [property: JsonPropertyName("tax_rate")] string TaxRate);

public sealed record OrderGetOrderListResponseDataOrdersHandlingDuration(
    [property: JsonPropertyName("days")] string Days,
    [property: JsonPropertyName("type")] string Type);


public sealed record OrderAddExternalOrderReferencesRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("orders")] IReadOnlyList<OrderAddExternalOrderReferencesRequestOrders> Orders);

public sealed record OrderAddExternalOrderReferencesRequestOrders(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("external_order")] OrderAddExternalOrderReferencesRequestOrdersExternalOrder ExternalOrder);

public sealed record OrderAddExternalOrderReferencesRequestOrdersExternalOrder(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("platform")] string Platform,
    [property: JsonPropertyName("line_items")] IReadOnlyList<OrderAddExternalOrderReferencesRequestOrdersExternalOrderLineItems> LineItems);

public sealed record OrderAddExternalOrderReferencesRequestOrdersExternalOrderLineItems(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("origin_id")] string OriginId);


public sealed record OrderAddExternalOrderReferencesResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] OrderAddExternalOrderReferencesResponseData Data);

public sealed record OrderAddExternalOrderReferencesResponseData(
    [property: JsonPropertyName("errors")] IReadOnlyList<OrderAddExternalOrderReferencesResponseDataErrors> Errors);

public sealed record OrderAddExternalOrderReferencesResponseDataErrors(
    [property: JsonPropertyName("code")] string Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("detail")] OrderAddExternalOrderReferencesResponseDataErrorsDetail Detail);

public sealed record OrderAddExternalOrderReferencesResponseDataErrorsDetail(
    [property: JsonPropertyName("order_id")] string OrderId,
    [property: JsonPropertyName("external_order")] OrderAddExternalOrderReferencesResponseDataErrorsDetailExternalOrder ExternalOrder);

public sealed record OrderAddExternalOrderReferencesResponseDataErrorsDetailExternalOrder(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("platform")] string Platform);


public sealed record OrderGetExternalOrderReferencesRequest(
    [property: JsonPropertyName("order_id")] string OrderId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("platform")] string Platform,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record OrderGetExternalOrderReferencesResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] OrderGetExternalOrderReferencesResponseData Data);

public sealed record OrderGetExternalOrderReferencesResponseData(
    [property: JsonPropertyName("external_orders")] IReadOnlyList<OrderGetExternalOrderReferencesResponseDataExternalOrders> ExternalOrders);

public sealed record OrderGetExternalOrderReferencesResponseDataExternalOrders(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("platform")] string Platform,
    [property: JsonPropertyName("line_items")] IReadOnlyList<OrderGetExternalOrderReferencesResponseDataExternalOrdersLineItems> LineItems);

public sealed record OrderGetExternalOrderReferencesResponseDataExternalOrdersLineItems(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("origin_id")] string OriginId);


public sealed record OrderSearchOrderByExternalOrderReferenceRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("external_order_id")] string ExternalOrderId,
    [property: JsonPropertyName("platform")] string Platform,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record OrderSearchOrderByExternalOrderReferenceResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] OrderSearchOrderByExternalOrderReferenceResponseData Data);

public sealed record OrderSearchOrderByExternalOrderReferenceResponseData(
    [property: JsonPropertyName("orders")] IReadOnlyList<OrderSearchOrderByExternalOrderReferenceResponseDataOrders> Orders);

public sealed record OrderSearchOrderByExternalOrderReferenceResponseDataOrders(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("external_order")] OrderSearchOrderByExternalOrderReferenceResponseDataOrdersExternalOrder ExternalOrder);

public sealed record OrderSearchOrderByExternalOrderReferenceResponseDataOrdersExternalOrder(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("platform")] string Platform,
    [property: JsonPropertyName("line_items")] IReadOnlyList<OrderSearchOrderByExternalOrderReferenceResponseDataOrdersExternalOrderLineItems> LineItems);

public sealed record OrderSearchOrderByExternalOrderReferenceResponseDataOrdersExternalOrderLineItems(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("origin_id")] string OriginId);


public sealed record OrderGetPriceDetailRequest(
    [property: JsonPropertyName("order_id")] string OrderId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record OrderGetPriceDetailResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] OrderGetPriceDetailResponseData Data);

public sealed record OrderGetPriceDetailResponseData(
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("total")] string Total,
    [property: JsonPropertyName("payment")] string Payment,
    [property: JsonPropertyName("sku_list_price")] string SkuListPrice,
    [property: JsonPropertyName("sku_sale_price")] string SkuSalePrice,
    [property: JsonPropertyName("subtotal")] string Subtotal,
    [property: JsonPropertyName("subtotal_deduction_seller")] string SubtotalDeductionSeller,
    [property: JsonPropertyName("subtotal_deduction_platform")] string SubtotalDeductionPlatform,
    [property: JsonPropertyName("subtotal_tax_amount")] string SubtotalTaxAmount,
    [property: JsonPropertyName("voucher_deduction_platform")] string VoucherDeductionPlatform,
    [property: JsonPropertyName("voucher_deduction_seller")] string VoucherDeductionSeller,
    [property: JsonPropertyName("shipping_list_price")] string ShippingListPrice,
    [property: JsonPropertyName("shipping_sale_price")] string ShippingSalePrice,
    [property: JsonPropertyName("shipping_fee_deduction_seller")] string ShippingFeeDeductionSeller,
    [property: JsonPropertyName("shipping_fee_deduction_platform")] string ShippingFeeDeductionPlatform,
    [property: JsonPropertyName("shipping_fee_deduction_platform_voucher")] string ShippingFeeDeductionPlatformVoucher,
    [property: JsonPropertyName("tax_amount")] string TaxAmount,
    [property: JsonPropertyName("tax_rate")] string TaxRate,
    [property: JsonPropertyName("net_price_amount")] string NetPriceAmount,
    [property: JsonPropertyName("cod_fee")] string CodFee,
    [property: JsonPropertyName("cod_fee_net_amount")] string CodFeeNetAmount,
    [property: JsonPropertyName("sku_gift_original_price")] string SkuGiftOriginalPrice,
    [property: JsonPropertyName("sku_gift_net_price")] string SkuGiftNetPrice,
    [property: JsonPropertyName("distance_shipping_fee")] string DistanceShippingFee,
    [property: JsonPropertyName("distance_fee")] string DistanceFee,
    [property: JsonPropertyName("line_items")] IReadOnlyList<OrderGetPriceDetailResponseDataLineItems> LineItems);

public sealed record OrderGetPriceDetailResponseDataLineItems(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("total")] string Total,
    [property: JsonPropertyName("payment")] string Payment,
    [property: JsonPropertyName("sku_list_price")] string SkuListPrice,
    [property: JsonPropertyName("sku_sale_price")] string SkuSalePrice,
    [property: JsonPropertyName("subtotal")] string Subtotal,
    [property: JsonPropertyName("subtotal_deduction_seller")] string SubtotalDeductionSeller,
    [property: JsonPropertyName("subtotal_deduction_platform")] string SubtotalDeductionPlatform,
    [property: JsonPropertyName("subtotal_tax_amount")] string SubtotalTaxAmount,
    [property: JsonPropertyName("voucher_deduction_platform")] string VoucherDeductionPlatform,
    [property: JsonPropertyName("voucher_deduction_seller")] string VoucherDeductionSeller,
    [property: JsonPropertyName("shipping_list_price")] string ShippingListPrice,
    [property: JsonPropertyName("shipping_sale_price")] string ShippingSalePrice,
    [property: JsonPropertyName("shipping_fee_deduction_seller")] string ShippingFeeDeductionSeller,
    [property: JsonPropertyName("shipping_fee_deduction_platform")] string ShippingFeeDeductionPlatform,
    [property: JsonPropertyName("shipping_fee_deduction_platform_voucher")] string ShippingFeeDeductionPlatformVoucher,
    [property: JsonPropertyName("tax_amount")] string TaxAmount,
    [property: JsonPropertyName("tax_rate")] string TaxRate,
    [property: JsonPropertyName("net_price_amount")] string NetPriceAmount,
    [property: JsonPropertyName("cod_fee")] string CodFee,
    [property: JsonPropertyName("cod_fee_amount")] string CodFeeAmount,
    [property: JsonPropertyName("sku_gift_original_price")] string SkuGiftOriginalPrice,
    [property: JsonPropertyName("sku_gift_net_price")] string SkuGiftNetPrice,
    [property: JsonPropertyName("distance_shipping_fee")] string DistanceShippingFee,
    [property: JsonPropertyName("distance_fee")] string DistanceFee);


public sealed record OrderGetOrderDetailRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("ids")] IReadOnlyList<string> Ids,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record OrderGetOrderDetailResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] OrderGetOrderDetailResponseData Data);

public sealed record OrderGetOrderDetailResponseData(
    [property: JsonPropertyName("orders")] IReadOnlyList<OrderGetOrderDetailResponseDataOrders> Orders);

public sealed record OrderGetOrderDetailResponseDataOrders(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("cancellation_initiator")] string CancellationInitiator,
    [property: JsonPropertyName("shipping_provider")] string ShippingProvider,
    [property: JsonPropertyName("shipping_provider_id")] string ShippingProviderId,
    [property: JsonPropertyName("user_id")] string UserId,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("rts_time")] long RtsTime,
    [property: JsonPropertyName("payment")] OrderGetOrderDetailResponseDataOrdersPayment Payment,
    [property: JsonPropertyName("recipient_address")] OrderGetOrderDetailResponseDataOrdersRecipientAddress RecipientAddress,
    [property: JsonPropertyName("buyer_message")] string BuyerMessage,
    [property: JsonPropertyName("create_time")] long CreateTime,
    [property: JsonPropertyName("tracking_number")] string TrackingNumber,
    [property: JsonPropertyName("cancel_reason")] string CancelReason,
    [property: JsonPropertyName("rts_sla_time")] long RtsSlaTime,
    [property: JsonPropertyName("paid_time")] long PaidTime,
    [property: JsonPropertyName("fulfillment_type")] string FulfillmentType,
    [property: JsonPropertyName("seller_note")] string SellerNote,
    [property: JsonPropertyName("tts_sla_time")] long TtsSlaTime,
    [property: JsonPropertyName("cancel_order_sla_time")] long CancelOrderSlaTime,
    [property: JsonPropertyName("update_time")] long UpdateTime,
    [property: JsonPropertyName("packages")] IReadOnlyList<OrderGetOrderDetailResponseDataOrdersPackages> Packages,
    [property: JsonPropertyName("delivery_type")] string DeliveryType,
    [property: JsonPropertyName("is_sample_order")] bool IsSampleOrder,
    [property: JsonPropertyName("warehouse_id")] string WarehouseId,
    [property: JsonPropertyName("split_or_combine_tag")] string SplitOrCombineTag,
    [property: JsonPropertyName("has_updated_recipient_address")] bool HasUpdatedRecipientAddress,
    [property: JsonPropertyName("cpf")] string Cpf,
    [property: JsonPropertyName("delivery_option_id")] string DeliveryOptionId,
    [property: JsonPropertyName("delivery_sla_time")] long DeliverySlaTime,
    [property: JsonPropertyName("payment_method_name")] string PaymentMethodName,
    [property: JsonPropertyName("payment_card_type")] string PaymentCardType,
    [property: JsonPropertyName("channel_entity_national_registry_id")] string ChannelEntityNationalRegistryId,
    [property: JsonPropertyName("payment_method_code")] string PaymentMethodCode,
    [property: JsonPropertyName("payment_auth_code")] string PaymentAuthCode,
    [property: JsonPropertyName("shipping_due_time")] long ShippingDueTime,
    [property: JsonPropertyName("line_items")] IReadOnlyList<OrderGetOrderDetailResponseDataOrdersLineItems> LineItems,
    [property: JsonPropertyName("shipping_type")] string ShippingType,
    [property: JsonPropertyName("buyer_email")] string BuyerEmail,
    [property: JsonPropertyName("delivery_time")] long DeliveryTime,
    [property: JsonPropertyName("need_upload_invoice")] string NeedUploadInvoice,
    [property: JsonPropertyName("is_cod")] bool IsCod,
    [property: JsonPropertyName("request_cancel_time")] long RequestCancelTime,
    [property: JsonPropertyName("delivery_option_required_delivery_time")] long DeliveryOptionRequiredDeliveryTime,
    [property: JsonPropertyName("delivery_option_name")] string DeliveryOptionName,
    [property: JsonPropertyName("is_buyer_request_cancel")] bool IsBuyerRequestCancel,
    [property: JsonPropertyName("delivery_due_time")] long DeliveryDueTime,
    [property: JsonPropertyName("collection_time")] long CollectionTime,
    [property: JsonPropertyName("is_on_hold_order")] bool IsOnHoldOrder,
    [property: JsonPropertyName("cancel_time")] long CancelTime,
    [property: JsonPropertyName("is_replacement_order")] bool IsReplacementOrder,
    [property: JsonPropertyName("replaced_order_id")] string ReplacedOrderId,
    [property: JsonPropertyName("collection_due_time")] long CollectionDueTime,
    [property: JsonPropertyName("pick_up_cut_off_time")] long PickUpCutOffTime,
    [property: JsonPropertyName("fast_dispatch_sla_time")] long FastDispatchSlaTime,
    [property: JsonPropertyName("commerce_platform")] string CommercePlatform,
    [property: JsonPropertyName("order_type")] string OrderType,
    [property: JsonPropertyName("release_date")] long ReleaseDate,
    [property: JsonPropertyName("handling_duration")] OrderGetOrderDetailResponseDataOrdersHandlingDuration HandlingDuration,
    [property: JsonPropertyName("auto_combine_group_id")] string AutoCombineGroupId,
    [property: JsonPropertyName("cpf_name")] string CpfName,
    [property: JsonPropertyName("is_exchange_order")] bool IsExchangeOrder,
    [property: JsonPropertyName("exchange_source_order_id")] string ExchangeSourceOrderId,
    [property: JsonPropertyName("is_subscription_order")] bool IsSubscriptionOrder,
    [property: JsonPropertyName("consultation_id")] string ConsultationId,
    [property: JsonPropertyName("fast_delivery_program")] string FastDeliveryProgram,
    [property: JsonPropertyName("buyer_nickname")] string BuyerNickname,
    [property: JsonPropertyName("buyer_avatar")] string BuyerAvatar,
    [property: JsonPropertyName("order_rights")] IReadOnlyList<long> OrderRights,
    [property: JsonPropertyName("fulfillment_priority_level")] long FulfillmentPriorityLevel,
    [property: JsonPropertyName("recommended_shipping_time")] long RecommendedShippingTime);

public sealed record OrderGetOrderDetailResponseDataOrdersPayment(
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("sub_total")] string SubTotal,
    [property: JsonPropertyName("shipping_fee")] string ShippingFee,
    [property: JsonPropertyName("seller_discount")] string SellerDiscount,
    [property: JsonPropertyName("platform_discount")] string PlatformDiscount,
    [property: JsonPropertyName("payment_platform_discount")] string PaymentPlatformDiscount,
    [property: JsonPropertyName("payment_discount_service_fee")] string PaymentDiscountServiceFee,
    [property: JsonPropertyName("total_amount")] string TotalAmount,
    [property: JsonPropertyName("original_total_product_price")] string OriginalTotalProductPrice,
    [property: JsonPropertyName("original_shipping_fee")] string OriginalShippingFee,
    [property: JsonPropertyName("shipping_fee_seller_discount")] string ShippingFeeSellerDiscount,
    [property: JsonPropertyName("shipping_fee_platform_discount")] string ShippingFeePlatformDiscount,
    [property: JsonPropertyName("shipping_fee_cofunded_discount")] string ShippingFeeCofundedDiscount,
    [property: JsonPropertyName("tax")] string Tax,
    [property: JsonPropertyName("small_order_fee")] string SmallOrderFee,
    [property: JsonPropertyName("shipping_fee_tax")] string ShippingFeeTax,
    [property: JsonPropertyName("product_tax")] string ProductTax,
    [property: JsonPropertyName("retail_delivery_fee")] string RetailDeliveryFee,
    [property: JsonPropertyName("buyer_service_fee")] string BuyerServiceFee,
    [property: JsonPropertyName("handling_fee")] string HandlingFee,
    [property: JsonPropertyName("shipping_insurance_fee")] string ShippingInsuranceFee,
    [property: JsonPropertyName("item_insurance_fee")] string ItemInsuranceFee,
    [property: JsonPropertyName("item_insurance_tax")] string ItemInsuranceTax,
    [property: JsonPropertyName("distance_shipping_fee")] string DistanceShippingFee,
    [property: JsonPropertyName("distance_fee")] string DistanceFee);

public sealed record OrderGetOrderDetailResponseDataOrdersRecipientAddress(
    [property: JsonPropertyName("full_address")] string FullAddress,
    [property: JsonPropertyName("phone_number")] string PhoneNumber,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("first_name")] string FirstName,
    [property: JsonPropertyName("last_name")] string LastName,
    [property: JsonPropertyName("first_name_local_script")] string FirstNameLocalScript,
    [property: JsonPropertyName("last_name_local_script")] string LastNameLocalScript,
    [property: JsonPropertyName("region_code")] string RegionCode,
    [property: JsonPropertyName("postal_code")] string PostalCode,
    [property: JsonPropertyName("post_town")] string PostTown,
    [property: JsonPropertyName("address_line1")] string AddressLine1,
    [property: JsonPropertyName("address_line2")] string AddressLine2,
    [property: JsonPropertyName("address_line3")] string AddressLine3,
    [property: JsonPropertyName("address_line4")] string AddressLine4,
    [property: JsonPropertyName("district_info")] IReadOnlyList<OrderGetOrderDetailResponseDataOrdersRecipientAddressDistrictInfo> DistrictInfo,
    [property: JsonPropertyName("delivery_preferences")] OrderGetOrderDetailResponseDataOrdersRecipientAddressDeliveryPreferences DeliveryPreferences,
    [property: JsonPropertyName("address_detail")] string AddressDetail);

public sealed record OrderGetOrderDetailResponseDataOrdersRecipientAddressDistrictInfo(
    [property: JsonPropertyName("address_level_name")] string AddressLevelName,
    [property: JsonPropertyName("address_name")] string AddressName,
    [property: JsonPropertyName("address_level")] string AddressLevel,
    [property: JsonPropertyName("iso_code")] string IsoCode);

public sealed record OrderGetOrderDetailResponseDataOrdersRecipientAddressDeliveryPreferences(
    [property: JsonPropertyName("drop_off_location")] string DropOffLocation);

public sealed record OrderGetOrderDetailResponseDataOrdersPackages(
    [property: JsonPropertyName("id")] string Id);

public sealed record OrderGetOrderDetailResponseDataOrdersLineItems(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("combined_listing_skus")] IReadOnlyList<OrderGetOrderDetailResponseDataOrdersLineItemsCombinedListingSkus> CombinedListingSkus,
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("product_name")] string ProductName,
    [property: JsonPropertyName("sku_name")] string SkuName,
    [property: JsonPropertyName("sku_image")] string SkuImage,
    [property: JsonPropertyName("original_price")] string OriginalPrice,
    [property: JsonPropertyName("sale_price")] string SalePrice,
    [property: JsonPropertyName("pfand_fee")] string PfandFee,
    [property: JsonPropertyName("platform_discount")] string PlatformDiscount,
    [property: JsonPropertyName("display_status")] string DisplayStatus,
    [property: JsonPropertyName("cancel_user")] string CancelUser,
    [property: JsonPropertyName("sku_type")] string SkuType,
    [property: JsonPropertyName("seller_sku")] string SellerSku,
    [property: JsonPropertyName("shipping_provider_id")] string ShippingProviderId,
    [property: JsonPropertyName("seller_discount")] string SellerDiscount,
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("package_id")] string PackageId,
    [property: JsonPropertyName("rts_time")] long RtsTime,
    [property: JsonPropertyName("item_tax")] IReadOnlyList<OrderGetOrderDetailResponseDataOrdersLineItemsItemTax> ItemTax,
    [property: JsonPropertyName("package_status")] string PackageStatus,
    [property: JsonPropertyName("shipping_provider_name")] string ShippingProviderName,
    [property: JsonPropertyName("is_gift")] bool IsGift,
    [property: JsonPropertyName("cancel_reason")] string CancelReason,
    [property: JsonPropertyName("small_order_fee")] string SmallOrderFee,
    [property: JsonPropertyName("retail_delivery_fee")] string RetailDeliveryFee,
    [property: JsonPropertyName("tracking_number")] string TrackingNumber,
    [property: JsonPropertyName("buyer_service_fee")] string BuyerServiceFee,
    [property: JsonPropertyName("handling_duration_days")] string HandlingDurationDays,
    [property: JsonPropertyName("is_dangerous_good")] bool IsDangerousGood,
    [property: JsonPropertyName("needs_prescription")] bool NeedsPrescription,
    [property: JsonPropertyName("gift_retail_price")] string GiftRetailPrice,
    [property: JsonPropertyName("is_unboxing_item")] bool IsUnboxingItem,
    [property: JsonPropertyName("unboxing_sku_code")] string UnboxingSkuCode,
    [property: JsonPropertyName("sub_item_info")] IReadOnlyList<OrderGetOrderDetailResponseDataOrdersLineItemsSubItemInfo> SubItemInfo,
    [property: JsonPropertyName("distance_shipping_fee")] string DistanceShippingFee,
    [property: JsonPropertyName("distance_fee")] string DistanceFee);

public sealed record OrderGetOrderDetailResponseDataOrdersLineItemsCombinedListingSkus(
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("sku_count")] long SkuCount,
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("seller_sku")] string SellerSku);

public sealed record OrderGetOrderDetailResponseDataOrdersLineItemsItemTax(
    [property: JsonPropertyName("tax_type")] string TaxType,
    [property: JsonPropertyName("tax_amount")] string TaxAmount,
    [property: JsonPropertyName("tax_rate")] string TaxRate);

public sealed record OrderGetOrderDetailResponseDataOrdersLineItemsSubItemInfo(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("sku_id")] string SkuId,
    [property: JsonPropertyName("display_status")] string DisplayStatus,
    [property: JsonPropertyName("product_name")] string ProductName,
    [property: JsonPropertyName("seller_sku")] string SellerSku,
    [property: JsonPropertyName("sku_image")] string SkuImage,
    [property: JsonPropertyName("sku_name")] string SkuName,
    [property: JsonPropertyName("product_id")] string ProductId,
    [property: JsonPropertyName("sale_price")] string SalePrice,
    [property: JsonPropertyName("platform_discount")] string PlatformDiscount,
    [property: JsonPropertyName("seller_discount")] string SellerDiscount,
    [property: JsonPropertyName("cancel_reason")] string CancelReason,
    [property: JsonPropertyName("original_price")] string OriginalPrice,
    [property: JsonPropertyName("rts_time")] long RtsTime,
    [property: JsonPropertyName("package_status")] string PackageStatus,
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("shipping_provider_name")] string ShippingProviderName,
    [property: JsonPropertyName("cancel_user")] string CancelUser,
    [property: JsonPropertyName("shipping_provider_id")] string ShippingProviderId,
    [property: JsonPropertyName("item_tax")] IReadOnlyList<OrderGetOrderDetailResponseDataOrdersLineItemsSubItemInfoItemTax> ItemTax,
    [property: JsonPropertyName("tracking_number")] string TrackingNumber,
    [property: JsonPropertyName("package_id")] string PackageId,
    [property: JsonPropertyName("retail_delivery_fee")] string RetailDeliveryFee,
    [property: JsonPropertyName("is_dangerous_good")] bool IsDangerousGood,
    [property: JsonPropertyName("warehouse_id")] string WarehouseId);

public sealed record OrderGetOrderDetailResponseDataOrdersLineItemsSubItemInfoItemTax(
    [property: JsonPropertyName("tax_type")] string TaxType,
    [property: JsonPropertyName("tax_amount")] string TaxAmount,
    [property: JsonPropertyName("tax_rate")] string TaxRate);

public sealed record OrderGetOrderDetailResponseDataOrdersHandlingDuration(
    [property: JsonPropertyName("days")] string Days,
    [property: JsonPropertyName("type")] string Type);


public sealed record OrderUpdateTheBlindBoxOpeningResultsRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("main_order_id")] string MainOrderId,
    [property: JsonPropertyName("blind_box_results")] IReadOnlyList<OrderUpdateTheBlindBoxOpeningResultsRequestBlindBoxResults> BlindBoxResults);

public sealed record OrderUpdateTheBlindBoxOpeningResultsRequestBlindBoxResults(
    [property: JsonPropertyName("order_line_id")] string OrderLineId,
    [property: JsonPropertyName("blind_result_product_id")] string BlindResultProductId,
    [property: JsonPropertyName("blind_result_sku_id")] string BlindResultSkuId,
    [property: JsonPropertyName("blind_open_time")] long BlindOpenTime);


public sealed record OrderUpdateTheBlindBoxOpeningResultsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] object Data);
