// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;
namespace TikTokPartnerSdk.Generated.Fulfillment;

public sealed record FulfillmentBatchShipPackagesRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("packages")] IReadOnlyList<FulfillmentBatchShipPackagesRequestPackages> Packages);

public sealed record FulfillmentBatchShipPackagesRequestPackages(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("handover_method")] string HandoverMethod,
    [property: JsonPropertyName("pickup_slot")] FulfillmentBatchShipPackagesRequestPackagesPickupSlot PickupSlot,
    [property: JsonPropertyName("self_shipment")] FulfillmentBatchShipPackagesRequestPackagesSelfShipment SelfShipment);

public sealed record FulfillmentBatchShipPackagesRequestPackagesPickupSlot(
    [property: JsonPropertyName("start_time")] long StartTime,
    [property: JsonPropertyName("end_time")] long EndTime);

public sealed record FulfillmentBatchShipPackagesRequestPackagesSelfShipment(
    [property: JsonPropertyName("tracking_number")] string TrackingNumber,
    [property: JsonPropertyName("shipping_provider_id")] string ShippingProviderId);


public sealed record FulfillmentBatchShipPackagesResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentBatchShipPackagesResponseData Data);

public sealed record FulfillmentBatchShipPackagesResponseData(
    [property: JsonPropertyName("errors")] IReadOnlyList<FulfillmentBatchShipPackagesResponseDataErrors> Errors);

public sealed record FulfillmentBatchShipPackagesResponseDataErrors(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("detail")] FulfillmentBatchShipPackagesResponseDataErrorsDetail Detail);

public sealed record FulfillmentBatchShipPackagesResponseDataErrorsDetail(
    [property: JsonPropertyName("package_id")] string PackageId);


public sealed record FulfillmentCombinePackageRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("combinable_packages")] IReadOnlyList<FulfillmentCombinePackageRequestCombinablePackages> CombinablePackages);

public sealed record FulfillmentCombinePackageRequestCombinablePackages(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("order_ids")] IReadOnlyList<string> OrderIds);


public sealed record FulfillmentCombinePackageResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentCombinePackageResponseData Data);

public sealed record FulfillmentCombinePackageResponseData(
    [property: JsonPropertyName("packages")] IReadOnlyList<FulfillmentCombinePackageResponseDataPackages> Packages,
    [property: JsonPropertyName("errors")] IReadOnlyList<FulfillmentCombinePackageResponseDataErrors> Errors);

public sealed record FulfillmentCombinePackageResponseDataPackages(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("order_ids")] IReadOnlyList<string> OrderIds);

public sealed record FulfillmentCombinePackageResponseDataErrors(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("detail")] FulfillmentCombinePackageResponseDataErrorsDetail Detail);

public sealed record FulfillmentCombinePackageResponseDataErrorsDetail(
    [property: JsonPropertyName("package_id")] string PackageId);


public sealed record FulfillmentFulfillmentUploadDeliveryFileRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("category_asset_cipher")] string CategoryAssetCipher,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("data")] string Data,
    [property: JsonPropertyName("name")] string Name);


public sealed record FulfillmentFulfillmentUploadDeliveryFileResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentFulfillmentUploadDeliveryFileResponseData Data);

public sealed record FulfillmentFulfillmentUploadDeliveryFileResponseData(
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("name")] string Name);


public sealed record FulfillmentFulfillmentUploadDeliveryImageRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("category_asset_cipher")] string CategoryAssetCipher,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("data")] string Data);


public sealed record FulfillmentFulfillmentUploadDeliveryImageResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentFulfillmentUploadDeliveryImageResponseData Data);

public sealed record FulfillmentFulfillmentUploadDeliveryImageResponseData(
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("height")] long Height,
    [property: JsonPropertyName("width")] long Width);


public sealed record FulfillmentGetEligibleShippingServiceRequest(
    [property: JsonPropertyName("order_id")] string OrderId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("order_line_item_ids")] IReadOnlyList<string> OrderLineItemIds,
    [property: JsonPropertyName("weight")] FulfillmentGetEligibleShippingServiceRequestWeight Weight,
    [property: JsonPropertyName("dimension")] FulfillmentGetEligibleShippingServiceRequestDimension Dimension,
    [property: JsonPropertyName("order_line_list")] IReadOnlyList<FulfillmentGetEligibleShippingServiceRequestOrderLineList> OrderLineList);

public sealed record FulfillmentGetEligibleShippingServiceRequestWeight(
    [property: JsonPropertyName("value")] string Value,
    [property: JsonPropertyName("unit")] string Unit);

public sealed record FulfillmentGetEligibleShippingServiceRequestDimension(
    [property: JsonPropertyName("length")] string Length,
    [property: JsonPropertyName("width")] string Width,
    [property: JsonPropertyName("height")] string Height,
    [property: JsonPropertyName("unit")] string Unit);

public sealed record FulfillmentGetEligibleShippingServiceRequestOrderLineList(
    [property: JsonPropertyName("order_line_id")] string OrderLineId,
    [property: JsonPropertyName("sub_item_id")] string SubItemId);


public sealed record FulfillmentGetEligibleShippingServiceResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentGetEligibleShippingServiceResponseData Data);

public sealed record FulfillmentGetEligibleShippingServiceResponseData(
    [property: JsonPropertyName("order_id")] string OrderId,
    [property: JsonPropertyName("order_line_id")] IReadOnlyList<string> OrderLineId,
    [property: JsonPropertyName("weight")] FulfillmentGetEligibleShippingServiceResponseDataWeight Weight,
    [property: JsonPropertyName("shipping_services")] IReadOnlyList<FulfillmentGetEligibleShippingServiceResponseDataShippingServices> ShippingServices,
    [property: JsonPropertyName("dimension")] FulfillmentGetEligibleShippingServiceResponseDataDimension Dimension);

public sealed record FulfillmentGetEligibleShippingServiceResponseDataWeight(
    [property: JsonPropertyName("value")] string Value,
    [property: JsonPropertyName("unit")] string Unit);

public sealed record FulfillmentGetEligibleShippingServiceResponseDataShippingServices(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("price")] string Price,
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("earliest_delivery_days")] long EarliestDeliveryDays,
    [property: JsonPropertyName("latest_delivery_days")] long LatestDeliveryDays,
    [property: JsonPropertyName("is_default")] bool IsDefault,
    [property: JsonPropertyName("shipping_provider_name")] string ShippingProviderName,
    [property: JsonPropertyName("shipping_provider_id")] string ShippingProviderId,
    [property: JsonPropertyName("shipping_fee")] string ShippingFee,
    [property: JsonPropertyName("shipping_app_service_fee")] string ShippingAppServiceFee,
    [property: JsonPropertyName("signature_fee")] string SignatureFee);

public sealed record FulfillmentGetEligibleShippingServiceResponseDataDimension(
    [property: JsonPropertyName("length")] string Length,
    [property: JsonPropertyName("width")] string Width,
    [property: JsonPropertyName("height")] string Height,
    [property: JsonPropertyName("unit")] string Unit);


public sealed record FulfillmentGetOrderSplitAttributesRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("order_ids")] IReadOnlyList<string> OrderIds,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record FulfillmentGetOrderSplitAttributesResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentGetOrderSplitAttributesResponseData Data);

public sealed record FulfillmentGetOrderSplitAttributesResponseData(
    [property: JsonPropertyName("split_attributes")] IReadOnlyList<FulfillmentGetOrderSplitAttributesResponseDataSplitAttributes> SplitAttributes);

public sealed record FulfillmentGetOrderSplitAttributesResponseDataSplitAttributes(
    [property: JsonPropertyName("order_id")] string OrderId,
    [property: JsonPropertyName("can_split")] bool CanSplit,
    [property: JsonPropertyName("reason")] string Reason,
    [property: JsonPropertyName("must_split")] bool MustSplit,
    [property: JsonPropertyName("must_split_reasons")] IReadOnlyList<FulfillmentGetOrderSplitAttributesResponseDataSplitAttributesMustSplitReasons> MustSplitReasons);

public sealed record FulfillmentGetOrderSplitAttributesResponseDataSplitAttributesMustSplitReasons(
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("category_id")] string CategoryId,
    [property: JsonPropertyName("max_count")] string MaxCount);


public sealed record FulfillmentGetPackageDetailRequest(
    [property: JsonPropertyName("package_id")] string PackageId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record FulfillmentGetPackageDetailResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentGetPackageDetailResponseData Data);

public sealed record FulfillmentGetPackageDetailResponseData(
    [property: JsonPropertyName("package_id")] string PackageId,
    [property: JsonPropertyName("orders")] IReadOnlyList<FulfillmentGetPackageDetailResponseDataOrders> Orders,
    [property: JsonPropertyName("package_status")] string PackageStatus,
    [property: JsonPropertyName("package_sub_status")] string PackageSubStatus,
    [property: JsonPropertyName("ship_exception_reason")] string ShipExceptionReason,
    [property: JsonPropertyName("split_and_combine_tag")] string SplitAndCombineTag,
    [property: JsonPropertyName("has_multi_skus")] bool HasMultiSkus,
    [property: JsonPropertyName("note_tag")] string NoteTag,
    [property: JsonPropertyName("shipping_provider_name")] string ShippingProviderName,
    [property: JsonPropertyName("shipping_provider_id")] string ShippingProviderId,
    [property: JsonPropertyName("shipping_type")] string ShippingType,
    [property: JsonPropertyName("delivery_option_name")] string DeliveryOptionName,
    [property: JsonPropertyName("delivery_option_id")] string DeliveryOptionId,
    [property: JsonPropertyName("tracking_number")] string TrackingNumber,
    [property: JsonPropertyName("last_mile_tracking_number")] string LastMileTrackingNumber,
    [property: JsonPropertyName("pickup_slot")] FulfillmentGetPackageDetailResponseDataPickupSlot PickupSlot,
    [property: JsonPropertyName("create_time")] long CreateTime,
    [property: JsonPropertyName("handover_method")] string HandoverMethod,
    [property: JsonPropertyName("order_line_item_ids")] IReadOnlyList<string> OrderLineItemIds,
    [property: JsonPropertyName("recipient_address")] FulfillmentGetPackageDetailResponseDataRecipientAddress RecipientAddress,
    [property: JsonPropertyName("sender_address")] FulfillmentGetPackageDetailResponseDataSenderAddress SenderAddress,
    [property: JsonPropertyName("weight")] FulfillmentGetPackageDetailResponseDataWeight Weight,
    [property: JsonPropertyName("dimension")] FulfillmentGetPackageDetailResponseDataDimension Dimension,
    [property: JsonPropertyName("update_time")] long UpdateTime,
    [property: JsonPropertyName("insurance")] FulfillmentGetPackageDetailResponseDataInsurance Insurance,
    [property: JsonPropertyName("biz_extension_tags")] IReadOnlyList<string> BizExtensionTags);

public sealed record FulfillmentGetPackageDetailResponseDataOrders(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("skus")] IReadOnlyList<FulfillmentGetPackageDetailResponseDataOrdersSkus> Skus);

public sealed record FulfillmentGetPackageDetailResponseDataOrdersSkus(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("image_url")] string ImageUrl,
    [property: JsonPropertyName("quantity")] long Quantity);

public sealed record FulfillmentGetPackageDetailResponseDataPickupSlot(
    [property: JsonPropertyName("start_time")] long StartTime,
    [property: JsonPropertyName("end_time")] long EndTime);

public sealed record FulfillmentGetPackageDetailResponseDataRecipientAddress(
    [property: JsonPropertyName("full_address")] string FullAddress,
    [property: JsonPropertyName("phone_number")] string PhoneNumber,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("postal_code")] string PostalCode,
    [property: JsonPropertyName("address_detail")] string AddressDetail,
    [property: JsonPropertyName("region_code")] string RegionCode,
    [property: JsonPropertyName("address_line1")] string AddressLine1,
    [property: JsonPropertyName("address_line2")] string AddressLine2,
    [property: JsonPropertyName("address_line3")] string AddressLine3,
    [property: JsonPropertyName("address_line4")] string AddressLine4);

public sealed record FulfillmentGetPackageDetailResponseDataSenderAddress(
    [property: JsonPropertyName("full_address")] string FullAddress,
    [property: JsonPropertyName("phone_number")] string PhoneNumber,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("postal_code")] string PostalCode,
    [property: JsonPropertyName("address_detail")] string AddressDetail,
    [property: JsonPropertyName("region_code")] string RegionCode,
    [property: JsonPropertyName("address_line1")] string AddressLine1,
    [property: JsonPropertyName("address_line2")] string AddressLine2,
    [property: JsonPropertyName("address_line3")] string AddressLine3,
    [property: JsonPropertyName("address_line4")] string AddressLine4);

public sealed record FulfillmentGetPackageDetailResponseDataWeight(
    [property: JsonPropertyName("value")] string Value,
    [property: JsonPropertyName("unit")] string Unit);

public sealed record FulfillmentGetPackageDetailResponseDataDimension(
    [property: JsonPropertyName("length")] string Length,
    [property: JsonPropertyName("width")] string Width,
    [property: JsonPropertyName("height")] string Height,
    [property: JsonPropertyName("unit")] string Unit);

public sealed record FulfillmentGetPackageDetailResponseDataInsurance(
    [property: JsonPropertyName("is_purchased")] bool IsPurchased,
    [property: JsonPropertyName("coverage_amount")] string CoverageAmount,
    [property: JsonPropertyName("is_claim_eligible")] bool IsClaimEligible,
    [property: JsonPropertyName("claim_status")] string ClaimStatus);


public sealed record FulfillmentGetPackageHandoverTimeSlotsRequest(
    [property: JsonPropertyName("package_id")] string PackageId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record FulfillmentGetPackageHandoverTimeSlotsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentGetPackageHandoverTimeSlotsResponseData Data);

public sealed record FulfillmentGetPackageHandoverTimeSlotsResponseData(
    [property: JsonPropertyName("can_pickup")] bool CanPickup,
    [property: JsonPropertyName("can_drop_off")] bool CanDropOff,
    [property: JsonPropertyName("can_van_collection")] bool CanVanCollection,
    [property: JsonPropertyName("drop_off_point_url")] string DropOffPointUrl,
    [property: JsonPropertyName("pickup_slots")] IReadOnlyList<FulfillmentGetPackageHandoverTimeSlotsResponseDataPickupSlots> PickupSlots);

public sealed record FulfillmentGetPackageHandoverTimeSlotsResponseDataPickupSlots(
    [property: JsonPropertyName("start_time")] long StartTime,
    [property: JsonPropertyName("end_time")] long EndTime,
    [property: JsonPropertyName("avaliable")] bool Avaliable);


public sealed record FulfillmentGetPackageShippingDocumentRequest(
    [property: JsonPropertyName("package_id")] string PackageId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("document_format")] string DocumentFormat,
    [property: JsonPropertyName("document_size")] string DocumentSize,
    [property: JsonPropertyName("document_type")] string DocumentType,
    [property: JsonPropertyName("shipping_period")] string ShippingPeriod,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record FulfillmentGetPackageShippingDocumentResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentGetPackageShippingDocumentResponseData Data);

public sealed record FulfillmentGetPackageShippingDocumentResponseData(
    [property: JsonPropertyName("doc_url")] string DocUrl,
    [property: JsonPropertyName("tracking_number")] string TrackingNumber);


public sealed record FulfillmentGetTrackingRequest(
    [property: JsonPropertyName("order_id")] string OrderId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record FulfillmentGetTrackingResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentGetTrackingResponseData Data);

public sealed record FulfillmentGetTrackingResponseData(
    [property: JsonPropertyName("tracking")] IReadOnlyList<FulfillmentGetTrackingResponseDataTracking> Tracking);

public sealed record FulfillmentGetTrackingResponseDataTracking(
    [property: JsonPropertyName("description")] string Description,
    [property: JsonPropertyName("update_time_millis")] long UpdateTimeMillis,
    [property: JsonPropertyName("action_code")] long ActionCode);


public sealed record FulfillmentMarkPackageAsShippedRequest(
    [property: JsonPropertyName("order_id")] string OrderId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("order_line_item_ids")] IReadOnlyList<string> OrderLineItemIds,
    [property: JsonPropertyName("tracking_number")] string TrackingNumber,
    [property: JsonPropertyName("shipping_provider_id")] string ShippingProviderId,
    [property: JsonPropertyName("order_line_list")] IReadOnlyList<FulfillmentMarkPackageAsShippedRequestOrderLineList> OrderLineList);

public sealed record FulfillmentMarkPackageAsShippedRequestOrderLineList(
    [property: JsonPropertyName("order_line_id")] string OrderLineId,
    [property: JsonPropertyName("sub_item_id")] string SubItemId);


public sealed record FulfillmentMarkPackageAsShippedResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentMarkPackageAsShippedResponseData Data);

public sealed record FulfillmentMarkPackageAsShippedResponseData(
    [property: JsonPropertyName("order_id")] string OrderId,
    [property: JsonPropertyName("order_line_item_ids")] IReadOnlyList<string> OrderLineItemIds,
    [property: JsonPropertyName("package_id")] string PackageId,
    [property: JsonPropertyName("warning")] FulfillmentMarkPackageAsShippedResponseDataWarning Warning);

public sealed record FulfillmentMarkPackageAsShippedResponseDataWarning(
    [property: JsonPropertyName("message")] string Message);


public sealed record FulfillmentSearchCombinablePackagesRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("page_size")] long PageSize,
    [property: JsonPropertyName("page_token")] string PageToken,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record FulfillmentSearchCombinablePackagesResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentSearchCombinablePackagesResponseData Data);

public sealed record FulfillmentSearchCombinablePackagesResponseData(
    [property: JsonPropertyName("combinable_packages")] IReadOnlyList<FulfillmentSearchCombinablePackagesResponseDataCombinablePackages> CombinablePackages,
    [property: JsonPropertyName("next_page_token")] string NextPageToken,
    [property: JsonPropertyName("total_count")] long TotalCount);

public sealed record FulfillmentSearchCombinablePackagesResponseDataCombinablePackages(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("order_ids")] IReadOnlyList<string> OrderIds);


public sealed record FulfillmentSearchPackageRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("page_size")] long PageSize,
    [property: JsonPropertyName("page_token")] string PageToken,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("sort_field")] string SortField,
    [property: JsonPropertyName("sort_order")] string SortOrder,
    [property: JsonPropertyName("create_time_ge")] long CreateTimeGe,
    [property: JsonPropertyName("create_time_lt")] long CreateTimeLt,
    [property: JsonPropertyName("update_time_ge")] long UpdateTimeGe,
    [property: JsonPropertyName("update_time_lt")] long UpdateTimeLt,
    [property: JsonPropertyName("package_status")] string PackageStatus);


public sealed record FulfillmentSearchPackageResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentSearchPackageResponseData Data);

public sealed record FulfillmentSearchPackageResponseData(
    [property: JsonPropertyName("next_page_token")] string NextPageToken,
    [property: JsonPropertyName("total_count")] long TotalCount,
    [property: JsonPropertyName("packages")] IReadOnlyList<FulfillmentSearchPackageResponseDataPackages> Packages);

public sealed record FulfillmentSearchPackageResponseDataPackages(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("orders")] IReadOnlyList<FulfillmentSearchPackageResponseDataPackagesOrders> Orders,
    [property: JsonPropertyName("create_time")] long CreateTime,
    [property: JsonPropertyName("update_time")] long UpdateTime,
    [property: JsonPropertyName("status")] string Status,
    [property: JsonPropertyName("tracking_number")] string TrackingNumber,
    [property: JsonPropertyName("shipping_provider_name")] string ShippingProviderName,
    [property: JsonPropertyName("shipping_provider_id")] string ShippingProviderId,
    [property: JsonPropertyName("order_line_item_ids")] IReadOnlyList<string> OrderLineItemIds);

public sealed record FulfillmentSearchPackageResponseDataPackagesOrders(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("skus")] IReadOnlyList<FulfillmentSearchPackageResponseDataPackagesOrdersSkus> Skus);

public sealed record FulfillmentSearchPackageResponseDataPackagesOrdersSkus(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("image_url")] string ImageUrl,
    [property: JsonPropertyName("quantity")] long Quantity);


public sealed record FulfillmentShipPackageRequest(
    [property: JsonPropertyName("package_id")] string PackageId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("handover_method")] string HandoverMethod,
    [property: JsonPropertyName("pickup_slot")] FulfillmentShipPackageRequestPickupSlot PickupSlot,
    [property: JsonPropertyName("self_shipment")] FulfillmentShipPackageRequestSelfShipment SelfShipment);

public sealed record FulfillmentShipPackageRequestPickupSlot(
    [property: JsonPropertyName("start_time")] long StartTime,
    [property: JsonPropertyName("end_time")] long EndTime);

public sealed record FulfillmentShipPackageRequestSelfShipment(
    [property: JsonPropertyName("tracking_number")] string TrackingNumber,
    [property: JsonPropertyName("shipping_provider_id")] string ShippingProviderId);


public sealed record FulfillmentShipPackageResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] object Data);


public sealed record FulfillmentSplitOrdersRequest(
    [property: JsonPropertyName("order_id")] string OrderId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("splittable_groups")] IReadOnlyList<FulfillmentSplitOrdersRequestSplittableGroups> SplittableGroups,
    [property: JsonPropertyName("splittable_groups_v2")] IReadOnlyList<FulfillmentSplitOrdersRequestSplittableGroupsV2> SplittableGroupsV2);

public sealed record FulfillmentSplitOrdersRequestSplittableGroups(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("order_line_item_ids")] IReadOnlyList<string> OrderLineItemIds);

public sealed record FulfillmentSplitOrdersRequestSplittableGroupsV2(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("order_line_list")] IReadOnlyList<FulfillmentSplitOrdersRequestSplittableGroupsV2OrderLineList> OrderLineList);

public sealed record FulfillmentSplitOrdersRequestSplittableGroupsV2OrderLineList(
    [property: JsonPropertyName("order_line_id")] string OrderLineId,
    [property: JsonPropertyName("sub_item_id")] string SubItemId);


public sealed record FulfillmentSplitOrdersResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentSplitOrdersResponseData Data);

public sealed record FulfillmentSplitOrdersResponseData(
    [property: JsonPropertyName("packages")] IReadOnlyList<FulfillmentSplitOrdersResponseDataPackages> Packages);

public sealed record FulfillmentSplitOrdersResponseDataPackages(
    [property: JsonPropertyName("splittable_group_id")] string SplittableGroupId,
    [property: JsonPropertyName("id")] string Id);


public sealed record FulfillmentUncombinePackagesRequest(
    [property: JsonPropertyName("package_id")] string PackageId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("order_ids")] IReadOnlyList<string> OrderIds);


public sealed record FulfillmentUncombinePackagesResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentUncombinePackagesResponseData Data);

public sealed record FulfillmentUncombinePackagesResponseData(
    [property: JsonPropertyName("packages")] IReadOnlyList<FulfillmentUncombinePackagesResponseDataPackages> Packages);

public sealed record FulfillmentUncombinePackagesResponseDataPackages(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("order_ids")] IReadOnlyList<string> OrderIds);


public sealed record FulfillmentUpdatePackageDeliveryStatusRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("packages")] IReadOnlyList<FulfillmentUpdatePackageDeliveryStatusRequestPackages> Packages);

public sealed record FulfillmentUpdatePackageDeliveryStatusRequestPackages(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("delivery_type")] string DeliveryType,
    [property: JsonPropertyName("fail_delivery_reason")] string FailDeliveryReason,
    [property: JsonPropertyName("file_type")] string FileType,
    [property: JsonPropertyName("file_url")] string FileUrl);


public sealed record FulfillmentUpdatePackageDeliveryStatusResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentUpdatePackageDeliveryStatusResponseData Data);

public sealed record FulfillmentUpdatePackageDeliveryStatusResponseData(
    [property: JsonPropertyName("errors")] IReadOnlyList<FulfillmentUpdatePackageDeliveryStatusResponseDataErrors> Errors);

public sealed record FulfillmentUpdatePackageDeliveryStatusResponseDataErrors(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("detail")] FulfillmentUpdatePackageDeliveryStatusResponseDataErrorsDetail Detail);

public sealed record FulfillmentUpdatePackageDeliveryStatusResponseDataErrorsDetail(
    [property: JsonPropertyName("package_id")] string PackageId);


public sealed record FulfillmentUpdatePackageShippingInfoRequest(
    [property: JsonPropertyName("package_id")] string PackageId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("tracking_number")] string TrackingNumber,
    [property: JsonPropertyName("shipping_provider_id")] string ShippingProviderId);


public sealed record FulfillmentUpdatePackageShippingInfoResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] object Data);


public sealed record FulfillmentUpdateShippingInfoRequest(
    [property: JsonPropertyName("order_id")] string OrderId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("tracking_number")] string TrackingNumber,
    [property: JsonPropertyName("shipping_provider_id")] string ShippingProviderId);


public sealed record FulfillmentUpdateShippingInfoResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] object Data);


public sealed record FulfillmentCreateFirstMileBundleRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("order_ids")] IReadOnlyList<string> OrderIds,
    [property: JsonPropertyName("handover_method")] string HandoverMethod,
    [property: JsonPropertyName("shipping_provider_id")] string ShippingProviderId,
    [property: JsonPropertyName("tracking_number")] string TrackingNumber,
    [property: JsonPropertyName("phone_tail_number")] string PhoneTailNumber);


public sealed record FulfillmentCreateFirstMileBundleResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentCreateFirstMileBundleResponseData Data);

public sealed record FulfillmentCreateFirstMileBundleResponseData(
    [property: JsonPropertyName("first_mile_bundle_id")] string FirstMileBundleId,
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("errors")] IReadOnlyList<FulfillmentCreateFirstMileBundleResponseDataErrors> Errors);

public sealed record FulfillmentCreateFirstMileBundleResponseDataErrors(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("detail")] FulfillmentCreateFirstMileBundleResponseDataErrorsDetail Detail);

public sealed record FulfillmentCreateFirstMileBundleResponseDataErrorsDetail(
    [property: JsonPropertyName("order_id")] string OrderId);


public sealed record FulfillmentUploadInvoiceRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("invoices")] IReadOnlyList<FulfillmentUploadInvoiceRequestInvoices> Invoices);

public sealed record FulfillmentUploadInvoiceRequestInvoices(
    [property: JsonPropertyName("package_id")] string PackageId,
    [property: JsonPropertyName("order_ids")] IReadOnlyList<string> OrderIds,
    [property: JsonPropertyName("file_type")] string FileType,
    [property: JsonPropertyName("file")] string File);


public sealed record FulfillmentUploadInvoiceResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentUploadInvoiceResponseData Data);

public sealed record FulfillmentUploadInvoiceResponseData(
    [property: JsonPropertyName("errors")] IReadOnlyList<FulfillmentUploadInvoiceResponseDataErrors> Errors);

public sealed record FulfillmentUploadInvoiceResponseDataErrors(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("detail")] FulfillmentUploadInvoiceResponseDataErrorsDetail Detail);

public sealed record FulfillmentUploadInvoiceResponseDataErrorsDetail(
    [property: JsonPropertyName("package_id")] string PackageId,
    [property: JsonPropertyName("order_ids")] IReadOnlyList<string> OrderIds);


public sealed record FulfillmentTtsTrackingValidationRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("tracking_number")] string TrackingNumber);


public sealed record FulfillmentTtsTrackingValidationResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentTtsTrackingValidationResponseData Data);

public sealed record FulfillmentTtsTrackingValidationResponseData(
    [property: JsonPropertyName("is_tiktok_shipping")] bool IsTiktokShipping,
    [property: JsonPropertyName("is_tiktok_collection")] bool IsTiktokCollection);


public sealed record FulfillmentCreateFirstMileBundleV2Request(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("order_ids")] IReadOnlyList<string> OrderIds,
    [property: JsonPropertyName("handover_method")] string HandoverMethod,
    [property: JsonPropertyName("shipping_provider_id")] string ShippingProviderId,
    [property: JsonPropertyName("tracking_number")] string TrackingNumber,
    [property: JsonPropertyName("phone_tail_number")] string PhoneTailNumber);


public sealed record FulfillmentCreateFirstMileBundleV2Response(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentCreateFirstMileBundleV2ResponseData Data);

public sealed record FulfillmentCreateFirstMileBundleV2ResponseData(
    [property: JsonPropertyName("first_mile_bundle_id")] string FirstMileBundleId,
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("errors")] IReadOnlyList<FulfillmentCreateFirstMileBundleV2ResponseDataErrors> Errors);

public sealed record FulfillmentCreateFirstMileBundleV2ResponseDataErrors(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("detail")] FulfillmentCreateFirstMileBundleV2ResponseDataErrorsDetail Detail);

public sealed record FulfillmentCreateFirstMileBundleV2ResponseDataErrorsDetail(
    [property: JsonPropertyName("order_id")] string OrderId);


public sealed record FulfillmentCreatePackagesRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("ship_type")] string ShipType,
    [property: JsonPropertyName("order_id")] string OrderId,
    [property: JsonPropertyName("order_line_item")] IReadOnlyList<FulfillmentCreatePackagesRequestOrderLineItem> OrderLineItem,
    [property: JsonPropertyName("order_list_ids")] IReadOnlyList<string> OrderListIds,
    [property: JsonPropertyName("dimension")] FulfillmentCreatePackagesRequestDimension Dimension,
    [property: JsonPropertyName("shipping_service_id")] string ShippingServiceId,
    [property: JsonPropertyName("weight")] FulfillmentCreatePackagesRequestWeight Weight);

public sealed record FulfillmentCreatePackagesRequestOrderLineItem(
    [property: JsonPropertyName("order_line_id")] string OrderLineId,
    [property: JsonPropertyName("sub_item_id")] string SubItemId);

public sealed record FulfillmentCreatePackagesRequestDimension(
    [property: JsonPropertyName("length")] string Length,
    [property: JsonPropertyName("width")] string Width,
    [property: JsonPropertyName("height")] string Height,
    [property: JsonPropertyName("unit")] string Unit);

public sealed record FulfillmentCreatePackagesRequestWeight(
    [property: JsonPropertyName("value")] string Value,
    [property: JsonPropertyName("unit")] string Unit);


public sealed record FulfillmentCreatePackagesResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentCreatePackagesResponseData Data);

public sealed record FulfillmentCreatePackagesResponseData(
    [property: JsonPropertyName("dimension")] FulfillmentCreatePackagesResponseDataDimension Dimension,
    [property: JsonPropertyName("shipping_service_info")] FulfillmentCreatePackagesResponseDataShippingServiceInfo ShippingServiceInfo,
    [property: JsonPropertyName("package_id")] string PackageId,
    [property: JsonPropertyName("weight")] FulfillmentCreatePackagesResponseDataWeight Weight,
    [property: JsonPropertyName("create_time")] long CreateTime);

public sealed record FulfillmentCreatePackagesResponseDataDimension(
    [property: JsonPropertyName("length")] string Length,
    [property: JsonPropertyName("width")] string Width,
    [property: JsonPropertyName("height")] string Height,
    [property: JsonPropertyName("unit")] string Unit);

public sealed record FulfillmentCreatePackagesResponseDataShippingServiceInfo(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("price")] string Price,
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("earliest_delivery_days")] long EarliestDeliveryDays,
    [property: JsonPropertyName("latest_delivery_days")] long LatestDeliveryDays,
    [property: JsonPropertyName("shipping_provider_id")] string ShippingProviderId,
    [property: JsonPropertyName("shipping_provider_name")] string ShippingProviderName);

public sealed record FulfillmentCreatePackagesResponseDataWeight(
    [property: JsonPropertyName("value")] string Value,
    [property: JsonPropertyName("unit")] string Unit);


public sealed record FulfillmentRedeemInfoCallbackRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonPropertyName("order_id")] string OrderId,
    [property: JsonPropertyName("order_info_list")] IReadOnlyList<FulfillmentRedeemInfoCallbackRequestOrderInfoList> OrderInfoList);

public sealed record FulfillmentRedeemInfoCallbackRequestOrderInfoList(
    [property: JsonPropertyName("order_line_id")] string OrderLineId,
    [property: JsonPropertyName("redeem_info")] FulfillmentRedeemInfoCallbackRequestOrderInfoListRedeemInfo RedeemInfo,
    [property: JsonPropertyName("source_unique_id")] string SourceUniqueId);

public sealed record FulfillmentRedeemInfoCallbackRequestOrderInfoListRedeemInfo(
    [property: JsonPropertyName("redeem_type")] string RedeemType,
    [property: JsonPropertyName("redeem_data")] string RedeemData);


public sealed record FulfillmentRedeemInfoCallbackResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] FulfillmentRedeemInfoCallbackResponseData Data);

public sealed record FulfillmentRedeemInfoCallbackResponseData(
    [property: JsonPropertyName("order_statuses")] IReadOnlyList<FulfillmentRedeemInfoCallbackResponseDataOrderStatuses> OrderStatuses);

public sealed record FulfillmentRedeemInfoCallbackResponseDataOrderStatuses(
    [property: JsonPropertyName("order_line_id")] string OrderLineId,
    [property: JsonPropertyName("status_code")] long StatusCode);
