// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;
namespace Loscardos.TikTokPartnerSdk.Generated.Logistics;

public sealed record LogisticsGetGlobalSellerWarehouseRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign);


public sealed record LogisticsGetGlobalSellerWarehouseResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] LogisticsGetGlobalSellerWarehouseResponseData Data);

public sealed record LogisticsGetGlobalSellerWarehouseResponseData(
    [property: JsonPropertyName("global_warehouses")] IReadOnlyList<LogisticsGetGlobalSellerWarehouseResponseDataGlobalWarehouses> GlobalWarehouses);

public sealed record LogisticsGetGlobalSellerWarehouseResponseDataGlobalWarehouses(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("ownership")] string Ownership);


public sealed record LogisticsGetShippingProvidersRequest(
    [property: JsonPropertyName("delivery_option_id")] string DeliveryOptionId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("buyer_region")] string BuyerRegion,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("warehouse_region")] string WarehouseRegion);


public sealed record LogisticsGetShippingProvidersResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] LogisticsGetShippingProvidersResponseData Data);

public sealed record LogisticsGetShippingProvidersResponseData(
    [property: JsonPropertyName("shipping_providers")] IReadOnlyList<LogisticsGetShippingProvidersResponseDataShippingProviders> ShippingProviders);

public sealed record LogisticsGetShippingProvidersResponseDataShippingProviders(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("name")] string Name);


public sealed record LogisticsGetWarehouseDeliveryOptionsRequest(
    [property: JsonPropertyName("warehouse_id")] string WarehouseId,
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("scope")] string Scope,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record LogisticsGetWarehouseDeliveryOptionsResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] LogisticsGetWarehouseDeliveryOptionsResponseData Data);

public sealed record LogisticsGetWarehouseDeliveryOptionsResponseData(
    [property: JsonPropertyName("delivery_options")] IReadOnlyList<LogisticsGetWarehouseDeliveryOptionsResponseDataDeliveryOptions> DeliveryOptions);

public sealed record LogisticsGetWarehouseDeliveryOptionsResponseDataDeliveryOptions(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("description")] string Description,
    [property: JsonPropertyName("dimension_limit")] LogisticsGetWarehouseDeliveryOptionsResponseDataDeliveryOptionsDimensionLimit DimensionLimit,
    [property: JsonPropertyName("weight_limit")] LogisticsGetWarehouseDeliveryOptionsResponseDataDeliveryOptionsWeightLimit WeightLimit,
    [property: JsonPropertyName("platform")] IReadOnlyList<string> Platform);

public sealed record LogisticsGetWarehouseDeliveryOptionsResponseDataDeliveryOptionsDimensionLimit(
    [property: JsonPropertyName("max_height")] long MaxHeight,
    [property: JsonPropertyName("max_length")] long MaxLength,
    [property: JsonPropertyName("max_width")] long MaxWidth,
    [property: JsonPropertyName("unit")] string Unit);

public sealed record LogisticsGetWarehouseDeliveryOptionsResponseDataDeliveryOptionsWeightLimit(
    [property: JsonPropertyName("max_weight")] long MaxWeight,
    [property: JsonPropertyName("min_weight")] long MinWeight,
    [property: JsonPropertyName("unit")] string Unit);


public sealed record LogisticsGetWarehouseListRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher);


public sealed record LogisticsGetWarehouseListResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] LogisticsGetWarehouseListResponseData Data);

public sealed record LogisticsGetWarehouseListResponseData(
    [property: JsonPropertyName("warehouses")] IReadOnlyList<LogisticsGetWarehouseListResponseDataWarehouses> Warehouses);

public sealed record LogisticsGetWarehouseListResponseDataWarehouses(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("entity_id")] string EntityId,
    [property: JsonPropertyName("name")] string Name,
    [property: JsonPropertyName("effect_status")] string EffectStatus,
    [property: JsonPropertyName("type")] string Type,
    [property: JsonPropertyName("sub_type")] string SubType,
    [property: JsonPropertyName("is_default")] bool IsDefault,
    [property: JsonPropertyName("address")] LogisticsGetWarehouseListResponseDataWarehousesAddress Address);

public sealed record LogisticsGetWarehouseListResponseDataWarehousesAddress(
    [property: JsonPropertyName("region")] string Region,
    [property: JsonPropertyName("state")] string State,
    [property: JsonPropertyName("city")] string City,
    [property: JsonPropertyName("distict")] string Distict,
    [property: JsonPropertyName("town")] string Town,
    [property: JsonPropertyName("contact_person")] string ContactPerson,
    [property: JsonPropertyName("first_name")] string FirstName,
    [property: JsonPropertyName("last_name")] string LastName,
    [property: JsonPropertyName("first_name_local_script")] string FirstNameLocalScript,
    [property: JsonPropertyName("last_name_local_script")] string LastNameLocalScript,
    [property: JsonPropertyName("postal_code")] string PostalCode,
    [property: JsonPropertyName("full_address")] string FullAddress,
    [property: JsonPropertyName("region_code")] string RegionCode,
    [property: JsonPropertyName("phone_number")] string PhoneNumber,
    [property: JsonPropertyName("address_line1")] string AddressLine1,
    [property: JsonPropertyName("address_line2")] string AddressLine2,
    [property: JsonPropertyName("address_line3")] string AddressLine3,
    [property: JsonPropertyName("address_line4")] string AddressLine4,
    [property: JsonPropertyName("geolocation")] LogisticsGetWarehouseListResponseDataWarehousesAddressGeolocation Geolocation);

public sealed record LogisticsGetWarehouseListResponseDataWarehousesAddressGeolocation(
    [property: JsonPropertyName("latitude")] string Latitude,
    [property: JsonPropertyName("longitude")] string Longitude);


public sealed record LogisticsGetAvailableShippingTemplateRequest(
    [property: JsonPropertyName("app_key")] string AppKey,
    [property: JsonPropertyName("timestamp")] long Timestamp,
    [property: JsonPropertyName("sign")] string Sign,
    [property: JsonPropertyName("shop_cipher")] string ShopCipher,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("product_attribute")] LogisticsGetAvailableShippingTemplateRequestProductAttribute ProductAttribute);

public sealed record LogisticsGetAvailableShippingTemplateRequestProductAttribute(
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("weight")] LogisticsGetAvailableShippingTemplateRequestProductAttributeWeight Weight,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("dimension")] LogisticsGetAvailableShippingTemplateRequestProductAttributeDimension Dimension);

public sealed record LogisticsGetAvailableShippingTemplateRequestProductAttributeWeight(
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("weight")] string Weight,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("unit")] long? Unit);

public sealed record LogisticsGetAvailableShippingTemplateRequestProductAttributeDimension(
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("length")] string Length,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("width")] string Width,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("height")] string Height,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    [property: JsonPropertyName("unit")] long? Unit);


public sealed record LogisticsGetAvailableShippingTemplateResponse(
    [property: JsonPropertyName("code")] long Code,
    [property: JsonPropertyName("message")] string Message,
    [property: JsonPropertyName("request_id")] string RequestId,
    [property: JsonPropertyName("data")] LogisticsGetAvailableShippingTemplateResponseData Data);

public sealed record LogisticsGetAvailableShippingTemplateResponseData(
    [property: JsonPropertyName("templates")] IReadOnlyList<LogisticsGetAvailableShippingTemplateResponseDataTemplates> Templates);

public sealed record LogisticsGetAvailableShippingTemplateResponseDataTemplates(
    [property: JsonPropertyName("template_is_available")] bool TemplateIsAvailable,
    [property: JsonPropertyName("template")] LogisticsGetAvailableShippingTemplateResponseDataTemplatesTemplate Template,
    [property: JsonPropertyName("service_unreachable_reason")] IReadOnlyList<LogisticsGetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReason> ServiceUnreachableReason);

public sealed record LogisticsGetAvailableShippingTemplateResponseDataTemplatesTemplate(
    [property: JsonPropertyName("template_name")] string TemplateName,
    [property: JsonPropertyName("template_id")] string TemplateId,
    [property: JsonPropertyName("is_default")] bool IsDefault,
    [property: JsonPropertyName("template_party")] long TemplateParty);

public sealed record LogisticsGetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReason(
    [property: JsonPropertyName("service_id")] string ServiceId,
    [property: JsonPropertyName("filter_reason")] IReadOnlyList<LogisticsGetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReasonFilterReason> FilterReason);

public sealed record LogisticsGetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReasonFilterReason(
    [property: JsonPropertyName("filter_type")] string FilterType,
    [property: JsonPropertyName("reason")] string Reason);
